### PR TITLE
DDF for Schneider/wiser battery switch FLS/SYSTEM-M/4

### PR DESCRIPTION
**Pull request by Smanar**
See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6141

- Product name: WDE002924
- Manufacturer: Scheider Electric
- Model identifier: FLS/SYSTEM-M/4

The DDF enable only the on/off, we have tried with @jensflorian to bind other cluster to tests, no success, but can be a different hardware/firmare.

Now some information about thoses devices. It seem Schneider play a lot with them, and they are customisable, with features that can be activated/deactivated.
They use the manufacture cluster 0xFF17

For this one, even on the hardware we have 4 endpoint, only one is used the 0x15.
On the cluster 0xFF17
- For endpoint 0x15, the attribute 0x0020 is  "0" for the other 16,17 and 18 it's "1"
- For endpoint 0x15, the attribute 0x0001 is "unknown and for the other 16,17 and 18 it's "7f"

From Z2m

> Depending on the firmware version the device may support both 1-channel and 2-channel mode. In 1-channel mode both the upper and lower buttons works as the upper buttons. On some firmware versions (incl. those sold as Elko EKO07117) the device starts out in 1-channel mode and must be switched into 2-channel mode either by using the Elko / Wiser gateway or by holding down button 1 and 4 (upper left and lower right) for approx. 10 seconds - the led will flash red and the become green once successfull.

Edit:

I have finally mixed the DDF with the 4 gangs.
It's not possible to know if it's a 2 gang or a 4 gang, same firmware, same hardware, it's just a setting, so all devices have same endoint and same cluster, even not used.

### CODE REVIEW

**Comment by Smanar** [comment]
Wait, I can perhaps mix 2 DDF.

**Comment by joggs** [comment]
To summarize this in english. The WDE002924 will work, but both 2 gang and 4 gang looks the same in the system, but both work ?

**Comment by jensflorian** [comment]
This probably depends on pairing, see [here](https://www.productinfo.schneider-electric.com/wiser_home/sysm_sysd-connected-wireless-switch-1-gang_2-gang_device-user-guide_wiser-home/English/SysM_SysD%20-%20Connected%20Wireless%20Switch%201-gang_2-gang_Wiser_Home_Device%20user%20guide_0000774577.xml/$/WHM-SysM_SysD-Connectedwirelessswitch1-gang_2-gang-PairingthedeviceTSK_0000735364). I could only test 1-gang (2buttons) and that one works.

**Comment by joggs** [comment]
> This probably depends on pairing, see [here](https://www.productinfo.schneider-electric.com/wiser_home/sysm_sysd-connected-wireless-switch-1-gang_2-gang_device-user-guide_wiser-home/English/SysM_SysD%20-%20Connected%20Wireless%20Switch%201-gang_2-gang_Wiser_Home_Device%20user%20guide_0000774577.xml/$/WHM-SysM_SysD-Connectedwirelessswitch1-gang_2-gang-PairingthedeviceTSK_0000735364). I could only test 1-gang (2buttons) and that one works.

I bought one 2-gang  now and it seems to work well, howerver there is one small visual bug . The 2-gang Schneider switch is visualized in phoscon as 4 square switches and as the 2-gang schneider switch has 2 rectangle where each rectangle is on and off where on is above off. If you mount the switch this way, the mapping in phonscon needs to be rotated 90 degress counter clockwise, like this
schneider

**Comment by joggs** [comment]
Another small visual bug is that you do not see what button you have mapped

**Comment by Smanar** [comment]
Unfortunately we have no impact on phoscon, we can only make change on the API.

**Pull request merged**
