### PR TITLE
Add basic support for Konke sensors (see #1607)

### PR DESCRIPTION
**Pull request by jurriaan**
It does work partially on my system, somehow the `IAS_CIE_ADDRESS` doesn't
get set automatically. After manually setting that, at least my door/window sensor works.

### CODE REVIEW

**Comment by jurriaan** [comment]
Temperature/humidity also shows up, but it does not update automatically.

**Comment by Hypfer** [comment]
So does the merge of this mean that I can simply use my konke motion sensors?

If not, how do I set the `IAS_CIE_ADDRESS` and to what value exactly?

**Comment by jurriaan** [comment]
@manup Thanks for merging! This PR works fine for me, but how are we going to fix this IAS_CIE_ADDRESS issue for adding new devices?

**Comment by jurriaan** [comment]
@Hypfer I've manually set the `IAS_CIE_ADDRESS` to the IEEE address of my Conbee

**Comment by Hypfer** [comment]
@jurriaan but what is `IAS_CIE_ADDRESS ` and where do you set it?

**Comment by Hypfer** [comment]
Nvm. Just as I was aksing, the IAS Zone Cluster appeared.
Still, I'd like to document this for other users.

https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1182

image

image

image

Double-click the value and this should appear:
image

The IEEE Address of the Raspbee/Conbee module is visible in the "Node Info" tab.

**Comment by jurriaan** [comment]
@manup as you can see there are also other sensors where the IAS_CIE_ADDRESS isn't set up automatically (#1182). How can we fix that?

**Comment by nicedevil007** [comment]
> Nvm. Just as I was aksing, the IAS Zone Cluster appeared.
> Still, I'd like to document this for other users.
> 
> #1182
> 
> image
> 
> image
> 
> image
> 
> Double-click the value and this should appear:
> image
> 
> The IEEE Address of the Raspbee/Conbee module is visible in the "Node Info" tab.

Hey Hypfer :) 

nice to see you here as well and not just on Valetudo <3

Can you tell me how to get to this settings you did with the IEEE Adress? I have the conbee stick installed on a raspberry pi inside a docker environment. I guess you are using the deconz software for Windows to get there right?

**Comment by Hypfer** [comment]
@nicedevil007 try keeping the sensor awake by triggering it and/or pressing the button when you try to write the value.

**Pull request merged**
