### PR TITLE
DDf, add support for doorlock EasyAccess EasyFingerTouch

### PR DESCRIPTION
**Pull request by Smanar**
See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5870
- Product name: EasyAccess EasyFingerTouch
- Manufacturer: Onesti Products AS
- Model identifier: EasyFingerTouch

This DDF is for sensor version (ZHADoorlock) it expose :
- config/lock to unlock lock the device
- state/lockstate that can be not fully locked/locked/unlocked/undefined
- state/open that say if the door is open or not

This device don't have poll cluster.

I have added a json item corrected for ZHADoorlock.

### CODE REVIEW

**Comment by cortado** [comment]
Have EasyAccess EasyCOde Touch, is this the same lock? (And how do I get this added to my DeConz plugin for HA? I have latest firmware for Conbee II)

**Comment by cortado** [comment]
to be mote precise: to make a correct DDF to make it be recognized by the system, what is needed/missing?

**Comment by Smanar** [comment]
I can make the DDF, except the cluster 0xFEA2 all seem classic, will take 5mn, but better to start a new issue (an admin can close this one, not repecting rules) , and I need at least a complete capture from the cluster 0x0000 with all attribute.

**Comment by cortado** [comment]
I see now that the system is not loading the DDF you have made. I started making one through the decent GUI, and than more info starts coming into HA - so I think if I just could  load your DDF into Deconz it might work! But hip do I download and how doing I get hot top the right directory? cannot edit text with coipy/påaste in decent, and cannot find the file with Filebrowser (addon). Can I use the SSH addon maybe?

**Comment by cortado** [comment]
Update: things looked even better after some reload of deconz. now it is only state that is a little quirky when it cones to state (does not reflect open-close auto sequence) - but I can open it through HA!
Skjermbilde 2024-01-07 kl  23 28 36
Skjermbilde 2024-01-07 kl  23 28 46

Also: is it possible to add managing of PIN codes and users through controllers in HA, instead of deCONZ interface?

**Comment by Smanar** [comment]
Hu ? You are aware this place is a PR for the device EasyAccess EasyFingerTouch.
And this PR is finished and closed ?

Seriously will be better if you can create a new issue for the new device.

>now it is only state that is a little quirky when it cones to state (does not reflect open-close auto sequence)

After a missing state change, the value is updated when you read it in deconz ? Cluster 0x0101 attribute 0x0000.
I m seing this device have too state/open and state/lockstate (if they are not visible in HA can use Phoscon/help/API Information/sensors)
If yes, it's a bind/report issue else the problem is in the DDF.

For PIN code there is a basic code, but not valided yet https://github.com/dresden-elektronik/deconz-rest-plugin/pull/5918

**Comment by cortado** [comment]
Thank, you! Sorry I am not very familiar with this, and put it the wrong place.

**Comment by Smanar** [comment]
Signal me if you continu your problem on an other issue, I m not checking all of them ^^.

**Pull request merged**
