### PR TITLE
IKEA SOMRIG Shortcut Button support

### PR DESCRIPTION
**Pull request by noud-github**
created the DDF file and added buttons to the buttons_maps.json

see https://github.com/dresden-elektronik/deconz-rest-plugin/issues/7450 for context, 
(just copied most of the code from there ;-))

I changed the buttons mapping to mimic the **one dot**  and **two dots** button from the symfonisk gen2 remote as that alsofeatures a **one dot** and **two dots** buttons

### CODE REVIEW

**Review by SwoopX — COMMENTED** [review]
I guess the suggested additions ensure the device generally works without any issues, yet leaving some room for improvement. I guess the group support is currently missing and could/should be added?

@ebaauw what do you think?

**Comment by ebaauw** [comment]
You might want to do the FC80 bindings first as the switch won’t wake on button press without these.

**Comment by Smanar** [comment]
> You might want to do the FC80 bindings first as the switch won’t wake on button press without these.

You mean before the bind on the cluster 0x0001 ?
The order matter on the DDF ?

**Comment by ebaauw** [comment]
I think deCONZ tries to add the bindings in the order they’re specified.

**Comment by manup** [comment]
Yes the order of bindings and reporting configuration is as given in respective JSON arrays.

**Comment by Smanar** [comment]
Ha good to know, in my mind deconz make the second bind without waiting a positive return for the first one.

@noud-github Can you put the binding for the cluster 0x0001 in last pls ? (after the 2 one for the cluster 0xFC80), on the last part of the DDF.

**Comment by noud-github** [comment]
@Smanar  ^^  Like this?

**Comment by Smanar** [comment]
Yep ^^. If I have understand, it's that.

**Pull request merged**
