### PR TITLE
Create TS0202.json

### PR DESCRIPTION
**Pull request by evanhemmen**
DDF for Tuya powered Human Motion Sensor (TS0202)

### CODE REVIEW

**Comment by evanhemmen** [comment]
Hi,

Will do, but maybe I do some further investigation first. I'm a complete
newby with regard to DDF and the use of Github. I'm realy not sure what I
did and how to use it. I was following the steps in
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6379, but
to be honest, I don't know what to do next.

I'll remove the DDF and will do some research first before potentially
further poluting the system.

Best regards,
Eelco

**Comment by Smanar** [comment]
The PR is still open, you can put again your DDF ^^
Don't worry, you was fine, just choose a better folder, you can retry all time you want, there is no danger for the offical branch.

**Comment by evanhemmen** [comment]
Thanks, but I'll first have to learn how to get a DDF file via a PR into my
Raspberry Pi :-). I'm really a newby at this.

BR

**Comment by Smanar** [comment]
If it's just to add or edit a file can make with your browser
Just go on the file you want to edit, or the path you want to create one and press the "edit the file"

You will have a message saying you have no rigt, it will create a fork, make the change, and help you for the PR

But it s easier now for you, you already have a fork https://github.com/evanhemmen/deconz-rest-plugin

You have all right on this fork, and all edition you will make on it will be visible on this PR

**Comment by manup** [comment]
0 files changed? :)

**Comment by Smanar** [comment]
Lol, @evanhemmen you have removed the file, but not re-add it.
You can use the same fork to do that https://github.com/evanhemmen/deconz-rest-plugin/tree/patch-1

**Comment by manup** [comment]
> Think it's already handled by #6679

Ya looks like it, closing this PR for now.

**Pull request closed without merging**
