### PR TITLE
Fix script paths for DDF files

### PR DESCRIPTION
**Pull request by Zehir**
The validator does not yet validate script path, I found 3 that was invalid

### CODE REVIEW

**Comment by Zehir** [comment]
> I don't think it wise to refer to JavaScript files in directories for other manufacturers. The maintainer of the JavaScript won't realise it's being used by devices from other manufacturers as well. Hopefully this will be solved by bundling DDFs, but for now, I think we better copy the JavaScript files.

There already other DDF referencing script from an other folder.

Even with the bundling the directory structure of the devices directory will be the same. Or we can do an other workflow, any idea ?

Or we can create a shared folder with scripts used by many DDF ?

**Comment by ebaauw** [comment]
Generic JavaScript files are already in the `generic` folder.  Apparently with a subfolder per cluster.

**Comment by Zehir** [comment]
If @manup agreed I can edit this PR to move all scripts in the generic folder and update the paths

**Comment by Smanar** [comment]
Yes exaclty, there is "Moes" but thee is too "nedis", "fantem", "tesla" and more.
Using `<brand>`/ directory is more friendly, but not good for common fies, and to group clone.

For me Tuya is Tuya, can be different brands, but same working mode, same problems, I don't see a difference beetween Moes or Nedis.

But I can understand an user buying a "Telsa" device not searching in the "Tuya" folder.

>if needed a script can be duplicated into another vendor directory to keep a meaningful tree structure.

Yes me too, if one day someone change a script in the "tuya" folder, 99% of chance it will be compatible for all tuya but not sure it will be still compatible for other brands.

**Comment by Zehir** [comment]
What about an import syntax ?
Maybe not a good idea, could be a mess for bundling

**Comment by manup** [comment]
Merging for now to get the path errors fixed.
We can address the logical organization of where to put things later on.

**Pull request merged**
