### PR TITLE
Add DDF for MHCOZY ZG-005-RF

### PR DESCRIPTION
**Pull request by ebaauw**
See #7309.

Initial support is quite straightforward, see resources below.

I want to expose the button mode (values: `toggle`, `state`, `momentary`) and, if we can reverse engineer it, the device mode (values: `self-locking`, `interlock`; `jog`), but I'm a bit lost in the various `config` attributes: `clickmode` vs `devicemode` vs `mode`.  Neither are currently supported for `lights` attributes, and I don't think the API checks for valid values when PUTting these for `/sensors` resources.  I think we'd need corresponding `capabilities` attributes to list the possible values.

Also these modes are for all endpoints.  In `/devices` I would expose these on the main device.  Not sure whether to expose these on all `/lights` resources, or only on the first.

I'm not sure if we already have a standard how we name DDFs for devices using the Tuya convention.  I've seen, what I assume is the same device on Amazon an AliExpress, which different (commercial) manufacturer name and model identifier.  I don't know if these use the same _Manufacturer Name_ and _Model Identifier_ values.

```
{
  "config": {
    "groups": [
      "0"
    ],
    "on": {
      "startup": false
    }
  },
  "etag": "501be1375a3277518ddf91ec052b1d90",
  "hascolor": false,
  "lastannounced": null,
  "lastseen": "2023-10-20T11:10Z",
  "manufacturername": "MHCOZY",
  "modelid": "ZG-005-RF",
  "name": "Relay 1",
  "state": {
    "on": false,
    "reachable": true
  },
  "swversion": "1.1.0",
  "type": "On/Off output",
  "uniqueid": "a4:c1:38:22:67:96:ec:15-01"
}
```
```
{
  "config": {
    "groups": [
      "0"
    ],
    "on": {
      "startup": false
    }
  },
  "etag": "501be1375a3277518ddf91ec052b1d90",
  "hascolor": false,
  "lastannounced": null,
  "lastseen": "2023-10-20T11:10Z",
  "manufacturername": "MHCOZY",
  "modelid": "ZG-005-RF",
  "name": "Relay 2",
  "state": {
    "on": false,
    "reachable": true
  },
  "swversion": "1.1.0",
  "type": "On/Off output",
  "uniqueid": "a4:c1:38:22:67:96:ec:15-02"
}
```
```
{
  "config": {
    "groups": [
      "0"
    ],
    "on": {
      "startup": false
    }
  },
  "etag": "501be1375a3277518ddf91ec052b1d90",
  "hascolor": false,
  "lastannounced": null,
  "lastseen": "2023-10-20T11:10Z",
  "manufacturername": "MHCOZY",
  "modelid": "ZG-005-RF",
  "name": "Relay 3",
  "state": {
    "on": false,
    "reachable": true
  },
  "swversion": "1.1.0",
  "type": "On/Off output",
  "uniqueid": "a4:c1:38:22:67:96:ec:15-03"
}
```
```
{
  "config": {
    "groups": [
      "0"
    ],
    "on": {
      "startup": "previous"
    }
  },
  "etag": "6d4d6840823cf39cb6627098ae94bcfe",
  "hascolor": false,
  "lastannounced": null,
  "lastseen": "2023-10-20T11:10Z",
  "manufacturername": "MHCOZY",
  "modelid": "ZG-005-RF",
  "name": "Relay 4",
  "state": {
    "on": false,
    "reachable": true
  },
  "swversion": "1.1.0",
  "type": "On/Off output",
  "uniqueid": "a4:c1:38:22:67:96:ec:15-04"
}
```

### CODE REVIEW

**Comment by Smanar** [comment]
For me not a good idea to change model id and manufacture name. Was a problem for lidl with user not able to reconize their device.

**Comment by ebaauw** [comment]
Now basing `manufacturername` and `modelid` on _Manufacturer Name_ and _Model Identifier_.  The real (non-Tuya) model id is exposed as `productid`.  See below:
```
{
  "config": {
    "groups": [],
    "on": {
      "startup": "previous"
    }
  },
  "etag": "f3cd380fbc54272565d1e70ab84f8bf8",
  "hascolor": false,
  "lastannounced": null,
  "lastseen": "2023-12-15T10:29Z",
  "manufacturername": "_TZ3000_u3oupgdy",
  "modelid": "TS0004",
  "name": "On/Off output 8",
  "productid": "ZG-005-RF",
  "state": {
    "on": false,
    "reachable": true
  },
  "swversion": "1.1.0",
  "type": "On/Off output",
  "uniqueid": "a4:c1:38:22:67:96:ec:15-01"
}
```

**Comment by Smanar** [comment]
Nice, on my side I prefer ^^, this solution is perfect for me.

**Comment by FhemiR** [comment]
I have tested it, I'm not sure if it is related to deconz-rest or is it a HW issue, but the device is time to time not reachable, it keeps the last state however. It comes back online again after a while however.

**Pull request merged**
