### PR TITLE
Hue dimmer switch (2021), Livarno Lux lights

### PR DESCRIPTION
**Pull request by ebaauw**
- Add support for Hue dimmer switch (2021 model, RWL022), see #4287;
- Add _Manufacturer Name_/_Model Identifier_ translations for LIDL Livarno Lux light bar (Lichtleiste) and mood light (Stimmingsleuchte), see #4248;
- Add _Manufacturer Name_/_Model Identifier_ translations for LIDL Xmas lightstrip.

### CODE REVIEW

**Comment by Thomas-Vos** [comment]
Thanks again Erik for delaying the model id for the LIDL Xmas lightstrip! I added the LIDL model IDs in Hue Essentials a few months ago, so it is alright to add this one now.

**Comment by ebaauw** [comment]
@manup, I double-checked that both new model and the old model pair OK and work with this PR.  I think it's good to go.

**Comment by ebaauw** [comment]
OK, this was self-inflicted.  Now both old and new models pair OK, getting only one resource.

**Comment by manup** [comment]
> OK, this was self-inflicted. Now both old and new models pair OK, getting only one resource.

Happens, I didn't know the new model was already available.
Will be part of v2.9.2. :)

**Comment by ebaauw** [comment]
Still an issue: when restored from database, endpoint 2 is used (as for the original model), causing the `uniqueid` to change to `-02-fc00` and button events not to be registered.

**Pull request merged**
