### PR TITLE
Add support for Illumra Dual Rocker Switch which uses the FOH PTM215ZE module

### PR DESCRIPTION
**Pull request by mdolnik**
This is a pull request for issue [#2108](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2108)

I am new to C++ so feel free to make any code suggestions.

### CODE REVIEW

**Comment by manup** [comment]
I'd like to merge this for the 15th October beta. Did you have a chance to test this with the other ZGP switch types?

**Comment by mdolnik** [comment]
> I'd like to merge this for the 15th October beta.

Great, thanks for the quick response!

> Did you have a chance to test this with the other ZGP switch types?

Unfortunately this Illumra switch is the only green-power switch I have, so I am unable to test with any others, but just by judging the code it _should_ avoid changing anything for other models (provided the `Philips` model below the Illumra declaration doesn't share the `ind.payload().size() == 27`)

Also I don't understand the impacts of setting the SW version to a string ID instead of a number, I just used that as a means of differentiating this model in the button mapping section.

I'm open for any code suggestions that I can try out on my end.

**Comment by manup** [comment]
That's fine I think we have all these switches in the company, will schedule some tests.
As far as I'm aware the swversion is only displayed but not uses otherwise, so it should be save.

**Comment by mdolnik** [comment]
Also a minor thing is I set the manufacturer to `PhilipsFoH` when it seems it is actually [EnOcean](https://www.enocean.com/en/products/enocean_modules_24ghz/ptm-215ze/).

I believe I may have either copy/pasted another switch declaration and forgot to change the manufacturer or I may have though Phillips was the manufacturer [from here since it uses the same module](http://www.docs.lighting.philips.com/en_gb/oem/download/xitanium/SCP_PHIL_164296_PMT215ZE_A03.pdf)

**Comment by manup** [comment]
The PhilipsFoH was used to reflect the original Hue REST-API (under the hood all ZGP switches use a EnOcean module).

**Comment by manup** [comment]
I've added a check for the sourceID to prevent confusion with Hue Tap, however I couldn't test this.
Can you please provide the sourceID prefix your switch is using?

**Comment by mdolnik** [comment]
> I've added a check for the sourceID to prevent confusion with Hue Tap, however I couldn't test this.
> Can you please provide the sourceID prefix your switch is using?

I don't know where to find the sourceID, I can't find anything in the deCONZ GUI that mentions anything about a source ID...

Judging by your commit ef15ee1 you are comparing using `ind.gpdSrcId()`. I can't say I know much about working with hexadecimals, but I debugged using:
```
QVariantMap map;
map["ind.gpdSrcId()"] = ind.gpdSrcId();
map["(ind.gpdSrcId() & 0x01700000)"] = (ind.gpdSrcId() & 0x01700000);
map["(ind.gpdSrcId() & 0x01700000) == 0x01700000"] = (ind.gpdSrcId() & 0x01700000) == 0x01700000;
map["0x + QString::number(ind.gpdSrcId(),16).toUpper()"] = "0x" + QString::number(ind.gpdSrcId(),16).toUpper();
DBG_Printf(DBG_INFO, "\n\n\n%s\n\n\n", qPrintable(Json::serialize(map)));
```

And got the following results:
```
{
  "(ind.gpdSrcId() & 0x01700000)":22020096,
  "(ind.gpdSrcId() & 0x01700000) == 0x01700000":false,
  "0x + QString::number(ind.gpdSrcId(),16).toUpper()":"0x15058D2",
  "ind.gpdSrcId()":22042834
}
```

So it seems it is a different ID than the commit is expecting...

Are these debugging values helpful? Or should I try something else?

**Comment by manup** [comment]
Thanks that helps, they seem to use a different vendor prefix than the other Friends of Hue switches.
I think in future we need a more complete approach to detect various switches, perhaps by first testing all buttons in a multi stage process.

**Comment by mdolnik** [comment]
I can confirm the latest master commit 45a769 works now with the Illumra switch.

Works for both commissioning as type "Other" and is able to control lights with no issues 

Thanks for your help.

**Comment by ICTSMART** [comment]
Started testing today with the PTM 215Z (EnOcean) as discussed on https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2780. Unfortunately the switch commands are not passed through the mesh.
When near to the Raspbee, I see the events coming in - when sufficient away with at least 2 nodes in between, messages are lost. Please let me know how I can help here.

**Pull request merged**
