### PR TITLE
Add DDF: Tuya Multi Sensor Temp./Humidity (_TZE200_znbl8dj5, _TZE200_qoy0ekbd)

### PR DESCRIPTION
**Pull request by Finne75**
This device ([link](https://www.aliexpress.com/item/1005004116638127.html)) and another clone. See discussion here (#6535)

### CODE REVIEW

**Comment by Smanar** [comment]
@Finne75 You don't have battery drain issue with this DDF ?

If you have try to add 

`"refresh.interval": 86400,` for all lines that are not natives like "attr/swversion"," name": "state/humidity", "name": "config/battery", "name": "state/temperature",

**Comment by Smanar** [comment]
@Finne75 can you add another clone to your list ?

```
  "manufacturername": ["_TZE200_znbl8dj5", "_TZE200_qoy0ekbd", "_TZE200_a8sdabtg"],
  "modelid": ["TS0601", "TS0601", "TS0601"],
```

**Comment by b2un0** [comment]
got another one: `_TZE200_whkgqxse`

https://aliexpress.com/item/1005004699157635.html

**Comment by Smanar** [comment]
You have tested the DDF with your device @b2un0 ?

**Comment by b2un0** [comment]
Yep, works as expected after adding this DDF modified with the mentioned id.

**Comment by Smanar** [comment]
@Finne75 I have edited your fork (I didn't know it was possible) To add thoses clone.

**Comment by Finne75** [comment]
Exzellent, thanks, I am a bit busy with the real work therefore a bit slow

**Pull request merged**
