### PR TITLE
Legrand Teleruptor and Xiaomi switch

### PR DESCRIPTION
**Pull request by Smanar**
2 lines devices. Realy nothing special in code but realy nice device > https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3040

### CODE REVIEW

**Comment by Smanar** [comment]
Adding Contactor https://www.legrand.fr/pro/catalogue/44172-contacteur-connecte-drivia-with-netatmo

**Comment by Smanar** [comment]
Adding support for xiaomi WXKG07LM (double) and simple version 2020 https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3066

**Comment by bsheepdiy** [comment]
Hello,

I've tried the LEGRAND contactor (REF 412171) all is working.
I've to mannually bind the following cluster :
0x000f, 0x0b04, 0x0003 and 0xfc41

The contactor has 2 configuration modes : 
Managed by "HC/HP from main power" or manually : 
You have to change attribute (0x000) on Legrand specific cluster 0xfc01 to these values : 
- Tarification HC/HP 0x0000 0x0004 
- ON/OFF 0x0000 0x0003 

Maybe you could change the general.xml according to these values : 
lgcluster

thanks for your job Smanar

**Comment by Smanar** [comment]
Howww, realy usefull information, thx.
BTW I realy need to check if it s possible making description chnage according to device.

I think with this PR the binding will be automatic, but I have done the contactor integration using informations found on the net, if you can confim me the model is is "Contactor" ?

**Comment by bsheepdiy** [comment]
Yes "Contactor" is model identifier :
Capture d’écran de 2020-07-25 09-31-50

**Comment by Smanar** [comment]
Adding a Konke sensor.

**Pull request merged**
