### PR TITLE
Add ubisys Device Setup Cluster

### PR DESCRIPTION
**Pull request by ma-ca**
Configures ubisys manufacturer specific Device_Setup Cluster `0xFC00` on Endpoint 232 (0xE8).
 
  Implements support for:
  - ubisys S1 power switch
  - ubisys S2 power switch
  - ubisys J1 shutter control

It can be used to control the behavior of inputs (i.e. permanent switches, push-button switches, normally open vs. normally closed, on/off, level control or scene selection, etc.)

Example usage:

    -X PUT -d '{ "mode": "momentary" }' /sensor/xx/config
    -X PUT -d '{ "mode": "rocker" }' /sensor/xx/config
 
In addition to predefined configurations for momentary switches and rocker switches, this implementation allows custom configurations for a more complex move or recall scene command.

Example usage:

    -X PUT -d '{ "mode": "custom_41020006000D0306000206010D04060002" }' /sensor/xx/config
    
Writes ZCL raw data `"41020006000D0306000206010D04060002"` to attribute `0x0001` on cluster `0xFC00`

### CODE REVIEW

**Comment by ma-ca** [comment]
Fixed missing light attribute `sat` on WindowCoveringType Tilt, issue #925. The missing `sat` is now being added during calibration for windowcoveringtype 6, 7 and 8.

Example

    sensors/xx/config -X PUT -d '{"windowcoveringtype" : 8}'

**Comment by theFork** [comment]
I'm trying to configure an S1 switch. Unfortunately, only the light is detected, there is no sensor with config/mode. Is this worth a new issue?

**Comment by Markkuuss** [comment]
> I'm trying to configure an S1 switch. Unfortunately, only the light is detected, there is no sensor with config/mode. Is this worth a new issue?

I don't think it's a new issue. I use the latest deconz version and the S1 sensors appear. Do you also use the 2.05.54? With the S1 I have also installed the latest firmware: [Firmware Version 1.13, ubisys ZigBee Stack 1.97](http://www.ubisys.de/smarthome/download-firmware.html)

In the OTAU cluster you can check if your S1 has the latest firmware: 0x010D0161
image

**Comment by theFork** [comment]
I've just upgraded to deconz 2.05.54 and re-paired one of my S1. Regarding the device FW the rest api says

```
swversion: 20161129-DE-FB0
```

whereas the deCONZ gui returns the following:

```
Current File Version: 0x010d0161
Current ZigBee Stack Version: 0x0002
```

Thus, I should also have the latest firmware. All my S2 devices gets recognized as switches whereas my S1 devices don't.

Anyway, thanks, I'm grateful for any kind of advice.

**Comment by ebaauw** [comment]
The S1 hasn't been whitelisted for the `/sensors` resources (see also https://github.com/ebaauw/homebridge-hue/issues/427).  I can add support in the REST API plugin (and in homebridge-hue), If you could please post the screenshots described in: https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Request-Device-Support.

**Comment by Markkuuss** [comment]
Here are the corresponding screenshots of my ubisys S1-R:
image
image

**Comment by manup** [comment]
>Thanks. Do you also have the non-R variant? This one has two control inputs for pulse switches (endpoints 02 and 03), the non-R S1 only has one.

I have these in the company can provide some screenshots during the week.

>I don’t think the deCONZ REST API plugin already deals with the Smart Energy profile. @manup any caveats adding that? We would definitely need to change general.xml and add the Electrical Measurement cluster to the Smart Energy profile.

Yes, I think the general.xml only misses a reference to this cluster, since simple metering is already shown.

>I don’t think the deCONZ REST API plugin already deals with the Smart Energy profile. @manup any caveats adding that?

For the respective clusters it should be enough to also handle Smart Energy profile id in the respective if branches.

**Comment by Markkuuss** [comment]
> Has that always been the case, or did that change with a recent firmware upgrade?
No, I don't think so. I think that has changed with the last update.

> Or does this device have very old firmware?
I'm using the latest firmware ubisys offers for the S1-R on their homepage.

> What do your other switches look like (with the 2016 `swversion`)?
In the deconz rest api under 'swversion' is '20140606-DE-FB0' for the S1-R lights and '1.0' for the two sensors.

**Comment by ebaauw** [comment]
RTFM, endpoint 0x04 has 0x0104: Common Profile (HA) with a small footnote:
> Since application version 1.01 (S1-R). Prior, profile ID 0x0109 (Smart Energy) was used.

This would suggest the switch is running **old** firmware.  However, according to the same manual, the 0x02 and 0x03 endpoints are only _Level control switch_ devices since version 1.04.

**Comment by Rolf56** [comment]
I have installed a new Ubisys Shutter control J1 and find it in Rest-API as light 12 and as sensors 19 and 20 (see below)
I use deCONZ Version 2.05.58 on a Windows 10 computer
the deCONZ gui returns the following:
 
image
image
 
In the Cluster Info tab "Window Covering Cluster" I can the drive up, down and also stop. But when I'm using values in the "Go to.." field nothing happens. 

Also there are no changes in the /lights/12  state attributes of the Rest-API. They never change!
- light
 
image

- sensor
The state attributes in the sensors are updated by the system

image

Do you have any ideas?

**Comment by ma-ca** [comment]
> I can the drive up, down and also stop. But when I'm using values in the "Go to.." field nothing happens.

You need to calibrate the J1.

    /sensors/xx/config -X PUT -d '{"windowcoveringtype" : 0}'

where `windowcoveringtype` is the device type from 0 to 9.

  Value |	WindowCoveringType  |    Capabilities
------- | ----------------------- | ------------
  0  |  Roller Shade                | Lift only
  1  |  Roller Shade two motors     | Lift only
  2  |  Roller Shade exterior       | Lift only
  3  |  Roller Shade two motors ext | Lift only
  4  |  Drapery                     | Lift only
  5  |  Awning                      | Lift only
  6  |  Shutter                     | Tilt only
  7  |  Tilt Blind Lift only        | Tilt only
  8  |  Tilt Blind lift & tilt      | Lift & Tilt
  9  |  Projector Screen            | Lift only

http://www.ubisys.de/downloads/ubisys-j1-technical-reference.pdf
 * page 18, chapter 7.2.5.1. Calibration

**Comment by SwoopX** [comment]
Let me jump in here as well since I don't seem to fully understand how calibration and configuration for calibration works here.

I got my J1 2 days ago and I read the technical reference before integrating it into my environment. Having thought I can set the required configuration settings via deconz GUI, I checked the home automation windows covering device cluster, but the parameters were, almost all, read only. So presumably not the route to take...

So I searched a bit around and stumbled about this conversation. Basically, Rolf56 indirectly asked my slightly different question on how to change the parameters for configuration. Ma-ca's answer pretty much gave the first piece of the puzzle by issuing the curl PUT request to set the coveringtype (ZHASwith sensor). I did that and heard that my roller started doing stuff, ending in a fully lifted position. Now, how to move on (more curl-ing for lights/sensors)?

Some detailed guidance would be highly appreciated to understand and learn here. Got another S2 liying around here waiting to be put into action and if the hardware convinces, a lot more will follow.

Lastly, another question regarding the STOP command for "bri_inc". Where is this one hidden? I cannot find the parameter it in any of the GET responses and neither in the list of my FHEM parameters. Maybe it shows only after successful calibration?

Many thanks in advance!

**Comment by ma-ca** [comment]
> issuing the curl PUT request to set the coveringtype (ZHASwith sensor). I did that and heard that my roller started doing stuff, ending in a fully lifted position. 

That is everything needed for calibration. The REST-API does send commands to move up and down until the J1 calibration is complete. You should now be able to send "Go To ..." commands.  

For example to move to 50% open.

    /lights/xx/state -X PUT -d '{ "bri": 127}'

> another question regarding the STOP command for "bri_inc". Where is this one hidden?

This is the stop command.

    /lights/xx/state -X PUT -d '{ "bri_inc": 0}'

**Comment by Rolf56** [comment]
Thank you ma-ca for your explanations. But I still have troubles to calibrate the J1.
After a factory reset I found another sensor, what I think that's the right one to configurate. Therefor I use `18` instead of `xx` as shown in your example  `/sensors/xx/config`

image

I could set "windowcoveringtype" successfully by using Postman

image

If I try to set “InstalledOpenLimitLift" or any other parameter, I get [{"error":{"address":"/sensors/config","description":"body contains invalid JSON","type":2}}]

image

Can you please tell me whats wrong in the syntax.

**Comment by ebaauw** [comment]
Looks like your editor beautified the opening double-quotes.

`InstalledOpenLimitLift` is the name of a Zigbee attribute.  It's not exposed thru the REST API, so you cannot set it through the API.

@manup, there's something odd with the ZHASwitch sensor resource: the cluster is missing from `uniqueid`.  The check for `sensor.fingerPrint().hasOutCluster(WINDOW_COVERING_CLUSTER_ID)` seems to be missing here:
https://github.com/dresden-elektronik/deconz-rest-plugin/blob/df387711926f109823c88139b5840a7143969697/de_web_plugin.cpp#L4002
and here:
https://github.com/dresden-elektronik/deconz-rest-plugin/blob/df387711926f109823c88139b5840a7143969697/database.cpp#L2806
I'm a bit reluctant to create a PR, as I have no experience with the J1.  As far as I can tell, the ZHASwitch resource is created for the sole purpose of exposing `config.windowcoveringtype`?  It's `state` seems to be non-functional.

**Comment by SwoopX** [comment]
Ok, it's working now for me. @ma-ca Many thanks for your input!

Quick summary on what I did:
Although calibration has been executed yesterday (before posing here), percentage lift through "bri" did not work. This has to be execute in **lights ZHASwitch**. However, the stop command through "bri_in" worked, as ma-ca explained, again in **lights ZHASwitch**. So I decided to re-calibrate, following the hint from the technical reference (which is: fully open and then move down a few centimeters). Then, I've set the "windowcoveringtype" to "0" again in **sensors ZHASwitch**. So calibration started as described in the technical reference (going up and down...) and that was it. Afterwards, I was finally able to move to e.g. 40% via "bri" in **lights ZHASwitch**me being happy :)

@Rolf56: no need to play around with anything as “InstalledOpenLimitLift"

So from my end, all's good. Next one up to see how to have FHEM send the "bri_inc" parameter ;)

**Comment by ma-ca** [comment]
> As far as I can tell, the ZHASwitch resource is created for the sole purpose of exposing `config.windowcoveringtype`? 

@ebaauw It also exposes `config.mode` that configures the ubisys _Device Setup_ Cluster for momentary and rocker switches. That is available for the ubisys D1, J1, S1, S2 devices.

> It's state seems to be non-functional.

That ist true, but not just for J1. Also for ubisys S2.

```
{
    "config": {
        "group": null,
        "mode": "rocker",
        "on": true,
        "reachable": true
    },
    "ep": 3,
    "etag": "4e13814fcfcaf485aebf3dc9d58c3749",
    "manufacturername": "ubisys",
    "mode": 1,
    "modelid": "S2 (5502)",
    "name": "S2 (5502) 60",
    "state": {
        "buttonevent": null,
        "lastupdated": "none"
    },
    "swversion": "20160310-DE-FB0",
    "type": "ZHASwitch",
    "uniqueid": "00:1f:ee:00:00:00:10:2e-03-0006"
}
```

```
{
    "config": {
        "group": null,
        "mode": "momentary",
        "on": true,
        "reachable": true,
        "windowcoveringtype": 0
    },
    "ep": 2,
    "etag": "9b0a3f5dd3ef37c6a2abfa67bc509240",
    "manufacturername": "ubisys",
    "mode": 1,
    "modelid": "J1 (5502)",
    "name": "Switch 69",
    "state": {
        "buttonevent": null,
        "lastupdated": "none"
    },
    "type": "ZHASwitch",
    "uniqueid": "00:1f:ee:00:00:00:2d:0e-02"
}
```

**Comment by ebaauw** [comment]
> Also for ubisys S2.

For the S2, the ZHASwitch resource should reflect the buttonevents on the connected switches.   Maybe rocker mode has broken this?  The buttonmap seems to be for momentary switches.

**Comment by ma-ca** [comment]
Both modes, momentary and rocker, send toggle commands whenever the buttons are pressed. 

I believe that the ubisys S2 is missing the required bindings from the OnOff client clusters on endpoints 3 and 4 to the gateway.

**Comment by ma-ca** [comment]
I have manually created the binding on the ubisys S2 and now I receive buttonevents when pressing the connected wall switch.

```
{
    "config": {
        "group": null,
        "mode": "rocker",
        "on": true,
        "reachable": true
    },
    "ep": 3,
    "etag": "79c242d136af90683ff8545640c4e188",
    "manufacturername": "ubisys",
    "mode": 1,
    "modelid": "S2 (5502)",
    "name": "S2 (5502) 57",
    "state": {
        "buttonevent": 1002,
        "lastupdated": "2019-02-14T16:40:48"
    },
    "swversion": "20160310-DE-FB0",
    "type": "ZHASwitch",
    "uniqueid": "00:1f:ee:00:00:00:10:33-03-0006"
}
```

**Comment by ebaauw** [comment]
Typically, _OnOff_ clusters on switch endpoints are bound to a group, not to the gateway.  The REST API plugin eavesdrops on the (broadcast) group commands.  Once the binding is there, `config.group` should be populated on the next button event.  The two buttons (input) can be bound to different groups.  You can then add smart lights to these groups, to control them, even when the gateway is down.

In factory state, the _OnOff_ clusters are bound to the light endpoints of the S2 itself, so the buttons control the devices wired to the S2 outputs.

**Comment by Rolf56** [comment]
Ok, it's working now for me too. Many thanks for your input!

@SwoopX Do you already have a solution to have FHEM send the "bri_inc" parameter?
Thanks in advance

**Comment by SwoopX** [comment]
@Rolf56: Found it just a minute ago after having checked the source code of module 31_HUEDevice. Use command "set wz.rollo dimDown 0" to stop and don't forget to replace your device name ;)

Another fun fact: Since my shutter motor has been installed subsequently, I have this wonderfully looking cable hanging out of my windows frame in the living room, currently attached to my smart plug and turned off while not being used for a while. Having calibrated the J1 and after switching on the plug again, the calibration values seem to have gone. However, once the shutter moves in any way, the J1 somehow "recalls" the values and from then on, I can use lift percentage again. Smells a bit fishy...
Does the J1 persistently store the values? Could that be due to a slight suboptimal twist in the code?

@ma-ca: Maybe any thoughts on this one?

**Comment by ma-ca** [comment]
> Having calibrated the J1 and after switching on the plug again, the calibration values seem to have gone. However, once the shutter moves in any way, the J1 somehow "recalls" the values and from then on, I can use lift percentage again.

This is working as designed and is described in the ubisys J1 technical reference manual on page 20 in the calibration chapter.

_After a power-cycle you need to let the blind reach the upper position to regain position awareness, i.e. move down a little, and then move up._

**Comment by SwoopX** [comment]
Damn, could have seen that myself. Thanks for mentioning!

**Comment by jensflorian** [comment]
Currently the Deconz 2.0.74 REST API reports all Ubisys S1 and S2 switch modes as "momentary" in my network although all S1 are configured by Ubisys as rocker by default and work as expected in phoscon.

After issuing the PUT command, their state is now correctly displayed 
> [
  {
    "success": {
      "/sensors/50/config/mode": "rocker",
      "successfully updated S1 (5501)": "rocker"
    }
  }
]

Is this the expected behavior of the API?

**Comment by Rolf56** [comment]
Hi, I have installed a 2nd Ubisys J1 module to control another jalousie motor now. Here I have the problem that after calibrating the motor moves 1mm only. Ubisys support mentioned to change the values of attributes "StartupSteps" and "InactivePowerThreshold":

image

Therefore I added these two attributes to general.xml in the _cluster id="0102" name="Window Covering"_:
_attribute id="0x1006" name="InactivePowerThreshold" type="u16" default="0x1000" access="rw" required="o"
attribute id="0x1007" name="StartupSteps" type="u16" default="0x0020" access="rw" required="o"_

Now I can see them in the Cluster Info Panel, but the are grayed out and can't be changed.
Can you please explane me what I have to do, that these values can be changed and sent to the device.

Would be great if you would integrate these two value in one of your next versions as well.

Thanks in Advance for your help

**Comment by SwoopX** [comment]
I assume those are manufacturer specific attributes, so the mfcode must be added as well. I can check and test it later.

**Comment by ma-ca** [comment]
> Ubisys support mentioned to change the values of attributes "StartupSteps" and "InactivePowerThreshold":
> Can you please explane me what I have to do, that these values can be changed and sent to the device.

You can use the REST API to set those ubisys J1 manufacturer specific values. There is PR #926 from @felixstorm that allows to set all ubisys J1 attributes on the _Windows Covering_ cluster.

**Comment by Rolf56** [comment]
Thank you for the info. I was trying the REST API to set those ubisys J1 manufacturer specific values but I can't get the info for.

_C:\Users\FHEM>curl  192.168.0.29:80/api/ABCDEF/sensors/38
{"config":{"mode":"momentary","on":true,"reachable":true,"windowcoveringtype":8},"ep":2,"etag":"3dac89bdd3851558579b9611c1e357e1","lastseen":"2020-08-06T12:24:47.681","manufacturername":"ubisys","mode":1,"modelid":"J1 (5502)","name":"J1 (5502) 38","state":{"buttonevent":null,"lastupdated":"none"},"swversion":"20190430-DE-FB0","type":"ZHASwitch","uniqueid":"00:1f:ee:00:00:00:3e:4e-02-0102"}_

In PR #926 I see some C files and don't know what to do with. I suppose this code isn't integrated in my system yet. Do you have an explanation on how to use it?

**Comment by ma-ca** [comment]
Note that the REST API takes decimal values and not hex values. You need `curl -X PUT`.

```
curl -X PUT 192.168.0.29:80/api/ABCDEF/sensors/38/config -d '{ "inactivepowerthreshold" : 4096 }'

curl -X PUT 192.168.0.29:80/api/ABCDEF/sensors/38/config -d '{ "startupsteps" : 32 }'
```

**Comment by Rolf56** [comment]
_C:\Users\FHEM>curl -X PUT 192.168.0.29:80/api/ABCDEF/sensors/38/config -d '{ "StartupSteps" : 20 }'_

gives following error:

_[{"error":{"address":"/sensors/config","description":"body contains invalid JSON","type":2}}]curl: (6) Could not resolve host: StartupSteps
curl: (3) Bad URL, colon is first character
curl: (6) Could not resolve host: 20
curl: (3) [globbing] unmatched close brace/bracket in column 1_

**Comment by ma-ca** [comment]
> "parameter, StartupSteps, not available",

The parameters are case sensitive and need to be lower case, i.e. `"startupsteps"`.

**Comment by Rolf56** [comment]
I allready tryed this before, gives allways the same result:
_C:\Users\FHEM>curl -X PUT 192.168.0.29:80/api/2D48D38F75/sensors/38/config -d @C:\curl\json.txt
[{"error":{"address":"/sensors/38/config/startupsteps","description":"parameter, startupsteps, not available","type":6}}]
C:\Users\FHEM>curl -X PUT 192.168.0.29:80/api/2D48D38F75/sensors/38/config -d @C:\curl\json.txt
[{"error":{"address":"/sensors/38/config/inactivepowerthreshold","description":"parameter, inactivepowerthreshold, not available","type":6}}]_

Is there a way to get the available attributes made visable?
How can I check if PR #926 is implemented?
Has anyone checked the functionality?

**Comment by Mimiix** [comment]
@Rolf56 If it is merged, it is implemented :)

**Comment by ma-ca** [comment]
Looking into the code, it seems that you need to prepend the J1 attibutes with `ubisys_j1_`.

https://github.com/dresden-elektronik/deconz-rest-plugin/blob/dd58a42044cb68bbe057f4bf7cfe2d6e07150a1e/rest_sensors.cpp#L894

```
curl -X PUT 192.168.0.29:80/api/ABCDEF/sensors/38/config -d '{ "ubisys_j1_inactivepowerthreshold" : 4096 }'

curl -X PUT 192.168.0.29:80/api/ABCDEF/sensors/38/config -d '{ "ubisys_j1_startupsteps" : 32 }'
```

**Comment by Rolf56** [comment]
Thats it! :-)
_C:\Users\FHEM>curl -X PUT 192.168.0.29:80/api/ABCDEF/sensors/38/config -d @C:\curl\json.txt
[{"success":{"set attribute config/ubisys_j1_inactivepowerthreshold":65535}}]
C:\Users\FHEM>curl -X PUT 192.168.0.29:80/api/ABCDEF/sensors/38/config -d @C:\curl\json.txt
[{"success":{"set attribute config/ubisys_j1_startupsteps":20}}]_

Thank you for support!

**Comment by CDRX2** [comment]
Hi,
I was wondering if this is still active in the more current versions of deconz. I'm running 2.19.1 beta and get an error message when attempting to set the attributes on an S1 (latest firmware 2.0.0).
The command I used:
`curl -X PUT 10.81.19.50:8090/api/ABCDEF/sensors/xx/config -d  '{"mode" : "momentary"}`
This is the response I get:
`
[
  {
    "error": {
      "address": "/sensors/111/config/mode",
      "description": "Could not set attribute",
      "type": 608
    }
  }
]`
Wondering if there may have been updates to this, before I attempt tackling the methods described in #360 (never used the C++ plugin before)

**Comment by steinbachd** [comment]
This could be linked to the issue reported here #6649 which seems to be just fixed by #6652, so not related to Ubisys.

**Comment by CDRX2** [comment]
Thanks for the info, I'll be waiting for the PR to be merged then.

**Comment by SwoopX** [comment]
> Hi, I was wondering if this is still active in the more current versions of deconz. I'm running 2.19.1 beta and get an error message when attempting to set the attributes on an S1 (latest firmware 2.0.0). The command I used: `curl -X PUT 10.81.19.50:8090/api/ABCDEF/sensors/xx/config -d '{"mode" : "momentary"}` This is the response I get: ` [ { "error": { "address": "/sensors/111/config/mode", "description": "Could not set attribute", "type": 608 } } ]` Wondering if there may have been updates to this, before I attempt tackling the methods described in #360 (never used the C++ plugin before)

Your API call is wrong. `mode` is a top level attribute, so it must **NOT** go to `/config`.

**Comment by CDRX2** [comment]
Well, that is only partially true for the Ubisys devices, see here: [https://dresden-elektronik.github.io/deconz-rest-doc/endpoints/sensors/#supported-config-attributes_1](url). The `mode` I am targetting is indeed to be found in `/config`.

**Comment by SwoopX** [comment]
Hm, another specialty not too common, indeed. And it also looks like a (different) regression. Will have a look what it takes here.

**Comment by CDRX2** [comment]
I tried it several times on different S1 and S2 devices. Same error message every time, even after updating to the latest beta (2.20).

**Comment by strandman** [comment]
Hi, I'm having the same problem updating `config/mode` on my Ubisys S2
`[ { "error": { "address": "/sensors/111/config/mode", "description": "Could not set attribute", "type": 608 } } ]`
I have recently updated the firmware to "ubisys S2 Firmware Version 2.0.0, ubisys Zigbee Stack 3.0.0" if that has something to do with it?

**Pull request merged**
