### PR TITLE
Add initial support for Keypad (XHK1-UE) and ZHAAncillaryControl sensor

### PR DESCRIPTION
**Pull request by Smanar**
The device is a keypad used for alarm https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4560
It create 3 sensors entries
- a ZHAAncillaryControl
- a ZHAPresence
- a ZHATemperature

```
{
  "config": {
    "armed": "arming_away",
    "battery": 100,
    "enrolled": 1,
    "on": true,
    "panel": "arming_away",
    "pending": [],
    "reachable": true
  },
  "ep": 1,
  "etag": "70b9ec51a9c10093b5e87fdcc2f7dfb3",
  "lastseen": "2021-04-11T13:10Z",
  "manufacturername": "Universal Electronics Inc",
  "modelid": "URC4450BC0-X-R",
  "name": "AncillaryControl 28",
  "state": {
    "action": null,
    "lastupdated": "2021-04-11T12:39:47.339",
    "lowbattery": false,
    "tampered": false
  },
  "type": "ZHAAncillaryControl",
  "uniqueid": "00:0d:6f:00:13:4f:61:39-01-0501"
}
```

- config/armed : armed mode, can be "disarmed", "armed_stay", "armed_night", "armed_away", "invalid_code", "not_ready", "already_disarmed"
- config panel : panel mode, can be "disarmed","armed_stay","armed_night","armed_away","exit_delay","entry_delay","not_ready_to_arm","in_alarm","arming_stay","arming_night","arming_away

### CODE REVIEW

**Comment by Smanar** [comment]
The device is not easy to use, so if the others want to put comment too ....

To use this device specially you can use armed and panel

- entry and exit delay only panel
- the arm commands: armed_stay/night/away can be with panel only but you get no extra confirmation beep, if you also set the armed value you get one longer confirmation beep

For exemple

**Comment by Kane610** [comment]
Should these be the same? armed - not_ready | panel - not_ready_to_arm
There is no representation of these with panel? already_disarmed, invalid_code, (not_ready)

So panel is only used for audible signalling? Main state of the device should be based on armed in that case?
So preferrably one should always set both panel and armed?

You say there are keyfobs, does that mean that panel is optional?
Certain devices might exclude reporting panel altogether?
How does the action string look like on keyfobs without code? {"action": "armed_away,,12"} or {"action": "armed_away,12"}

What is the sequence number you're mentioning?

Presence sensor is a PIR sensor?

**Comment by Smanar** [comment]
>Should these be the same? armed - not_ready | panel - not_ready_to_arm
>There is no representation of these with panel? already_disarmed, invalid_code, (not_ready)

Values are direclty from the zigbee library documentation, so I think it s device dependent, the brand can do that it want with them, you can see some device differences here https://github.com/arnbme/nyckelharpa/blob/master/Centralite-Keypad.groovy

>So panel is only used for audible signalling? Main state of the device should be based on armed in that case?
>So preferrably one should always set both panel and armed?

I think @a1ad  can confirm. But yes for me the more important is "armed", "panel" is just like a LED or a beeper, keyfob can arm or disarm but don't have panel at all.

>You say there are keyfobs, does that mean that panel is optional?
>Certain devices might exclude reporting panel altogether?

Yes

>How does the action string look like on keyfobs without code? {"action": "armed_away,,12"} or {"action": "armed_away,12"}

I think here it s possible improve the code, for the moment keyfob are used like remote, so are ZHAswitch, for me will be better to use them as ZHAAncillaryControl too.
The notification is totally disabled for keyfob, as they don't need code validation, deconz always validate them and "armed" is automaticaly updated.

>What is the sequence number you're mentioning?
The code handle it itself.
When the device send a arm command, the gateway need to answer, and with the same sequence number (like for all zigbee requests). So when you "validate" the code, deconz use the same sequence number to answer.
But after some tests, it seem it s not so important, ikke-zelf use the same sequence number, or no sequence number at all with z2m, and all is working, but is described like that in the zigbee bible so doing same.

>Presence sensor is a PIR sensor?

Yes (if @a1ad can firm too)

**Comment by a1ad** [comment]
@Smanar i dont know about panel/armed.. normally i am using both but in the case of armed_night i don't want a confirmation beep so i only use panel. i ll use both when i want a confirmation beep.

My alarm is auto disarmed at 6u30 in the morning so i don't want that beep.

In node red ill do it like this:
afbeelding
Also no exit_delay sound when activating night mode.

Panel = status keypad (right alarm mode is set to the keypad. ex: when armed_away -> armed_away button is red)
Armed = for me the only difference is a confirmation beep when setting the keypad status.

Also with only panel it look like the keypad status is only updating its state when there is presence detected. With both the status is immediately changed.

Presence is acting like a PIR indeed:
afbeelding

afbeelding

**Comment by a1ad** [comment]
@Smanar: i v got the sleep problem again when testing with only "panel" to disable the sound... it seemd that you always need armed. :s

**Review by SwoopX — COMMENTED** [review]
Sorry, but why do you rape the IAS zone code like that and make things so tremendously complicated? 😄 Please don't!

Why not just add RStatePresence to the ACE items, as all the rest of the IAS zone items is already and just add a new check in `processIasZoneStatus()` for the new device type? Much cleaner, no potential to break existing stuff, just 3 additional lines of code and no more problems/hacks.

**Comment by Smanar** [comment]
Yeah was one of my problem ^^.

In my mind was better to create 3 sensors for the device
- ZHApresence
- ZHAAncillaryControl
- ZHAAlarm (not used in my code because I don't find it usefull but possible, z2m use it too)

So for you, you think it's better making only 1 entry, will all field, easier for me, but not sure for third party integration ?

**Comment by Kane610** [comment]
Keep them as separate endpoint in the rest api please

**Comment by manup** [comment]
This will need some time to get ready to be merged. I don't really like nor understand what happened to the IAS Zone code.
I'm not sure yet how, but we need to separate a few things to get cleaner code and simpler functions.

For the IAS ACE code can you please align it with the usual code style, it looks a bit rough ;) When this is done I'd like to check how to cleanly separate the various steps which play a role here.

**Comment by Smanar** [comment]
On the ias Zone code, I have done only 2 changes.
- It can support more than 1 sensor that use IAS cluster, but only one have the enrollement stuff. So the code parse all all sensors (like before) but now it check too if this one have the enrollement stuff.
- A sensor can have the field "tamper" and "lowbattery" but don't have special type like ZHAPresence or ZHAAlarm.

That's all.

**Comment by manup** [comment]
>It can support more than 1 sensor that use IAS cluster, but only one have the enrollement stuff. So the code parse all all sensors (like before) but now it check too if this one have the enrollement stuff.

That's what confuses me :) the IAS Zone code does already check that the given sensor has the required items in the first 5 lines.
The basic idea is that `checkIasEnrollmentStatus(Sensor*)` only operates on the sensor given in its argument — it shouldn't know nor access the `sensors` vector. The function gets called from various places, sometimes from loops iterating over all sensors.

With the PR the function "extends" looping and does the same as the caller of the function again within the function:


```cpp
for (auto &s : sensors) {
   checkIasEnrollmentStatus(&s);
   ...
         for (auto &s : sensors) {
                 // test again
          }
   ...
}
```

If there are 50 sensors, we loop 50 x 50 in worst case :) 
Therefore if there are missing calls for some sensors they should be added outside of the function on the calling side.

>A sensor can have the field "tamper" and "lowbattery" but don't have special type like ZHAPresence or ZHAAlarm.

Ah ok, this is quite interesting. I'm not sure why the dependency on the type was done in the past. If I remember correctly there were at least a few devices (Climax?) where the low battery bool wasn't extracted from IAS status due invalid values and instead  was derived from _non_ IAS attribute reports.

**Comment by Smanar** [comment]
>If there are 50 sensors, we loop 50 x 50 in worst case :)

Yep, but it s realy fast, nope ?

>Therefore if there are missing calls for some sensors they should be added outside of the function on the calling side.

Here, I don't realy understand what you mean ?
But after reflexion, I don't think this code part was usefull

If you have 3 sensors ZHAalarm + ZHApresence + ZHAAncillaryControl, but the enrollment stuff only on the ZHAAncillaryControl (it s the principal sensor), the fonction checkIasEnrollmentStatus will be skipped for 2 devices/3, but only one is enought to make the enrollement.
No ?

**Comment by manup** [comment]
> > If there are 50 sensors, we loop 50 x 50 in worst case :)
> 
> Yep, but it s realy fast, nope ?

We already have the problem that the code base has become way slower than it should be, it could be 500–1000 times faster ;)
There are just so many unnecessary loops, we need to be carefully to not add more if we can prevent it.

So in this example if we can iterate just 50 times instead 2500 we should take the chance.

> > Therefore if there are missing calls for some sensors they should be added outside of the function on the calling side.
> 
> Here, I don't realy understand what you mean ?
> But after reflexion, I don't think this code part was usefull
> 
> If I remove this part (for this fonction) and if you have 3 sensors ZHAalarm + ZHApresence + ZHAAncillaryControl, but the enrollment stuff only on the ZHAAncillaryControl (it s the principal sensor), the fonction checkIasEnrollmentStatus will be skipped for 2 devices/3, but only one is enought to make the enrollement.
> 
> So for me perhaps not usefull.

Do I understand this right `ZHAalarm` and `ZHAAncillaryControl` both have the IAS cluster?

I think the PR change in `handleIasZoneClusterIndication()` already has the solution by only selecting the sensor which has the `RConfigEnrolled` and `RConfigPending` items. With this there is no need to loop again inside `checkIasEnrollmentStatus()`.

The initial start of the IAS handling should be done for a specific sensor (here `ZHAAncillaryControl`)  like it is done for other IAS sensors in `addSensorNode()`.

**Comment by SwoopX** [comment]
I repeat my comment https://github.com/dresden-elektronik/deconz-rest-plugin/pull/4758#pullrequestreview-637058223

Don't overenginneer, decide on the chosen one and there will be no problems 😉

**Comment by Smanar** [comment]
>Do I understand this right ZHAalarm and ZHAAncillaryControl both have the IAS cluster?

Yep, else they can't work, the ZHAAlarm is pure IAS_ZONE sensor, and ZHAAncillaryControl nned it too, because in the better situation it will be the only one sensor, so If I can prevent the creation of a second sensor just to use "tamper" or "lowbattery" ...

>I think the PR change in handleIasZoneClusterIndication() already has the solution by only selecting the sensor which has the RConfigEnrolled and RConfigPending items. With this there is no need to loop again inside checkIasEnrollmentStatus().

Yes, I think too it will be better, will make some tests.

>Don't overenginneer, decide on the chosen one and there will be no problems 😉

Have already asked for tuya devices, I wanted to do only 1 sensor with all field, and all others devs have say "no, not good idea for third app integration".
I m agress with you, will be easier, but no one like it ...

**Comment by Smanar** [comment]
Ok so the fonction checkIasEnrollmentStatus() is restored, like before.
@a1ad have tested. for this fonction, you need only 1 entry with the enrollement stuff.

**Comment by a1ad** [comment]
what is the status? We v got official HA support and the deconz code is working great here.

**Comment by manup** [comment]
Thanks Smanar the PR has improved :+1:  but needs more work, especially the file `ias_ace.cpp` is currently a bit off from the remaining code style. I have a few question while skimming over the code, will add them in a review.

**Comment by Smanar** [comment]
I think I will buy the book, "the deconz code style for newbies"

**Comment by manup** [comment]
It's a classic best seller :smile: for the most part it follows the Qt coding style.

**Comment by Smanar** [comment]
Add device IRIS 3405-L Keypad https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4845

**Comment by leonardpitzu** [comment]
how do you set a pin code on this thing? how do you change it? it so happens i own such a keypad but i have no manual or other device around it.

**Comment by Smanar** [comment]
The implementation in HA is not my job but the @Kane610 one ^^.
This device is a "dummy" device, all job need to be done by the third app.

**Comment by froogl** [comment]
@Smanar So all of the button presses are exposed through the REST API or as events? That would be awesome, as it makes using these keypad devices super flexible. :tada:

**Comment by a1ad** [comment]
> @Smanar So all of the button presses are exposed through the REST API or as events? That would be awesome, as it makes using these keypad devices super flexible. 🎉

4 digit code is send to API/websocket. So yeah you can use it for plethora of automations

**Comment by froogl** [comment]
> 4 digit code is send to API/websocket. So yeah you can use it for plethora of automations

Just 4 digit codes? Not every single keypress? What about codes of any arbitrary length?

**Comment by a1ad** [comment]
> > 4 digit code is send to API/websocket. So yeah you can use it for plethora of automations
> 
> Just 4 digit codes? Not every single keypress? What about codes of any arbitrary length?

Nope, the keypad send only data after you press 4 digits. It is by keypad design, nothing to do with deconz.

**Comment by leonardpitzu** [comment]
i have managed to fully integrate the keypad in HA and the alarm works great so far. If it's armed in AWAY mode the keypad keeps beeping and never stops. Is it intended like this is is there something wrong?

**Comment by Smanar** [comment]
I haven't the device to test, but perhaps the device have skipped a request ?

**Comment by leonardpitzu** [comment]
Might be. How can i check?
I was on an older build and I am currently struggling to build the main/latest which I failing. Do you have an ARM64 test build available by chance?

**Comment by Smanar** [comment]
With checking log, or easier just send again the command.
The device support 2 command, one for the armed mode and one for the panel mode, it s the second one that act on the "sound"

If the situation appear again, just try to send again the {"panel": "arming_away"}, or just check the actual value.

I m not sure for the value, but from my memory the beeping one is "exit_delay"

And for ARM64, perhaps the deconz_dev package is here http://deconz.dresden-elektronik.de/raspbian/alpha/

**Comment by leonardpitzu** [comment]
Yeah, beeping is the exit_delay. I’ll check again.
Does the dev build have your push already merged?

**Comment by Smanar** [comment]
Nope, manup have bought a keypad too and want to make some test before

**Comment by leonardpitzu** [comment]
i can't build master:

`/usr/include/deconz/aps.h:68:10: fatal error: deconz/timeref.h: No such file or directory
   68 | #include "deconz/timeref.h"
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
`

the file is missing...

**Comment by Smanar** [comment]
You have succesfully installed the dev-deconz package ?

**Comment by leonardpitzu** [comment]
yeap, 2.12 dev on a clean debian arm64 system

**Comment by Smanar** [comment]
Ok, so I realy don't know the compatiblity difference with debian and Ubuntu, but have you tried the package procedure to install the dev-package ?

https://phoscon.de/en/conbee2/install#ubuntu

The link I have gived can be out of date, there is some change on the dev package, 15 days ago.

**Comment by leonardpitzu** [comment]
Yes,  have a new raspbian install and got the master fresh + your pull

**Comment by a1ad** [comment]
> i have managed to fully integrate the keypad in HA and the alarm works great so far. If it's armed in AWAY mode the keypad keeps beeping and never stops. Is it intended like this is is there something wrong?
> Edit: pulling the batteries out fixed the thing, now it works as expected. still strange...

Yea, i also got that behavior when i did a lot of tests with Smanar. But no problems anymore after i pulled the batteries and only used the official commands.

**Comment by leonardpitzu** [comment]
@Smanar can you look in /usr/include/deconz if you have timeref.h?
i am missing this file and have searched for it in the packages but could not find it...

**Comment by Smanar** [comment]
Yep it is
tmp

**Comment by leonardpitzu** [comment]
something must be wrong - take the latest dev from here, open it and look for the file - it's not in there...

**Comment by Smanar** [comment]
I have made with the package method. On the link I have gived, there is deconz 2.12 but I don't see the deconz-dev package (last one is 

`deconz-dev_2.05.82-debian-stretch-beta_arm64.deb   16-Sep-2020 12:35 `

**Comment by leonardpitzu** [comment]
You can look into that one as well - it’s in the Debian folder where all downloads are.

**Comment by Smanar** [comment]
Ha you are right !
Will ask to dev channel.

**Comment by leonardpitzu** [comment]
Please add it in here - i’lol test it once I get home a bit later in the day.

**Comment by Smanar** [comment]
You have it here https://pastebin.com/duJMqqvH

**Comment by leonardpitzu** [comment]
thanks, it worked great. i have a fully functional keypad which integrates great with HA. Thanks!

**Comment by Smanar** [comment]
Have just updated the code to be compatible with last format. It compile, but I can't test it on my side.

**Comment by callebridholm** [comment]
Any update when this feature will be added to stable version of deCONZ?

**Pull request merged**
