### PR TITLE
Update _TZ3000_ygvf9xzp_4gang_remote.json

### PR DESCRIPTION
**Pull request by sinus61**
I have a few of the switches here and most of them have much battery loss, they reported battery values are not real anyway.
Now I have changed config/battery the battery values are still wrong, according to other zigbee projects you need some tuya magic here.
But there is no real battery loss anymore. battery is reported when a button is pressed, and the switch gives a heartbeat avery 4 hours, like it is stated in the tuya documentation.

### CODE REVIEW

**Comment by Smanar** [comment]
Ha ?
I need some explanation here. Can you give the device with battery not working ? Because lot of them are still using the cluster 0x0001, and some other don't work even with working attribute. And yes if the report is not working, deconz will poll the device cause battery drain.
But this issue need to be solved by 
`"refresh.interval": 84000,`

>Now I have changed config/battery the battery values are still wrong, according to other zigbee projects you need some tuya magic here

So reading the tuya cluster don't work ?

For information, as exemple the device _TZ3000_ygvf9xzp don't have the tuya cluster, so this DDF can't work with it.

**Comment by sinus61** [comment]
I don't have all switches from the DDF here, but I can say for
_TZ3000_abci1hiu
_TZ3000_ufhtxr59
_TZ3000_b7bxojrg
the battery problem exists and was not resolved with just the refresh.interval changing.
_TZ3000_dziaict4 was working before and now also.

There some discussions at z2m about this:
https://github.com/Koenkk/zigbee2mqtt/issues/8072
https://github.com/Koenkk/zigbee-herdsman-converters/pull/4742/commits

If _TZ3000_ygvf9xzp is different maybe separate DDFs are needed. I dont' have that device, but optical it looks like the _TZ3000_dziaict4.

**Comment by sinus61** [comment]
> So updating battery with reading the tuya cluster don't work ?

No, but it haven't worked before. It is reporting something, i.e. _TZ3000_b7bxojrg has reported 95% before and 95% now. It doesn't change even I put a new or old battery in or add a external 3V power source.

**Comment by Smanar** [comment]
Ha nice found ^^.
But we have 2 problems.

1 - On Z2M they are removing the battery bind/report and using the tuya unlock sequence, the second part is not yet possible on deconz, but idk if it's needed ?
2 - Some device on the DDF are working fine, so need to make something to separe them.

> maybe separate DDFs are needed

Yes I think, need to check all models, I will update this post later.

PS:
There is user with the _TZ3000_wkai4ga5  and the battery drain here https://github.com/dresden-elektronik/deconz-rest-plugin/pull/5881

**Comment by Smanar** [comment]
But on Z2M they just disable the report/bind, the device is still making his report on the cluster 0x0001 but naturally, they are not using the tuya cluster.

Device that have battery leak:
- _TZ3000_wkai4ga5
- _TZ3000_abci1hiu
- _TZ3000_ufhtxr59
- _TZ3000_b7bxojrg

Device that haven't battery leak:

Device to check:
- _TZ3000_ygvf9xzp
- _TZ3000_ee8nrt2l
- _TZ3000_dziaict4
- _TZ3000_mh9px7cq
- _TZ3000_ufhtxr59

**Comment by sinus61** [comment]
Hmm, I think have just played with min/max there, which doesen't help. I'll try it and let it run a few hours.

For the 2 gangs, the _TZ3000_t8hzpgnd have also the battery leak.

**Comment by sinus61** [comment]
Ok, running since yesterday and looks good for now. I've logged what they push via the API and all switches gives a heartbeat every 4 hours.
3 of them report battery when you press a button. Also _TZ3000_b7bxojrg reports battery every hour and _TZ3000_ufhtxr59 every 4 hours.
Only _TZ3000_abci1hiu don't report battery anymore. It's the only one with a Tuya specific cluster.

**Comment by Smanar** [comment]
For the battery report can be a problem with the tuya unclock sequence.
But I don't think we need it to prevent the battery leak, so your method can work for that.
Unfortunately an user have tried with a simplified DDF, without success, I m making something bad ? https://github.com/dresden-elektronik/deconz-rest-plugin/pull/5881#issuecomment-1427086457

**Comment by BabaIsYou** [comment]
If it could help I currently use _TZ3000_ee8nrt2l with this config in DDF without any trouble with battery drain : 

```
        {
          "name": "config/battery",
          "awake": true,
          "parse": {
            "at": "0x0021",
            "cl": "0x0001",
            "ep": 1,
            "eval": "Item.val = Attr.val / 2;",
            "fn": "zcl"
          },
          "default": 0
        },
```

```
{
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0001",
      "report": [
        {
          "at": "0x0021",
          "dt": "0x20",
          "min": 60,
          "max": 3600,
          "change": "0x00000001"
        }
      ]
    },
```

**Comment by manup** [comment]
Hi, interesting case, is the PR ready to merge or are changes needed?

**Comment by sinus61** [comment]
> If it could help I currently use _TZ3000_ee8nrt2l with this config in DDF without any trouble with battery drain :

According to blakadder it looks like the _TZ3000_ee8nrt2l is the V2 to the _TZ3000_ufhtxr59, maybe Loratap fixed something here.

**Comment by sinus61** [comment]
> Hi, interesting case, is the PR ready to merge or are changes needed?

I think all should work now. No battery loss here, battery is reported at least if you press a button. 
Maybe later a separate DDF for switches with Tuya specific cluster like the _TZ3000_abci1hiu make sense, if you could read they battery state from there. But it works as a switch also with this DDF.

**Comment by JerreV** [comment]
Hi,

Tried the code for the _TZ3000_wkai4ga5 I have.
The lights don't seem to flicker at random anymore so I guess the battery drain is fixed but the battery level is not send at all so it always shows 0. I guess for that it need the "tuyamagic" I saw mentioned somewhere.

**Comment by sinus61** [comment]
You may go to the deConz GUI, select the Power Configuration Cluster, double-click at 0x0021 und press "read". Then press a button on your remote. I get a value then. Don't know if this will update later or is real.

**Comment by Smanar** [comment]
>You may go to the deConz GUI, select the Power Configuration Cluster, double-click at 0x0021 und press "read". Then press a button on your remote. I get a value then. Don't know if this will update later or is real

When you read the attribute using the GUI, it will update the value in the API, but only for 1 time, we need to enable the reporting, and I think this part need the tuya unlock sequence.

On Z2M they are using this trick for all devices now TS0041 > TS0044.

So I think we can use it on all DDFs
- https://github.com/dresden-elektronik/deconz-rest-plugin/blob/master/devices/tuya/_TZ3000_itb0omhv_1gang_bat.json
- https://github.com/dresden-elektronik/deconz-rest-plugin/blob/master/devices/tuya/_TZ3000_5e235jpa_2gang_remote.json
- https://github.com/dresden-elektronik/deconz-rest-plugin/blob/master/devices/tuya/TS0043_3gang_remote.json
- https://github.com/dresden-elektronik/deconz-rest-plugin/blob/master/devices/tuya/_TZ3000_ygvf9xzp_4gang_remote.json

We will miss the battery return for already working devices, but better to miss a battery return that having a battery drain.
Time to make the tuya unlock sequence.

But not sure It work for all devices https://github.com/dresden-elektronik/deconz-rest-plugin/pull/5881#issuecomment-1427086457

>Maybe later a separate DDF for switches with Tuya specific cluster like the _TZ3000_abci1hiu

This one have the tuya cluster ? From this site https://community.jeedom.com/t/demande-ajout-equipement-telecommande-tuya/61648 It seem it's a classic one.

**Comment by JerreV** [comment]
> You may go to the deConz GUI, select the Power Configuration Cluster, double-click at 0x0021 und press "read". Then press a button on your remote. I get a value then. Don't know if this will update later or is real.

Okay after looking for a bit I got a value back and it even shows it in my Home Assistant.
Thanks!
image

**Comment by Smanar** [comment]
>_TZ3000_abci1hiu

Ha fck :(, I have a bad feeling for this one.

On Z2M project https://github.com/Koenkk/zigbee2mqtt/issues/8461 this device use the old method ^^, the cluster 0x0001, but with tuya not possible to be sure, and it seem his one don't have the tuya cluster.

I think it will be a future challenge to make battery working on tuya ...... But removing the battery leak is nice.

**Comment by Smanar** [comment]
@sinus61 , Sorry I have made a mistake, I have tried to correct the conflict.
It have worked, but it have removed your last device.

**Comment by sinus61** [comment]
@Smanar 
For me everything is working now, no tuya magic needed atm

**Comment by Smanar** [comment]
@manup For me this PR is fine.

- It mix 2 DDF in one (for the 2 gangs).
- It add some clone.
- Remove the battery drain

The only mystery will be the result on the already working device, it the worst situation they will just miss the battery report.

Just 2 remarks @sinus61 
- I have tried to remove a conflict with editing code, and by error I have removed the model "_TZ3000_w3c7ouru", if you can re-add it yourself ?
- You still have isue on your side for battery return on "patched" devices ? On Z2M they are using the Tuya unlock sequence, but they are using it all the time even on device that don't need it.

**Comment by manup** [comment]
> @manup For me this PR is fine.

Thanks for the review, from my side it also looks good. Just needs update to fix the merge conflict.

**Comment by sinus61** [comment]
@Smanar 
I'm not sure now, but doesn't come _TZ3000_w3c7ouru from your [PR](https://github.com/dresden-elektronik/deconz-rest-plugin/pull/6728)

I've tried it with and withou the Tuya magic, I don't see any difference even on devices with Tuya cluster. And everything makes no difference how often the device reports battery through the API, some makes it  every hour, others once a day or only if a button is pressed. At least then that device reports battery.
And every device gives a tuya heartbeat every 4 hours and reports lastseen via the API, so you can see if a device is dead or not. For me thats enough.

But maybe it's a good idea to add the Tuya unlock sequence to all tuya device, if it brings at least nothing bad. For newer device it's maybe needed and makes it easier to add them. I'm not really sure how often the Tuya unlock sequence is needed, maybe it was enough I've used it for testing and removed it later to get something to work.

**Comment by Smanar** [comment]
>I'm not sure now, but doesn't come _TZ3000_w3c7ouru from your PR

Ha yes, have totally forget my PR ^^. But my comment was because of my Merge after this comment https://github.com/dresden-elektronik/deconz-rest-plugin/pull/6744#issuecomment-1431767508
It have solved the conflit but removed your last modification.

>At least then that device reports battery.

So perfect.

>But maybe it's a good idea to add the Tuya unlock sequence to all tuya device, if it brings at least nothing bad. For newer device it's maybe needed and makes it easier to add them. I'm not really sure how often the Tuya unlock sequence is needed, maybe it was enough I've used it for testing and removed it later to get something to work

Not realy, if the device don't support the read on the attribute 0xffe, the tuya unlock sequence will provoke a read attribute error, and IDK how deconz will react, it can give up or spam the device.

>For newer device it's maybe needed and makes it easier to add them. I'm not really sure how often the Tuya unlock sequence is needed, maybe it was enough I've used it for testing and removed it later to get something to work

Right, @BabaIsYou have same idea, I will make a PR to add it easily
Need to make it only 1 time, but ATM not possible with DDF, so the request will be made every 24h

BTW you still have a conflict on the PR, you can probably solve it using the "resolve conflict' button

**Comment by sinus61** [comment]
About the conflict, don't know how to solve that.
grafik

and on my side I can only discard everything
grafik

**Comment by Smanar** [comment]
Can try first to update the branch.
On your fork, update the "master" branch using "sync fork" on the main page, on top. As your PR was made on the master branch, I think it can be enought to enable the "resolve conflict" link (for only 1 file, no need to use external editor)

**Comment by sinus61** [comment]
Hmm, looks like that removed anything

**Comment by Smanar** [comment]
And I don't found how to make rollback.

**Pull request closed without merging**
