### PR TITLE
DDF Add support for Tuya Raw request and add support for energy meter _TZE204_ac0fhfiq

### PR DESCRIPTION
**Pull request by Smanar**
With the @decrouxtom help, See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/7151

- Product name: Tuya BiDirectional ZigBee Energy Meter with 150A Clamp Current Sensor
- Manufacturer: _TZE204_ac0fhfiq
- Model identifier: TS0601

We have added an item state/direction, can be used later by covering.

Tuya raw data are converting to hexa string, to be used in JS code without the use of code like (and are now visible on debug)

`"Item.val = (ZclFrame.at(6) << 8) | ZclFrame.at(7)) / 10;"`

### CODE REVIEW

**Comment by manup** [comment]
Sorry I have a few problems with this PR.

`state/direction` --> "consumer" | "producer"   sounds strange to me, the description in the Tuya docs sounds more clear, perhaps even just leave it as the 0,1 integer?

>Tuya raw data are converting to hexa string, to be used in JS code without the use of code like (and are now visible on debug)
>"Item.val = (ZclFrame.at(6) << 8) | ZclFrame.at(7)) / 10;"

But this very code is so much better than the string conversion dance. It extracts the data right from the ZCL frame and is super fast. It's almost a no-op and does zero dynamic memory allocations. (Spoiler alert: In future such simple numeric expressions will be compiled away automatically, so the JS engine doesn't even need to run here).

In contrast the string version is magnitudes slower:

* Allocate a dynamic QByteArray buffer (now for each invocation of the Tuya function, not only raw data, since it's at top function scope)
* Allocates another dynamic QByteArray via toHex() and does a string conversion
* Bumps that string into JS where it is split up again
* To build a new string appended to another "0x" string
* That is parsed into an int

.... and everything two times :smiley:  :see_no_evil: 

-----------------------------------------------

Sorry for being so picky on such things, yes it's 2023 and in small networks on fast PC's it doesn't matter. But my goal for the refactor of the code base is also to get rid of *all* slow code paths. Currently all Zigbee projects including deCONZ are slow and struggle with larger networks.

But for us it will be possible in future to have large networks > 500 nodes running on a Raspberry Pi 1 like host, e.g. a OpenWRT home router. The magic behind this is simple: we need to process incoming messages as fast as possible, I'm aiming for 100/sec minimum, currently we are on 10-20/sec if we are lucky on a fast machine. This is with one ConBee/RaspBee connected, but in future it will be possible to connect multiple to one deCONZ instance in parallel.

**Comment by Smanar** [comment]
Have removed the raw support, new PR here https://github.com/dresden-elektronik/deconz-rest-plugin/pull/7204

> the description in the Tuya docs sounds more clear,

They call that power direction, what do you prefer as name ?

**Comment by decrouxtom** [comment]
> Have removed the raw support, new PR here #7204 @decrouxtom if you want to try the new DDF ?

Sorry, I missed this message. I'll try as soon as I can

**Comment by decrouxtom** [comment]
Hello,
Sorry, I probably missed something but the DDF is not working. Do I need to recompile ?

**Comment by Smanar** [comment]
Oups sorry.
@decrouxtom was on holiday, was just come back, so the DDF here is not working ?
https://github.com/dresden-elektronik/deconz-rest-plugin/pull/7204

But I m using some command than here https://github.com/dresden-elektronik/deconz-rest-plugin/issues/7151#issuecomment-1676281754

**Comment by decrouxtom** [comment]
After re-pairing the device, I think it works but I needed to rename the DDF with a E capital case for Energy to be recognized. But in the meantime,my domoticz has some troubles. I cannot access it even no errors are displayed in the log... Please let me few days to recover and confirm the DDF is fine ;)
Write to you soon!

**Comment by Smanar** [comment]
No problem, I have set the PR on draft status, waiting for your return.

**Pull request closed without merging**
