### PR TITLE
IKEA Vallhorn motion sensor device request

### PR DESCRIPTION
**Pull request by noud-github**
Created a DDF file with a JS file,

My 9 year-old, bought one so I had to quickly make it work ;-)

see https://github.com/dresden-elektronik/deconz-rest-plugin/issues/7454

### CODE REVIEW

**Comment by noud-github** [comment]
will have a look later today (at home)

**Comment by Mimiix** [comment]
I am not sure if this is due to other DDF's in your branch.

**Comment by noud-github** [comment]
no it is in mine, did not know and cannot find documentation on fingerprint and did some tweaking that probbely is giving this "correct " issie

**Comment by noud-github** [comment]
FYI:
I mostly copied from the philips SML003_motion_sensor.json 
as I own both so this was the easiest way to a working IKEA sensor.

**Comment by Smanar** [comment]
Just by curiosity the native file for lux is not working ? https://github.com/dresden-elektronik/deconz-rest-plugin/blob/master/devices/generic/illuminance_cluster/lux_to_lightlevel.js

Lot of code is able to work natively, sometime you just need to use
```
        {
          "name": "state/presence",
        },
```

But you are in better place than me to say what is working or not ^^

The issue in the validator is here

`"device": "0x"`

In the fingerprint.

Occupancy Sensor = 0x0107
On/off sensor = 0x850
Light sensor = 0x0106

And on your DDF there is some binds I don't see he utility, not used in the DDF core. For exemple attribute 0x0030 on cluster 0x0406 or attribute 0x0033 and 0x0032 on the Cluster 0x0000

**Comment by Smanar** [comment]
Nope ^^.
You need it, but you miss one.
The first one is not complete.

Else don't say it's me that have say that to you, but you can remove all the fingerprint.

**Comment by noud-github** [comment]
fixed the device items , now are valid (and it think correct.)

while adding the lux, I looked at the values shown in the GUI and they looked the same for the SML003 and the vallhorn I figured lets use the same script, but that might return wrong results. will setup the vallhorn next to the SML003 to see if the lux matches,

as sad this was a quick setup to please my son who bought one and was really disappointed it did not show up in phoscon ;-)

**Comment by Smanar** [comment]
Ha right, haven't see this js for philips, so you are certently right.

**Comment by Smanar** [comment]
Missed ^^.
You NEED "device" if you use a fingerprint

`1 validation error in file devices/ikea/vallhorn_wireless_motion_sensor.json at subdevices/1/fingerprint/device`

And this IDK where it's from ...

`"name": "config/OUdelay",`

and you still have the strange Binds https://github.com/dresden-elektronik/deconz-rest-plugin/pull/7513#issuecomment-1877346265

**Comment by noud-github** [comment]
just pushed with I think all your comments addresed, thanx

**Comment by noud-github** [comment]
you can set two delays, on the pressence thsi is for the other, I think I tested it yesterday and it work form HA

**Comment by Mimiix** [comment]
Looks good :) Thanks

**Comment by ebaauw** [comment]
Wanted to pick one up today, but the Amsterdam IKEA store doesn't carry it yet; they need to ditch the current stock of Trådfri motion sensors first.  Will try another store this weekend.

**Comment by noud-github** [comment]
@ebaauw  hengelo did have them at same price as the on "sale" old once,

**Comment by Smanar** [comment]
Just to be sure, there is bind/report for the Presence attribute, but not for the luminance.
Can be native, but be sure it can work without.

**Comment by noud-github** [comment]
shall I add the bind and the static name to the second one?  and create a new PR?

**Comment by Smanar** [comment]
> and create a new PR?

No, can just update this one.
I mean the 2 sensors in this PR, `"name": "attr/productname"` is present for the TYPE_LIGHT_LEVEL_SENSOR but not the TYPE_PRESENCE_SENSOR, it's not usefull, but not logic to have it on one sensor and not the second one for the same device.

For the bind, like I have said, if it work for you, it mean you don't need it.

**Comment by noud-github** [comment]
^^ with added productname, 
it works withoud the bind so I left that for now.

**Comment by jmue** [comment]
Thank you for your work on this. I get no illuminance sensor update within phoscon (shows only value 0lux) without the binding. After manually adding the illuminance binding I can see the sensor value.

**Comment by noud-github** [comment]
I do have reading without, but looking closer it seems static,  that might have been from my testing...

**Comment by Smanar** [comment]
Ha ? 
So mean the binding is needed, on your side, you have probablt made it with previous removed code.

```
    {
      "bind": "unicast",
      "src.ep": 2,
      "cl": "0x0400",
      "report": [
        {
          "at": "0x0000",
          "dt": "0x21",
          "min": 5,
          "max": 300,
          "change": "0x07d0"
        }
      ]
    },
```

**Comment by workoutpeter** [comment]
With binding and repairing, lux works for me.

`    {
      "bind": "unicast",
      "src.ep": 3,
      "cl": "0x0400",
      "report": [
        {
          "at": "0x0000",
          "dt": "0x21",
          "min": 5,
          "max": 300,
          "change": "0x07d0"
        }
      ]
    },`

**Comment by ArnaudFeld** [comment]
If I am running Gateway Version 2.25.1 I should connect it on the normal way?

**Comment by noud-github** [comment]
not sure what the normal way is but all lates IKEA stuff all need 4 (not more or less) button presses on the connection button

**Comment by ebaauw** [comment]
> not sure what the normal way is but all lates IKEA stuff all need 4 (not more or less) button presses on the connection button

Afaik, that has always been the case for IKEA sensors and controllers.  There is no “normal” way across all manufacturers.

**Comment by noud-github** [comment]
@Smanar 

> {
>     "type": "$TYPE_LIGHT_LEVEL_SENSOR",
>      "restapi": "/sensors",
>      "uuid": [
>        "$address.ext",
>        "0x03",
>        "0x0400"
>      ],

setting ep to 3, 
does it also needs the endpoint (below:) need to go to 3? (or is that the enpoint on the "gateway"

    "fingerprint": {
        "endpoint": "0x02",
        "profile": "0x0104",
        "device": "0x0106",
        "in": [
          "0x0400"
        ]
      },

**Comment by ArnaudFeld** [comment]
> not sure what the normal way is but all lates IKEA stuff all need 4 (not more or less) button presses on the connection button

I ask because I updated to 2.25.1 and try to connect it but it wasn't recognized. Any Secret hints for this one?

**Comment by Smanar** [comment]
> setting ep to 3, does it also needs the endpoint (below:) need to go to 3? (or is that the enpoint on the "gateway"

Ha yes, right, I have missed this one.
It's more cosmetic (so can work with bad one) but it's the device fingerprint, so better to use 0x03 too.

**Comment by SwoopX** [comment]
> > not sure what the normal way is but all lates IKEA stuff all need 4 (not more or less) button presses on the connection button
> 
> I ask because I updated to 2.25.1 and try to connect it but it wasn't recognized. Any Secret hints for this one?

Not really surprising since deconz release notes do not meotion is and this PR adds it for Milestone 2.25.2 🙂 Feel free to use the DDF right away.

**Comment by ArnaudFeld** [comment]
ok ;) sorry my fault

**Comment by pawg** [comment]
Thanks for the DDF, I've had some trouble to get it working, but I slowly grasp how to. However, despite the motion sensing part, the luxmeter stays at 0. Any idea why or how to debug? Thanks

**Comment by Smanar** [comment]
Ha yes right, still missing this part.
The normal "working mode" is using bind/report on the bottom DDF, and if this part is failing deconz can make poll using the "refresh.interval".

It's possible the bind was done previously, so even if it's missing in the DDF the device can work for another one, but not out of the box.

**Comment by noud-github** [comment]
@pawg 
did I add your changes in the right place: https://github.com/noud-github/deconz-rest-plugin/commit/ce20a400f2d553fa6ffb2f3203b945cdf2abfc0c

**Comment by Smanar** [comment]
@noud-github now your PR was valided/merged, you can delete your branch, or the complete fork if you can't, to start on a fresh base. The file your are editing ATM is a "desynchronised" version.

`This branch is 5 commits ahead of, 9 commits behind dresden-elektronik/deconz-rest-plugin:master.`

Your fork is ATM is same time ahead and behind, it can be solved but not easy to do, for only 1 file edited, better to start on a fresh base.

**Comment by noud-github** [comment]
merged (current) master into my (forked) branch so should be able to create PR again

**Comment by hyper2910** [comment]
when will 2.25.2 released?

**Comment by marmic-hub** [comment]
2.25.3 is available (https://github.com/dresden-elektronik/deconz-rest-plugin/releases/tag/v2.25.3)
Note, that it still needs a further adjustment and therefore a further release (https://github.com/dresden-elektronik/deconz-rest-plugin/issues/7454#issuecomment-1935496846)

**Pull request merged**
