### PR TITLE
DDF add support for _TZE204_sxm7l9xa mmWave radar sensor

### LINKED ISSUE #6998: Tuya Zigbee Human Presence Sensor
## Device

- Product name: Tuya Zigbee Human Presence Sensor
- Manufacturer: _tze204_sxm7l9xa
- Model identifier: TS0601
- Device type : 
  - Sensor

## Screenshots

image
image

### Basic
image
### Other clusters that are not mentioned above
Tuya specific
image

### PR DESCRIPTION
**Pull request by BabaIsYou**
Fix #6998

### CODE REVIEW

**Comment by manup** [comment]
Can you please put the file through a JSON formatter :)

**Comment by MichaelHeimann** [comment]
Does the manufacturername have to match exactly? Because the device reports "_TZE204_sxm7l9xa" with an 7l9 as does the title of this PR, but the file reads "_TZE204_sxm719xa"  with 719 (l vs 1). I think this is a typo but my understanding of DDFs is not enough to understand the consequences.

**Comment by BabaIsYou** [comment]
Hi,

The manufacturername must be exactly what the device is reporting. And it seems to be the case here. Where do you see the number 1 ?

**Comment by MichaelHeimann** [comment]
You are right. It is an l. The github font in code viewer confused me. Copy and Paste into a textviewer and its a clear l.
Should have done that before.

But to not make it a complete waste of time:

I was troubleshooting the writing of the triggerdistance and I needed the dpid for the write changed. You actually parse/read dpid 107 but write to 4. That didn't work for me.

**Comment by BabaIsYou** [comment]
You’re right … what a mistake !
You could find useful information into originating issue #6998

**Comment by MichaelHeimann** [comment]
I've created a change request #7132 (hopefully correctly, being a github noob)

**Pull request merged**
