### PR TITLE
Danalock

### PR DESCRIPTION
**Pull request by denv3r**
Hi Team,

Here is some code to support Danalock V3.
It is not perfect. It lacks a battery sensor and to initialize you need to manually read the state of the lock (I don't know why and if it can be fixed by code).
But according to https://github.com/dresden-elektronik/deconz-rest-plugin/issues/520 a lot of people need this support. And it is better than nothing.

Kind regards,
Denis

### CODE REVIEW

**Comment by Smanar** [comment]
I think you have a problem with the  rest_lights.cpp file, hard to see the code modification.

**Comment by smulle48** [comment]
@denv3r I have tried to merge it into the current release, but I can see the code has changed a lot.

Can you please make it work with current release? :-)

**Comment by smulle48** [comment]
> I think you have a problem with the rest_lights.cpp file, hard to see the code modification (@@ -1,2687 +1,2702 @@)

there are 3 modifications.

If you search for the word danalock you will find them

Just successfully modded the latest deconz with the code and can confirm it's working

**Comment by denv3r** [comment]
Github also shows that pull request compatible with the current version

**Comment by Smanar** [comment]
Sure I don't say the code is bad, just there is a problem that make the "difference check" harder.
On my side I m seing 1,2687 line removed and 1,2702 added.

**Comment by mozzbozz** [comment]
> Sure I don't say the code is bad, just there is a problem that make the "difference check" harder.
> On my side I m seing 1,2687 line removed and 1,2702 added, not only your changes, but it s just "aesthetic", not a problem.

If you choose the option "hide whitespaces", you will see what really changed.

However the creator of this merge request should adjust the settings of his text editor or IDE. And then recommit these files without the whitespace changes. There is simply no way they will accept this merge request like this 😬

**Comment by denv3r** [comment]
@mozzbozz there is nothing to adjust in my text editor because everything was fine until I pressed the button to resolve conflicts on github.
Somewhy github made this. I don't know maybe I also did something wrong. What I know is when I created this pull request I was able to see clearly all the differences.
Basically, I don't understand how to revert everything back. I will try to remove the last commit (related to conflict resolution).

**Comment by mozzbozz** [comment]
@denv3r I've looked into it locally now. But in none of my standard git-tools I could discover what causes this. I thought "oh, you've hit 'reformat file' or got the line endings (Windows vs. Linux) mixed up" but if I haven't overlooked something, that's not the case. I mean... git can be fun, but normally it's easy to sort out if you dig into it. However this time, I'm either simply ready for holiday (brain is done with thinking?) or it's something weird going on. If anyone figures it out, I'd be interested in the cause of this.

Sorry that I can't really help you with this problem... (but I'm used to gitlab and maybe there are things about github I don't know too well)

Only one more idea:

> until I pressed the button to resolve conflicts on github.

So you resolved the conflicts in the github webinterface, right? It could be that it uses the LF line endings (Linux) only while the repository seems to use CR+LR (Windows) line endings if I saw it correctly. So that might explain the huge diff in that single file. But why doesn't my local system show it then? Well, git converts line endings locally when pulling from a repo (depending on some configuration the user can set). So that might hide the different line changes on my local system.

So my suggestion would be to *locally* revert to the commit before the conflict resolving and then *locally* merge the according base branch from this repo and *locally* resolve the conflicts without the help of the github web-texteditor.

(or maybe I'm completely wrong and there is some different much simpler solution)

**Comment by Smanar** [comment]
Hello, sorry , there is new conflict on the same file
And the date limit is soon ...

**Comment by Smanar** [comment]
Hello, for information someone else have do a PR without conflict and his code was validated.

https://github.com/dresden-elektronik/deconz-rest-plugin/pull/3030

**Comment by SwoopX** [comment]
Closing this one as PR #3030 has been merged.

**Pull request closed without merging**
