### PR TITLE
Fix validation errors

### PR DESCRIPTION
**Pull request by ebaauw**
Just added the missing mandatory items.

### CODE REVIEW

**Comment by Smanar** [comment]
Just adding missing field will not make the device working. Most of them need to work without.
I can say at least for one of them this change will break the device support, and haven"t check the others.

**Comment by ebaauw** [comment]
So please update the DDFs so that device support works and they pass validation.

**Comment by Smanar** [comment]
> So please update the DDFs so that device support works and they pass validation.

Not possible, else it will be already done.
Someone suggested a field in DDF to signale the validator to ignore them, I m agree with that, with the tons of devices that will come and will not be standards.

**Comment by ebaauw** [comment]
Skipped DDF validation for the danalock and the legrand cable outlet.  I think the changes to the other three DDFs are valid, and we can continue to validate these.

Meanwhile PR https://github.com/dresden-elektronik/deconz-rest-plugin/pull/7393 introduced a new DDF failing validation.  WTF?!

**Review by manup — APPROVED** [review]

**Pull request merged**
