### PR TITLE
FYRTUR battery and OSRAM power-on settings

### PR DESCRIPTION
**Pull request by ebaauw**
**FYRTUR Battery**
- Add support for `ZHABattery` and `CLIPBattery` sensors, with `state.battery` and `state.lastupdated`, but without `config.battery`, see #1827;
- For now, a `ZHABattery` sensor resource is created only for the IKEA FYRTUR and KADRILJ smart blinds (that are otherwise only exposed as a light resource), see #1121;
- I haven't touched `config.battery` for other sensor resources;
- Not sure how much of this we want to pursue before API v2, see #1827.  The logic works for "all" devices with a _Power Configuration_ cluster (to test, remove the `if` statement from https://github.com/ebaauw/deconz-rest-plugin/blob/dc83c121cf40e6d4331765f811623631c443b5d5/de_web_plugin.cpp#L3627-L3631), with some restrictions:
  - I haven't implemented the code to update `state.battery` from _Battery Voltage_;
  - I haven't implemented the code to create a `ZHABattery` for Xiaomi devices, nor to update `state.battery` from the Xiaomi special attribute report;
  - `config.group` is populated for the `ZHABattery` sensor for devices that send group commands (wireless switches, Trådfri motion sensor).  This is done in too many places in the code to check for `ZHABattery`.
```
{
  "config": {
    "alert": "none",
    "on": true,
    "reachable": true
  },
  "ep": 1,
  "etag": "03741a300ae80dac92894b7b84e2b2e6",
  "manufacturername": "IKEA of Sweden",
  "modelid": "FYRTUR block-out roller blind",
  "name": "FYRTUR block-out roller blind ",
  "state": {
    "battery": 92,
    "lastupdated": "2019-09-08T16:04:43"
  },
  "swversion": "2.2.007",
  "type": "ZHABattery",
  "uniqueid": "00:0d:6f:ff:fe:9e:00:aa-01-0001"
}
```

**OSRAM Power-On Settings**
- Added to `general.xml` the OSRAM manufacturer-specific cluster to set the power-on defaults to the current state, see #102, #1833.

### CODE REVIEW

**Comment by mysteryan** [comment]
The power-on default cluster appears with those commits to general.xml for bulbs identifying their manufacturer as “OSRAM”, but doesn’t show up for LEDVANCE ones.  I think it uses a similar cluster address FC01 instead of FC0F so a simple inclusion of that address should fix it.
B2264033-248A-45B7-A88A-E6071571C0CA

**Comment by ebaauw** [comment]
What _Manufacturer Code_ does Ledvance use?  Also 0xbbaa?

**Comment by mysteryan** [comment]
Manufacturer code: 0x1189
Copy and pasted a duplicate of your commit and substituted fc01 for fc0f, manufacturer code with 0x1189 for 0xbbaa and LEDVANCE for OSRAM for name and seems to work fine for the modified duplicate.

**Comment by ebaauw** [comment]
Cool!  Could you create a PR for that?

**Pull request merged**
