### PR TITLE
Adding new sensor from Luminea Home Control

### PR DESCRIPTION
**Pull request by BabaIsYou**
Adding new sensor from #6632 
Luminea Home Control Tür- und Fensteralarm für ZigBee-Gateway, App, Sprachsteuerung

### CODE REVIEW

**Comment by manup** [comment]
Thanks looks fine, but needs an update on top of master branch to solve merge conflict.

**Comment by BabaIsYou** [comment]
Already merged and file moved since that. This one can be closed.

**Comment by wunni1** [comment]
Is this Sensor (TZ3000_4ugnzsli) now implemented in the last release 2.21.0?

**Comment by BabaIsYou** [comment]
> Is this Sensor (TZ3000_4ugnzsli) now implemented in the last release 2.21.0?

Sorry, seems I mixed two PR from two different devices impacting the same DDF. Added it in a new PR.

**Pull request closed without merging**
