### PR TITLE
Report battery correctly for samjin multi sensor

### PR DESCRIPTION
**Pull request by torandreroland**

### CODE REVIEW

**Comment by Smanar** [comment]
Only light can use state/battery.
All sensors will use config/battery.

**Comment by torandreroland** [comment]
Thanks. Can you point me in the direction of the api? Currently the sensor is not reporting battery correctly and the current pull request basically includes the generic item for state/config works with homebridge deconz.

**Comment by Smanar** [comment]
For sensor https://dresden-elektronik.github.io/deconz-rest-doc/endpoints/sensors/#sensors only config/battery
For light, nothing official ^^, but there is no "config" on light device.

It's perhaps a parsing problem, but its' not something new, all sensors are working like that from the start, strange it's the only sensor where you have the issue !

**Comment by torandreroland** [comment]
All right, I changed the pull request to use config/battery instead. I added parsing and reading of the correct endpoint, cluster and attribute to complement [config_battery_item](https://github.com/dresden-elektronik/deconz-rest-plugin/blob/master/devices/generic/items/config_battery_item.json).

**Comment by SwoopX** [comment]
We're almost there. The functions contained in the items are the defaults to use. I guess `state/battery` shouldn't have any as well. The "issue" is that devices use varying attributes, so it must be checked which is the right one. Functions defined in the DDF overwrite the defaults.

However, I strongly advice to add `"refresh.interval": 3600` as well for the battery, otherwise the device will be hammered with requests, draining the battery in no time.

**Comment by torandreroland** [comment]
@SwoopX: Sure! Added it. I noticed it prior to your comment in [state_battery_item](https://github.com/dresden-elektronik/deconz-rest-plugin/blob/master/devices/generic/items/state_battery_item.json), but I thought it anyways was beyond the scope of what I originally wanted to achieve and I didn't quite understand if it was necessary.

@Smanar: Not quite sure why I have problems with the percentage not being reported correctly as the device seems to be fairly Zigbee standard-compliant in this regard. Maybe my best suggestion is that the [standard divider ](https://github.com/dresden-elektronik/deconz-rest-plugin/blob/1d7f27ea34f3470998998fff8c28a2319817ce1e/power_configuration.cpp#L124) may not be used for DDF-devices, leading to the percentage to exceed the [upper allowed limit](https://github.com/dresden-elektronik/deconz-rest-plugin/blob/073b74f5f37604acce19e6995ae2d306a6550360/resource.cpp#L401).

**Comment by Smanar** [comment]
>Not quite sure why I have problems with the percentage not being reported correctly, as the device seems to be fairly "standard Zigbee"-compliant in this regard. Maybe my best suggestion is that the [standard divider ](https://github.com/dresden-elektronik/deconz-rest-plugin/blob/1d7f27ea34f3470998998fff8c28a2319817ce1e/power_configuration.cpp#L124)may not be used for DDF-devices

Don't worry you can not use it if you want

```
                {
                    "name": "config/battery",
                    "awake": true,
                    "parse": {"fn": "zcl", "ep": 0, "cl": "0x0001", "at": "0x0021", "eval": "Item.val = Attr.val / 2"},
                    "read": {"fn": "zcl", "ep": 0, "cl": "0x0001", "at": "0x0021"},
                    "refresh.interval": 3600
                },
```

If you use this code, the legacy code is bypassed, so the code on your link is not used, and it use instead eval": "Item.val = Attr.val / 2"

**Comment by torandreroland** [comment]
Sorry for being a bit unclear in my previous post. There is no doubt that this device needs a divider of 2. When putting in a new battery, the percentage is reported as 200, i.e. it must be divided with 2. However it was my understanding that the divider is standard set to 2 but for some models changed to 1 due to how [this code](https://github.com/dresden-elektronik/deconz-rest-plugin/blob/1d7f27ea34f3470998998fff8c28a2319817ce1e/power_configuration.cpp#L124:L148) was structured.

**Comment by Smanar** [comment]
Ha yes, I think too, I generally use /2 too.

Nothing to say about your PR, if it work for you, will be fine for me.
Just something to improve

`"ep": 0,`

Better to use the good endpoint, to prevent deconz use an exotic one when trying to determine it itself.

**Comment by torandreroland** [comment]
Thanks, corrected!

**Pull request merged**
