### PR TITLE
Schlage Connect Smart Deadbolt B3468 Support

### PR DESCRIPTION
**Pull request by ericvandamme**
Using the Danalock v3 code update as base, updated to support Schlage Connect Smart Deadbolt B3468.

Tested and working with my lock.

### CODE REVIEW

**Comment by Mimiix** [comment]
@ericvandamme is there a git issue on our repo that can be linked to this PR?

**Comment by ericvandamme** [comment]
No. I have been waiting for a template to base it off first. 

Should I create a device request?

**Comment by Mimiix** [comment]
@ericvandamme No need :) I was just wondering because might as well linked it then. 

Have to wait for Manup to merge anyway, that ain't my cup of tea. Thanks for the quick response!

**Comment by beccsjb** [comment]
Tested and working fine with my Schlage via phoscon. It does only get 1 entity though. No battery percentage etc, only lock/unlock.

**Comment by ericvandamme** [comment]
I do get the power percentage indicated in the REST client (and it is available in my Home Assistant install). I don't believe it is exposed in the Web UI.

**Comment by beccsjb** [comment]
I wish i could get it. I've added the lock into Phoscon as a light, as ive seen elsewhere. Is there anyway to be able to access what data the lock puts out? Can you view these details from Deconz interface?

**Comment by beccsjb** [comment]
image
I can see some data in deconz, albeit seemingly random data. There doesnt seem to be any translation of this into Home assistant though :(

**Pull request merged**
