### PR TITLE
Add DDF validator action

### PR DESCRIPTION
**Pull request by Zehir**
Adding the DDF validator action.

For now I keep the existing json linter because I don't validate generic files yet

### CODE REVIEW

**Comment by Zehir** [comment]
Before merging this PR could you merge #6820 and #6821 as they contain fix that are already detected by the validator. Thanks

**Comment by Zehir** [comment]
I removed the old json validator as the new validator read the content of each file to the json format is validated at the same time.

**Comment by manup** [comment]
Very cool, good work this should help a lot in catching common errors :+1:  I'm not too familiar with GitHub Actions development, is it possible to test it before merging into master branch?

**Comment by Zehir** [comment]
I test it on my fork, last time it's worked

**Comment by Zehir** [comment]
I test it on my fork, last time it's worked

And if for some reason he does not work you can still merge pulls requests, it's not blocking them

**Pull request closed without merging**
