### PR TITLE
Remove extra quotes from items values

### PR DESCRIPTION
**Pull request by Zehir**

### CODE REVIEW

**Comment by BabaIsYou** [comment]
Hi Zehir,

Don't really understand what is missing in `devices/tuya/_TZ3000_TS011F_PowerStrip.json` ?

**Comment by Zehir** [comment]
> Hi Zehir,
> 
> Don't really understand what is missing in `devices/tuya/_TZ3000_TS011F_PowerStrip.json` ?

Hello, It's because `config/configured` it not in generic files. Maybe it's only avaliable for alarm systems.

What do you think @manup ?

**Comment by BabaIsYou** [comment]
It’s used to send Tuya Magic Sequence because the PR made by @Smanar to include a new attribute for this purpose has not been merged for the moment.

**Comment by manup** [comment]
> Hello, It's because `config/configured` it not in generic files. Maybe it's only avaliable for alarm systems.

The `config/configured` is already in the C++ code, it's used by alarm systems, and the daylight sensor code.
We should add the respective `generic/items/config_configured_item.json` file.

**Comment by BabaIsYou** [comment]
> It’s used to send Tuya Magic Sequence because the PR made by @Smanar to include a new attribute for this purpose has not been merged for the moment (#6779) ... But will be soon ;-)

DDF corrected in PR #6865 after 6779 has been merged.

**Comment by Zehir** [comment]
Cleanup old PR

**Pull request closed without merging**
