### PR TITLE
DDF for SONOFF SNZB-02 multi sensor

### PR DESCRIPTION
**Pull request by Finne75**
[Link](https://sonoff.tech/product/smart-home-security/snzb-02/) to device.

### CODE REVIEW

**Comment by BabaIsYou** [comment]
From my point of vue the changes in bindings part are still too small. I use : 
`  "bindings": [
    {
      "bind": "unicast",
      "src.ep": 1,
      "dst.ep": 1,
      "cl": "0x0001",
      "report": [
        {
          "at": "0x0021",
          "dt": "0x20",
          "min": 60,
          "max": 3600,
          "change": "0x00000001"
        }
      ]
    },
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0405",
      "report": [
        {
          "at": "0x0000",
          "dt": "0x21",
          "min": 300,
          "max": 1800,
          "change": "0x000001F4"
        }
      ]
    },
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0402",
      "report": [
        {
          "at": "0x0000",
          "dt": "0x29",
          "min": 300,
          "max": 1800,
          "change": "0x00000064"
        }
     ]
    }
  ]`

**Comment by Finne75** [comment]
> From my point of vue the changes in bindings part are still too small. 

Makes sense, should be  in now.

**Comment by gregnebu** [comment]
Is it me or the DDF is not applied because the file misses ".json" extention ?

**Comment by BlauerPulli** [comment]
It is also not working for me.

**Comment by gregnebu** [comment]
> It is also not working for me.

You can rename the file to add « .json » extension and it’ll work fine

**Comment by BlauerPulli** [comment]
thx. i already did this as workaround. but would be nice to get rid of it in near future

**Comment by Finne75** [comment]
Done #6655 - don't know why this always happens...

**Pull request merged**
