### PR TITLE
Add support for Bitron smoke detector 902010/24

### PR DESCRIPTION
**Pull request by ma-ca**
Add Bitron smoke detector 902010/24

```
{
        "config": {
            "on": true,
            "reachable": true
        },
        "ep": 1,
        "etag": "90f0140d0c8eaa982b3e7675ec28ab14",
        "manufacturername": "Bitron Home",
        "modelid": "902010/24",
        "name": "Alarm 18",
        "state": {
            "alarm": false,
            "lastupdated": "none",
            "lowbattery": false,
            "tampered": false
        },
        "type": "ZHAAlarm",
        "uniqueid": "00:12:4b:00:07:7f:13:44-01-0500"
    },
```

### CODE REVIEW

**Comment by ma-ca** [comment]
You are right. I did read the `IAS Zone` cluster attributes and then searched for new devices again.

    curl http://xxx/api/xxx/sensors -X POST

Now the the smoke detector has the type `ZHAFire`.

```
{
        "config": {
            "on": true,
            "reachable": true
        },
        "ep": 1,
        "etag": "0471718322305776bbf1c851f66fac49",
        "manufacturername": "Bitron Home",
        "modelid": "902010/24",
        "name": "Fire 19",
        "state": {
            "fire": false,
            "lastupdated": "none",
            "lowbattery": false,
            "tampered": false
        },
        "type": "ZHAFire",
        "uniqueid": "00:12:4b:00:07:7f:13:44-01-0500"
    },
```

**Comment by ma-ca** [comment]
I did add the Bitron smoke detector 902010/24 to the whitelist.

**Comment by ma-ca** [comment]
Sorry for adding another commit to this PR that is not related to the smoke detector, but this was just a very small change to an existing line in the supported devices. 

I changed `902010/21A` to `902010/21` in order to also support `902010/21B`.

https://github.com/dresden-elektronik/deconz-rest-plugin/blob/96daf83a87e38be60978283bb375f3365be4ef2a/de_web_plugin.cpp#L108

**Comment by ma-ca** [comment]
@manup I would like to ask if there is anything missing or wrong in this PR that prevents from merging? I am asking because I would like to create some more PRs.

**Comment by manup** [comment]
> I am asking because I would like to create some more PRs.

I'm unsure, is the ZHAFire issue solved? Maybe prevent the ZHAAlarm to be created for certain model ids?

**Comment by ma-ca** [comment]
> is the ZHAFire issue solved?

Yes, I have whitelisted the model Id in this commit baad88403145339f120f792e02b0e4cfb6d98a5d in order to enforce the `ZHAFire` type even when the IAS_ZONE cluster attributes have not been read.

**Comment by ma-ca** [comment]
Add Bitron motion sensor 902010/22 to supported model Id list and whitelisted ZHAPresence type.

```
{
    "config": {
        "duration": 60,
        "on": true,
        "reachable": true
    },
    "ep": 1,
    "etag": "e2d1f50fca44ed1817e87a3455b18fed",
    "manufacturername": "Bitron Home",
    "modelid": "902010/22",
    "name": "Presence 23",
    "state": {
        "lastupdated": "2019-01-12T15:43:32",
        "lowbattery": false,
        "presence": false,
        "tampered": false
    },
    "swversion": "20150216",
    "type": "ZHAPresence",
    "uniqueid": "00:12:4b:00:01:ee:12:b3-01-0500"
}
```

**Comment by lyncker** [comment]
Iam just trying to pair a 902010/24 in the newest version of deconz, but it is not recognized. I did not find any information how to reset or set the device in the pairmode... pressing 20 seconds the button does not help... the sensor is not beeing found and the debug log does not show any information  ... 
maybe you can help me how to handle such a device?

**Comment by ma-ca** [comment]
You need to press the button 10 seconds, not 20 seconds.

https://manuals.smabit.eu/len/av2010_24.html#c

> Hold the function button on the top of the sensor for about 10 seconds until the red LED illuminates briefly once.
During the search, the LED will light red once every 10 seconds. If the LED flashes 2 times, the device has successfully logged on to your Smart Home system.

**Comment by lyncker** [comment]
perfect , thanks... that worked ...:)

**Pull request merged**
