### PR TITLE
DDF for Bosch Light/shutter control II

### LINKED ISSUE #7661: Bosch Light/shutter control unit II
### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for my device

### Product name

Light/shutter control unit II

### Manufacturer

Bosch

### Model identifier

RBSH-MMS-ZB-EU

This device is a bit special as it has a "split personality": it can function as 2x switch (i.e. for controlling an on/off light) OR as a window covering device. For the latter it must be configured, which can be done  using the Bosch Gateway & proprietary app but not through deconz (yet?)

The magic seems to be in the cluster #FCA0, where some attributes must be set accordingly. Unfortunately these cluster attributes are not available in deconz. A reference to these attributes can be found in a discussion for ZHA [here](https://github.com/zigpy/zha-device-handlers/issues/2518)

BTW I was able to pair this device through the "pair with install code" method in the REST API.

### Device type to add

Other

### Node info

Node_Info

### Endpoints and clusters

Clusters_overview

### Basic

Basic_cluster

### Simple Metering
Cluster_Simple_metering

### Electrical Measurement
Cluster_electrical_measurement_1
Cluster_electrical_measurement_2
Cluster_electrical_measurement_3
Cluster_electrical_measurement_4

### Window covering
Cluster_window_covering_1
Cluster_window_covering_2
Cluster_window_covering_3

### Diagnostics
Cluster_Diagnostics

### PR DESCRIPTION
**Pull request by SwoopX**
Interesting device. Making an educated guess here, especially on the switch resource and the button map. Would be great if it could be tested upfront.

Closes #7661

### CODE REVIEW

**Comment by Smanar** [comment]
Hello, you are sure for
```
        <attribute id="0x0000" name="Device mode" type="enum8" mfcode="0x1209" access="rw" required="m"></attribute>
        <attribute id="0x0001" name="Switch type" type="enum8" mfcode="0x1209" access="rw" required="m"></attribute>
```

According that I have see on the link gived by the user, the attribute 0x0000 is the device mode yes, but need to change the value to chnage it, so for me it's more something like

```
        <attribute id="0x0000" type="enum8" name="shutter mode" access="rw" required="o" mfcode="0x1209">
            <value name="xxxx" value="0x00"></value>
            <value name="shutter" value="0x01"></value>
        </attribute>
```

**Comment by SwoopX** [comment]
@Smanar ah, forgot the values. Thanks for poking me, will add them later 👍🏻

**Comment by manup** [comment]
Ready to merge? :)

**Comment by SwoopX** [comment]
> Ready to merge? :)

I'd say so 🙂

**Pull request merged**
