### PR TITLE
Various bug fixes and more eCozy

### PR DESCRIPTION
**Pull request by ebaauw**
## Enhancements
- Poll _Time_ cluster every 6 hours (instead of every minute), in line with eCozy gateway.

## Bug Fixes
- Don't reset `config.duration` for Aqara motion sensor on load.  See #1366, #1395, #1468.  All closed by the bot, but never resolved.  Issue popped up again on Discord, #restapi-issues channel.
- Sometimes ZHAThermostat attributes wouldn't be updated, see #technical-talk channel on Discord.

### CODE REVIEW

**Comment by popy2k14** [comment]
@ebaauw 
Hi Erik.

Does the change regarding aqara motion sensors mean that the react faster after they has been detect motion for the first time?

Thank you

**Comment by ebaauw** [comment]
The change is to accommodate the hardware mod, see the linked issues.

**Comment by popy2k14** [comment]
Sorry to bother you again. English is not my native language.

Do I have to Hardware mod the devices to get lower detection intervals with v81?

I have v81 installed and the detection pause is ~60s on my aqara motion sensors (no hw mod).

Thx

**Comment by ebaauw** [comment]
The change is for the hardware mod to work with deCONZ.

**Comment by popy2k14** [comment]
ok, thanks now its clear to me!
Will mod my sensors to get faster updates from the sensor.

Do i have to configure the delay to 5 seconds on every deconz start (like described here #1671) or is this also fixed in v2.05.81?
(config will be saved and survives an restart of deconz)

thx a lot for your help

**Comment by popy2k14** [comment]
@ebaauw 
Hey Erik, is the config for the delay after every restart of deconz needed for the hack to work or not?

thx

**Comment by popy2k14** [comment]
Just want to let you know.
Have modded 4x xiaomi sensors and set the duration to 5 seconds.
After:

`sudo systemctl stop deconz`

and

`sudo systemctl start deconz`

the duration is set to 5 seconds. Seems that deconz is not reseting this setting.

thx a lot

**Pull request merged**
