### PR TITLE
ResourceItems for device firmware

### PR DESCRIPTION
**Pull request by ebaauw**
To support automated checking if newer firmware is available for a device, the API needs to expose the firmware parameters, _Manufacturer Code_, _Image Type_, and _File Version_.  This PR adds support for resource items `cap/otau/manufacturer_code`, `cap/otau/image_type`, and `cap/otau/file_version`, to be included in DDFs of devices that support OTA firmware upgrades.  These items are exposed as a separate map under `capabilities` on `lights` and `sensors` resources:
```
  "capabilities": {
    "otau": {
      "file_version": 16786690,
      "image_type": 276,
      "manufacturer_code": 4107
    }
  }
```
They're also included as separate map in the `capabilities` websocket notifications.

Note that the items are populated from the _Query Next Image Request_, rather than from the optional (!) _OTAU_ cluster attributes.  `cap/otau/manufacturer_code ` sends an _Image Notify_ on `read`, triggering the _Query Next Image Request_, which also populates table in the _OTA Update_ panel in the GUI.

This PR adds the new items to the DDFs for Hue devices and for some others that I had handy.

TODO:
- Add these attributes to devices (exposed by legacy code) on receipt of the _Query Next Image Request_.

TODO on the longer term:
- Define these attributes (only) on the device, instead of on each sub-device.
- Deprecate the existing `attr/otaversion`(based on the OTAU cluster attribute),  in favour of `cap/otau/fileversion`?  It's used only as `matchexpr` in the DDF for the Trådfri on/off switch (after the attributes are defined on device level, and we've made sure they's persisted in the database).
- Add these items to other devices supporting OTAU firmware upgrades.
- Refactor `rest_lights.cpp` and `rest_sensors.cpp` to build the maps dynamically (cf. websocket notifications for `sensors`) rather than listing all items explicitly (see #7979).

### CODE REVIEW

**Comment by ebaauw** [comment]
Not sure why the validation checks fail.  These changes pass `ddf-tool validate` locally:
```
$ ddf-tools validate -d devices
- Using validator version 2.31.1
✔ Found 662 files to validate
Skipping file devices/danalock/danalock_v3.json because it has the ddfvalidate option set to false
Skipping file devices/legrand/cable_outlet.json because it has the ddfvalidate option set to false
✔ Loaded 270 generic files and 390 DDF files from disk
✔ No errors found in 270 generic files
✔ No errors found in 390 ddf files
```

**Comment by Zehir** [comment]
> Not sure why the validation checks fail. These changes pass `ddf-tool validate` locally:
> 
> ```
> $ ddf-tools validate -d devices
> - Using validator version 2.31.1
> ✔ Found 662 files to validate
> Skipping file devices/danalock/danalock_v3.json because it has the ddfvalidate option set to false
> Skipping file devices/legrand/cable_outlet.json because it has the ddfvalidate option set to false
> ✔ Loaded 270 generic files and 390 DDF files from disk
> ✔ No errors found in 270 generic files
> ✔ No errors found in 390 ddf files
> ```

The issue was because the bundler was not able to find the generic file for `attr/otau/imagetype` he was expecting the location `generic/items/attr_otau_imagetype_item.json` Updated in https://github.com/dresden-elektronik/deconz-rest-plugin/pull/7961/commits/c672d71219d1d09cccdb9d3b4aec5c69800d3161

**Comment by ebaauw** [comment]
@manup, can we merge this?

I want to wait with creating the attributes in legacy code, until we can handle them at the device level in DDFs as well (rather than at each subdevice).

**Comment by Jagohu** [comment]
Please not this thread: https://forum.phoscon.de/t/phillips-hue-motion-sensor-sml001-doesnt-update-brightness/5815/2

The SML001 shows 0 as lightlevel, 1 as lux - all the time, all of them.

**Pull request merged**
