### PR TITLE
DDF for Aqara Smart Radiator Thermostat E1

### PR DESCRIPTION
**Pull request by Smanar**
Aqara but use Xiaomi manufacture number.

With the @cameo77 help.see https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6351

Still missing some feature like preset, but need another PR was merged to be available with DDF.

### CODE REVIEW

**Comment by manup** [comment]
> but need another PR was merged to be available with DDF.

@Smanar which PR is needed for this to work?

Since the general.xml has changed quite a bit, we now have a merge conflict.

**Comment by Smanar** [comment]
@manup confilct is solved.
The PR needed for config/preset is the "problematic" one, the one used to have support for tuya TRV.

Do you want a small PR just for config/preset ? If you don't think it can be  critic one ?

**Comment by manup** [comment]
Ah right I think it's https://github.com/dresden-elektronik/deconz-rest-plugin/pull/6054
And discussion in https://github.com/dresden-elektronik/deconz-rest-plugin-v2/issues/13

@Smanar  @SwoopX any thoughts on this?

The way I see it is we have two options:

1. Merge it now to be able to merge related Tuya TRV devices (which are on hold for a uncomfortable long time).
   With the danger to later smooth out items, maybe involving some trouble.
2. Work out the items asap and adapt and merge the PRs then.

To be honest while I'm usually in camp Nr. 2, since the PRs are on hold for so long we might bite the sour apple to get things running and work it our over time.

**Comment by Smanar** [comment]
@manup you are talking about https://github.com/dresden-elektronik/deconz-rest-plugin/pull/6054 ?

If yes, no, not possible to merge it now, too much PR in waiting list, and the PR is too old, need a more recent "master" branch.
Better to merge the most no critic PR we can first, so this one (without the config/preset feature)

The tuya PR is waiting since the 14 may, it can wait some more weeks.

**Comment by manup** [comment]
Ah ok thanks, this helps to understand :) Then I'd propose you add the TRV PRs which can be already be safely merged to the v2.20.0-beta milestone.

I've added #6054 to https://github.com/dresden-elektronik/deconz-rest-plugin/milestone/39 so we can review it later on.

**Comment by Smanar** [comment]
Yeah, I know lot of users are waiting for tuya TRV support but too dangerous on this deconz version.
This PR is safe, just a DDF and some xml addition, can use the v2.20.0-beta milestone . The device can work without config/preset for some time.

**Comment by SwoopX** [comment]
@manup I'm easy either way for the reasons you already gave. However, I guess the dice is already cast as Smanar's feedback indicates 🙂

**Pull request merged**
