### PR TITLE
DDF for LIDL Livarno window blinds (Tuya)

### PR DESCRIPTION
**Pull request by chbndrhnns**
Product name: LIVARNO home Automatik-Verdunkelungsrollo
Manufacturer: _TZB000_42ha4rsc
Model identifier: TS030F
Device type : Please remove all unrelated device types.
Other: Blinds

Discussion: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/7197

### CODE REVIEW

**Comment by Smanar** [comment]
There is a problem with this PR ?

**Comment by manup** [comment]
> There is a problem with this PR ?

From a quick look the "fn" needs to be adapted to the specif ones like "zcl:attr". For some reason Github doesn't show the re-run checks button here so the output is a bit noisy.

**Comment by Smanar** [comment]
@chbndrhnns  can you replace all `"fn": "zcl"` by "fn": "zcl:attr" ?

**Comment by chbndrhnns** [comment]
Rebased the branch and changes applied as per @Smanar 's suggestions

**Comment by Smanar** [comment]
Nice thx, and this time the check have worked.

**Pull request merged**
