### PR TITLE
Added Magic Cube T1 Pro (lumi.remote.cagl02)

### PR DESCRIPTION
**Pull request by fhinder**
I added the new Magic Cube T1 Pro (lumi.remote.cagl02).
The configuration is working with the magic cube and with the new Aqara Cube T1 Pro.

Please merge and modify to tyour coding guideleins, which I don't know.
This should solve the issues:
 #5732 , #6585, #6580
 and is related to: #5838 

Thanks a lot.

### CODE REVIEW

**Comment by manup** [comment]
@SwoopX in my dusty memory I think there was some work to handle these via DDF? Should we this C++ extension or go the DDF way here?

**Comment by SwoopX** [comment]
@manup I got this one covered by my Cube PR, so this one can be closed and seen as confirmation it's working.

**Comment by manup** [comment]
Looks like not to be working for @fhinder yet? As mentioned in the issue would be really cool to work it out, perhaps for v2.20.1-beta in a week.

**Comment by fhinder** [comment]
It is working, I did a mistake, see details in here:
https://github.com/dresden-elektronik/deconz-rest-plugin/pull/5838#issuecomment-1376217918

**Pull request closed without merging**
