### PR TITLE
FIX/DDF add support by DDF for the Aqara Single Switch Module T1

### PR DESCRIPTION
**Pull request by Smanar**
It seem this device don't use cluster 0x0b04 and 0x0702 (legacy code), but the Xiaomi one (with the DDF core now)
See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4328

### CODE REVIEW

**Comment by manup** [comment]
@Smanar  and @SwoopX DDF looks good to me, ready to merge? :)

**Comment by Smanar** [comment]
For me yes, I have removed the line

`"matchexpr": "R.endpoints.indexOf(0x15) + R.endpoints.indexOf(0x1F) >= 0 ? true : false;",`

I m not sure of that but @flopp999 have old and new version working with the DDF.

**Comment by manup** [comment]
`R.endpoints.indexOf(0x15) + R.endpoints.indexOf(0x1F)  >= 0 ? true : false;`  is also rather weird, as `indexOf()` returnes `-1` if the value isn't in the array, e.g. `-1 + 0` would return `false` here.

maybe the intention was to check if one of the endpoints was present?
```
(R.endpoints.indexOf(0x15) !== -1  || R.endpoints.indexOf(0x1F) !== -1) ? true : false;
```

Or simplified:

```
(R.endpoints.indexOf(0x15) !== -1  || R.endpoints.indexOf(0x1F) !== -1);
```

**Comment by Smanar** [comment]
>maybe the intention was to check if one of the endpoints was present?

Both, but as I have said, I have never see version without thoses endpoint yet, so for me not usefull

**Comment by SwoopX** [comment]
Such a check is only relevant anyway, if there's devices with different firmwares out there exposing different endpoints. This is apparently not the case, therefore I vouched for removing the `matchexpr` stanza.

I'd be prepared that people will lose their power and consumption sensors when updating to a new deconz version containing the DDF, unless they reset and repair the device with a current coordinator firmware. I'd suggest to make such a note prominent in the release notes.

Other than that, this DDF should be good to go.

**Comment by SwoopX** [comment]
> > I'd be prepared that people will lose their power and consumption sensors when updating to a new deconz version containing the DDF, unless they reset and repair the device with a current coordinator firmware. I'd suggest to make such a note prominent in the release notes.
> 
> Hm but why is this, if it works with the legacy code can't the DDF use the same? (I don't understand why it needs to be repaired)

Well, this is that "Xiaomi thingy" with the node descriptor response... Eventually, the device exposes different stuff and behaves differently. I don't have the device here and cannot check if clusters are "just hidden" but generally accessible.

**Comment by manup** [comment]
Oh my, classical Xiaomi :D yeah I guess then we can only note that in the changelog. I just have the H1 double rocker here for testing perhaps it has the same weirdness.

**Comment by flopp999** [comment]
I can delete one old(3 years) and one new if it needs to be checked.
Just tell me what to do and what to check and send to you.

**Comment by manup** [comment]
Would be interesting to know if your device still works with the DDF, without delete / repair.
If it doesn't we should have a closer look how it looks, e.g. the cluster list etc. perhaps we can derive a second DDF which only targets the "old" representation so a repair isn't needed.

I'll merge this PR for the beta with the note in the changelog.

**Pull request merged**
