### PR TITLE
add another manufacturername  to  _TZ3000_TS044_4gang_remote.json

### PR DESCRIPTION
**Pull request by pavime**
Add another manufacturername to the config

### CODE REVIEW

**Comment by pavime** [comment]
Hi @sinus61 
I add the change @manup suggest in the #6787 pr
Thank you

**Comment by manup** [comment]
@pavime  @Smanar It looks like the "_TZ3000_wkai4ga5" is already in `button_maps.json` and we can close this PR?

**Comment by Smanar** [comment]
Yep, sorry @pavime but another PR was merged with the same device before this one.
The device was in DDF "_TZ3000_TS044_4gang_remote.json" and in the button_maps.json.

**Comment by pavime** [comment]
OK, we can close it
Thank you

**Pull request closed without merging**
