### PR TITLE
[subdevice] Door Lock

### PR DESCRIPTION
**Pull request by Zehir**
Part 11 of https://github.com/dresden-elektronik/deconz-rest-plugin/pull/7155

### CODE REVIEW

**Comment by Zehir** [comment]
There is door lock in `/lights` and `/sensors`, maybe there is a better way to do it ?

**Comment by manup** [comment]
Unfortunately "Door Lock" is another lightoid like the Danalock V3, not pretty... I guess this can only be cleaned up with the move to `/devices` endpoint where light/sensor stuff doesn't really exist other than the reference to the "old" API.

**Comment by manup** [comment]
I can't find any reference to "Door lock controller" or TYPE_DOOR_LOCK_CONTROLLER.

**Comment by Zehir** [comment]
So whats the plan for this PR ? You want to create a new `restapi` option to have `/devices` ?

**Comment by manup** [comment]
> So whats the plan for this PR ? You want to create a new `restapi` option to have `/devices` ?

No the `restapi` is only "used" within the `/devices` context, in reality right now it isn't used at all :)

If I remember correctly the idea behind this is to map to the old API, this isn't done yet but might be handy once the REST-API itself gets refactored with proper commands...

The PR looks fine to me, except the "Door lock controller" as I can't find any device which uses this?

**Comment by Zehir** [comment]
@manup There is no `Door lock controller` DDF but there is a subdevices for it (`door_lock_controller.json`) so I added the constants but we can remove both if you prefer

**Comment by manup** [comment]
Looks like it comes from commit: https://github.com/dresden-elektronik/deconz-rest-plugin/commit/7403eb8857c207ff4c9943a6ac08b34f9419c069

@Smanar do we still need it, there don't seem to be devices for it? If no than it can be removed.

**Comment by Smanar** [comment]
There is, for exemple https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3973
But can use a TYPE_DOOR_LOCK

**Comment by Zehir** [comment]
What the difference between TYPE_DOOR_LOCK and TYPE_DOOR_LOCK_CONTROLLER ?

**Comment by Smanar** [comment]
When a brand create a device, it choose the type they want, for tuya all devices are plugs.

**Comment by manup** [comment]
Okay, not sure if I understand everything but I guess it's fine to merge for now :)

**Pull request merged**
