### PR TITLE
Fix Zigbee Dual Curtain Switch _TZ3000_j1xl73iw (TS130F)

### PR DESCRIPTION
**Pull request by Xyaren**
Followup to #3757

I know that PRs regarding devices are not merged if they are not in DDF format, but don't stop reading here.
The logic of reversing the percentage like it is implemented is currently **not possible** with the DDF specification.

If that changes I am happy to add and test a DDF for the device.

### CODE REVIEW

**Comment by Smanar** [comment]
>If that changes I am happy to add and test a DDF for the device.


It's WIP, need someone to test it https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5710#issuecomment-1107875449

**Comment by Smanar** [comment]
The code is available, you have the procedure to test it on the link.
After that you just need to create a DDF for your device, I can help for that too, I just need a skeleton/base for that.

**Comment by Finne75** [comment]
Just want to say that I have TS130F device (_TZ3000_fccpjz5z, so not exactly the one referred to in this PR) which works just fine, including in home assistant. When I first integrated the device, I had to create a template cover in HA to fix the "reverse" issue, but this was not necessary anymore after a HA core update (I do not remember exactly, which one).

I say this to raise caution that nothing is fixed or even broken which currently works well, at least for my TS130F. If you are all aware of this, please ignore :)

**Comment by Xyaren** [comment]
@Smanar 
So I tried your branch and got it to kind of working with the following DDF:

```json
{
  "schema": "devcap1.schema.json",
  "manufacturername": "_TZ3000_j1xl73iw",
  "modelid": "TS130F",
  "product": "TS130F",
  "sleeper": false,
  "status": "Gold",
  "path": "/devices/ts130f.json",
  "subdevices": [
    {
      "type": "$TYPE_WINDOW_COVERING_DEVICE",
      "restapi": "/lights",
      "uuid": [
        "$address.ext",
        "0x01"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "state/lift",
          "refresh.interval": 300,
          "parse": {
            "at": "0x0008",
            "cl": "0x0102",
            "ep": 0,
            "eval": "Item.val = (100 - Attr.val);",
            "fn": "zcl",
            "reverse": true
          },
          "default": 0
        },
        {
          "name": "state/open",
          "parse": {
            "at": "0x0008",
            "cl": "0x0102",
            "eval": "Item.val = Attr.val == 100",
            "fn": "zcl"
          }
        },
        {
          "name": "state/reachable"
        }
      ]
    },
    {
      "type": "$TYPE_WINDOW_COVERING_DEVICE",
      "restapi": "/lights",
      "uuid": [
        "$address.ext",
        "0x02"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "state/lift",
          "refresh.interval": 300,
          "parse": {
            "at": "0x0008",
            "cl": "0x0102",
            "ep": 0,
            "eval": "Item.val = (100 - Attr.val);",
            "fn": "zcl",
            "reverse": true
          },
          "default": 0
        },
        {
          "name": "state/open",
          "parse": {
            "at": "0x0008",
            "cl": "0x0102",
            "eval": "Item.val = Attr.val == 100",
            "fn": "zcl"
          }
        },
        {
          "name": "state/reachable"
        }
      ]
    }
  ],
  "bindings": [
    {
      "bind": "unicast",
      "src.ep": 2,
      "cl": "0x0102",
      "report": [
        {
          "at": "0x0008",
          "dt": "0x20",
          "min": 0,
          "max": 0
        }
      ]
    },
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0102",
      "report": [
        {
          "at": "0x0008",
          "dt": "0x20",
          "min": 0,
          "max": 0
        }
      ]
    }
  ]
}
```

So the following works:
- Opening via "Open"
- Closing via "Close"
- Setting the Percentage

What does **not work** now:
- Stop Button

When calling the API I get the following error:
`pydeconz.errors.BridgeBusy: 901 /lights/7/state/stop Internal error, 951`

So this is no a feasable solution right now.

**Comment by Smanar** [comment]
>So this is no a feasable solution right now.

No, but I don't have full device to test code, it's for that I need you.
If you want to continue test here https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5710 to not polute your PR.

Have updated the code, you can update it just with

```
cd deconz-rest-plugin
git pull
qmake && make -j2
sudo cp ../libde_rest_plugin.so /usr/share/deCONZ/plugins
```

The "stop" request is working now, but I don't understand why you create 2 light entry on your json ?

**Comment by Xyaren** [comment]
> The "stop" request is working now (I think I can listen a "clic" when making the request), but I don't understand why you create 2 light entry on your json ?

I'll have to remove that. 
My device has no light at all, so that can be removed.

**Comment by Smanar** [comment]
No I mean "light entries", it s covering, but you have 2
```

"subdevices": [
    {
      "type": "$TYPE_WINDOW_COVERING_DEVICE",
      "restapi": "/lights",
      "uuid": [
        "$address.ext",
        "0x01"
      ],
```

```
      "type": "$TYPE_WINDOW_COVERING_DEVICE",
      "restapi": "/lights",
      "uuid": [
        "$address.ext",
        "0x02"
      ],
```

**Comment by Xyaren** [comment]
Oh, yeah it does have two clusters.
I can control two individual covers with one device.

**Comment by Smanar** [comment]
Ha yeah, so forget that I m saying. All seem fine in your DDF.
If you can say me if the "stop" request is working now ?

**Comment by Xyaren** [comment]
Stop command is doing something now yes. 
Altough the Experience is not as good as with the cpp change of this PR.
I get frequent artifacts, like the shutter moving back to the previous position after it has moved, or it stuttering when using the stop button.
Or for example it is 90% open, and I press the "Open/Up" button it opens to 100% then  goes back down a bit.

This did not happen with code change from this PR.

**Comment by Smanar** [comment]
BTW, thx for your test. I will stop to pollute your issue ^^
I will copy paste your return on the other issue, to check if it's same or to try to have some logs because I don't see the issue.

**Comment by manup** [comment]
Hi, should this PR be included in the next beta or is it work in progress?

**Comment by Smanar** [comment]
Sorry, my fault, have polluted his PR, discution have nothing to see with his PR.
For me his PR is finished.

**Comment by Xyaren** [comment]
I'm fine with this PR beeing merged. I have been testing it for the last weeks and it performs as expected.

**Comment by manup** [comment]
Only in very rare cases like this one since the PR simple and doesn't hurdle the transition to DDF once possible.  
More complex code needs the DDF treatment :)

**Comment by Xyaren** [comment]
> Only in very rare cases like this one since the PR simple and doesn't hurdle the transition to DDF once possible. More complex code needs the DDF treatment :)

Thanks !
I would love this to be merged, so I can move away from my custom builds 😁

**Pull request merged**
