### PR TITLE
Add DDF for a Tuya TRV _TZE200_hhrtiq0x , and prepare the code to use it

### PR DESCRIPTION
**Pull request by Smanar**
So with the @TheHaf 's help, the first working tuya trv with DDF

The code is working but still have 2 issues :
- the valve position is not working, but for the moment the tuya return is not visible in log (so perhaps not supported by this device)
~~- Not possible to use "script" for "write" part, only "eval" is working.~~

If you want to help there is a version with more debug lines on the issue https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5831

### CODE REVIEW

**Comment by Smanar** [comment]
For the moment I m the only one that use it for tuya so I m using

`StateChange change2(StateChange::StateCallFunction, SC_WriteZclAttribute, task.req.dstEndpoint());`

For classic device the normal command is

`StateChange change2(StateChange::StateWaitSync, SC_WriteZclAttribute, task.req.dstEndpoint());`

But don't work for tuya stuff.

**Comment by TheHaf** [comment]
Is there anything that keeps this PR from being merged at the moment that I can help with?

**Comment by EmJay276** [comment]
@Smanar can I do anything here? Test with Tuya devices for example?

**Comment by Smanar** [comment]
IDK, the PR can actually work, it probably don't respect deconz rules, but I need to know what is not good, to correct them.

But I have a good new, Mimix have mentionned there is too much PR in waiting list, so I think someone will take in care all of them, and close/answer/validate them

**Comment by Mimiix** [comment]
@manup this one is blocking a lot of device supports.

**Comment by containerguy** [comment]
Winter season is coming fast. Would be great to get the tuya devices finally into deconz.

**Comment by Smanar** [comment]
Ok so the code was updated here https://github.com/dresden-elektronik/deconz-rest-plugin/commit/f17ab0097bf01d613b2303d380fcd68d1d0735e4#diff-7548d412985c02a5cf5b188c22b61937c468e2ce2914e8ee4e8c13cd28e0750b
 
New version WIP

**Comment by SwoopX** [comment]
@Smanar I'm afraid the whole PR has some good potential to break stuff ans as I see it, there might also be merge conflicts. Wondering who this is not reported...

Anyway, there's so much unnecessary and outdated stuff in it, I'd rather recommend to close this one down and come up with a fresh and clean new one.

**Comment by Smanar** [comment]
Nothing repoeted perhaps because it was updated with last master.

Clean version here https://github.com/dresden-elektronik/deconz-rest-plugin/pull/6674

**Comment by Smanar** [comment]
I know the winter saison is close to finish, but if someone with a Tuya TRV can test the code ? I can make a DDF for unsupported TRV if needed.

**Comment by Mimiix** [comment]
Locking this one, please proceed in #6674

**Pull request closed without merging**
