### PR TITLE
DDF for Eva Powermeter

### LINKED ISSUE #6343: EVA Han Powermeter
## Device

- Product name: The device name as shown on the product or package.
- Manufacturer: EVA
- Model identifier: Meter REader
- Device type : Please remove all unrelated device types. 
  - Sensor

## Screenshots

image
image
image
image
image
image

Another user posted a request for this device here
https://forum.phoscon.de/t/eva-metering-han-powermeeter/1941

Link to device:
https://shop.evasmart.no/produkt/smarthus/maleravleser

### PR DESCRIPTION
**Pull request by sevrinrobstad**
Fix #6343 .

### CODE REVIEW

**Comment by BabaIsYou** [comment]
Hi,
To avoid some isuues it's preferable that `refresh.interval` would be higher than `max` in binds, as a last resort if bind failed. 
And these values (same for  `default": 0`) are already into generic items for "power", "current" and "voltage" then useless into the DDF.

**Comment by sevrinrobstad** [comment]
> Hi, To avoid some isuues it's preferable that `refresh.interval` would be higher than `max` in binds, as a last resort if bind failed. And these values (same for `default": 0`) are already into generic items for "power", "current" and "voltage" then useless into the DDF.

OK so just remove the refresh.interval and default:0 all together?

**Comment by BabaIsYou** [comment]
Exactly, or just default and put a higher value for refresh like 360 for instance ;-)

**Comment by sevrinrobstad** [comment]
Updated.

**Pull request merged**
