### PR TITLE
DDF for Tuya 3gang modelid TS0043 (_TZ3000_w8jwkczz)

### PR DESCRIPTION
**Pull request by b2un0**
add also _TZ3000_w8jwkczz for TS0043

### CODE REVIEW

**Comment by b2un0** [comment]
with this PR the following  switch works

https://expo.tuya.com/product/1049042

**Comment by Smanar** [comment]
Hello there is already a DDF for 3 tuya 3 gangs https://github.com/dresden-elektronik/deconz-rest-plugin/blob/master/devices/tuya/_TZ3000_gbm10jnj_3gang_remote.json

Can you look if you can mix the 2 DDF using

```
  "manufacturername": ["_TZ3000_gbm10jnj", "_TZ3000_w8jwkczz "],
  "modelid": ["TS0043", "TS0043"],
```

**Comment by b2un0** [comment]
@Smanar  works, thanks.

doesn't know that arrays are possible at this point.

**Comment by Smanar** [comment]
No problem, realy few documentation, ...., and realy too mich tuya clone.

**Comment by Ombrelin** [comment]
What is missing to merge this PR ? Ho could I help ?

**Comment by Smanar** [comment]
Nothing.
Long story, but PR was locked since long time, If I m right small PR like this one will be valided just after the newt deconz version that solve issues on 2.19.X branch

**Comment by manup** [comment]
Would like to merge it in v2.20.0-beta can you please resolve the merge conflicts?

**Pull request merged**
