### PR TITLE
Initial support for Netvox Z809A smart plug

### PR DESCRIPTION
**Pull request by clockbrain**
As per #1998 

Based on code for other smart plugs as best I can tell. Works for on/off but doesn't create any sensors for power monitoring. Any suggestions on where to start with that?

### CODE REVIEW

**Comment by Smanar** [comment]
IDK, I have do exacly like you, for legrand plug, I don't see what is missing.
Yo check if your code is working, for exemple, use deconz, go on cluster 0B04, attribute 050B, double click and check if attribute reporting have been set by your code.

Perhpas with enabling log ?

**Comment by clockbrain** [comment]
Thanks for the suggestions but no luck. Reporting for attribute 050B is configured but not with the values from bindings.cpp so maybe just defaults for the device.

Log didn't help. Might have to include some additional logging but I don't understand the code so could take a while.

Yes, I did remove and re-pair the smart plug after patching the code.

**Comment by clockbrain** [comment]
I couldn't find that line anywhere in the code so couldn't try that.

I did however notice that the Z809A is returning a device id of 0x0009 DEV_ID_MAINS_POWER_OUTLET instead of expected 0x0051 DEV_ID_SMART_PLUG.

Tried changing everywhere in the code that referenced DEV_ID_SMART_PLUG to also accept DEV_ID_MAINS_POWER_OUTLET and also tried to override the device type with 0x0051 but still nothing.

**Comment by Smanar** [comment]
This line is still good ?
>const quint64 netvoxMacPrefix     = 0x00137a0000000000ULL;

**Comment by clockbrain** [comment]
Yes, that line in the code is still good and the prefix matches my netvox plug mac. The plug works fine for on/off so I'm assuming all the basics are ok, I just need to find where in the code it is failing the test to set up the additional sensors for voltage etc.

I did also try the VENDOR_NONE you suggested above but that didn't make any difference.

I've poked around quite a bit and thrown semi-random debug statements in but I don't really know what I am looking for. Any clues where to focus my efforts? I'm thinking its most likely somewhere in de_web_plugin.cpp or maybe light_node.cpp. I did try bypassing the endswith "Power" test in https://github.com/dresden-elektronik/deconz-rest-plugin/blob/9ed7c7f46fd78eab7473fc6ffc67f60cc748765d/de_web_plugin.cpp#L4708 but no luck.

By any chance would you have a log extract from a different brand of smart plug that does work that I could compare with? I don't have any other supported smart plugs that I can experiment on.

**Comment by ebaauw** [comment]
> The plug works fine for on/off so I'm assuming all the basics are ok, I just need to find where in the code it is failing the test to set up the additional sensors for voltage etc.

There’s no such thing as “the basics”.  There’s different logic for creating `/lights` resources vs `/sensors` resources.  You need to whitelist the plug twice: `/lights` resources are whitelisted by device type and receiver on when idle; `/sensors` resources are whitelisted by manufacturer, model, and mac address prefix.

**Comment by Smanar** [comment]
But I realy don't see where he can have forget a whitelist !

@clockbrain Try to add debug line (or just take a look on actual on) in the function
>void DeRestPluginPrivate::addSensorNode(const deCONZ::Node *node, const deCONZ::NodeEvent *event)

Are you reaching this function ?

**Comment by clockbrain** [comment]
Yes I am getting to the addSensorNode function. It does execute this line https://github.com/dresden-elektronik/deconz-rest-plugin/blob/9ed7c7f46fd78eab7473fc6ffc67f60cc748765d/de_web_plugin.cpp#L4014 which seems promising but fails the device supported test here because modelId is empty 
https://github.com/dresden-elektronik/deconz-rest-plugin/blob/9ed7c7f46fd78eab7473fc6ffc67f60cc748765d/de_web_plugin.cpp#L4111
I assume that test is checking against supportedDevices[] although I can't find the actual function that does that. My PR already includes the Netvox entry in that array.

So now to figure out why modelId isn't set. I'm guessing it should be grabbing it from the light here https://github.com/dresden-elektronik/deconz-rest-plugin/blob/9ed7c7f46fd78eab7473fc6ffc67f60cc748765d/de_web_plugin.cpp#L4106

I will add some more debug lines around there to see whats going on.

A further thought .... I noticed when pairing the Z809A smart plug that it brings up the manufacturer name in Phoscon then the model appears a second or two later. Is that normal? Maybe when the add sensor node function tries to grab the model it hasn't been loaded into the light node yet?

**Comment by clockbrain** [comment]
Some progress - I had a mistake in my model and some dodgy debug statements. When I fixed those it does pass as a supported model. However, it still fails on the first go under /sensors/new when the modelId is empty but works on the next try just listing the lights.

Log extract:
```
23:01:55:365 LightNode 2: Smart plug 2 added
23:01:55:365 ~Resource() /lights 0x7eff8780
23:01:55:365 Working with modelId 
23:01:55:365 Device not supported
23:01:55:365 DB pushZdpDescriptorDb()
23:01:55:366 DB UPDATE device_descriptors SET data = x'010401090000090000030004000500060015000207040b050b00', timestamp = 1572440515 WHERE device_id = (SELECT id FROM devices WHERE mac = '00:13:7a:00:00:04:0a:4b') AND endpoint = 1 AND type = 4
23:01:55:366 DB INSERT INTO device_descriptors (device_id, endpoint, type, data, timestamp) SELECT id, 1, 4, x'010401090000090000030004000500060015000207040b050b00', 1572440515 FROM devices WHERE mac = '00:13:7a:00:00:04:0a:4b'
23:01:55:380 don't close database yet, keep open for 900 seconds
23:01:55:381 read attributes of 0x00137A0000040A4B cluster: 0x0000: [ 23:01:55:381 0x0005 23:01:55:381 ]
23:01:55:381 add task 187 type 19 to 0x00137A0000040A4B cluster 0x0000 req.id 85
23:01:55:383 Websocket 192.168.0.6:37086 send message: {"e":"added","id":"2","r":"lights","t":"event","uniqueid":"00:13:7a:00:00:04:0a:4b-01"} (ret = 87)
23:01:55:383 Websocket 192.168.0.12:39558 send message: {"e":"added","id":"2","r":"lights","t":"event","uniqueid":"00:13:7a:00:00:04:0a:4b-01"} (ret = 87)
23:01:55:385 Websocket disconnected 192.168.0.6:37086 (state: 0) 
23:01:55:389 poll node 00:13:7a:00:00:04:0a:4b-01
23:01:55:389 Poll light node Smart plug 2
23:01:55:405 HTTP client hdr detected:
GET /api/B62B11D007/lights HTTP/1.1
Host: 192.168.0.12
Connection: keep-alive
Accept: vnd.ddel.v1
X-Requested-With: XMLHttpRequest
User-Agent: Mozilla/5.0 (X11; Linux armv7l) AppleWebKit/537.36 (KHTML, like Gecko) Raspbian Chromium/74.0.3729.157 Chrome/74.0.3729.157 Safari/537.36
Referer: http://192.168.0.12/pwa/devices-lights.html?_v=b879bb8a461451c5b1d759a4c80a78c2b9b1642f,9,3,23&gwid=00212EFFFF04DB7B
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9
If-None-Match: "f11f9e96c223018f66656a21e3025a95"


23:01:55:405 HTTP API GET /api/B62B11D007/lights - 192.168.0.12
23:01:55:405 ApiMode: 0
23:01:55:406 {"2":{"etag":"8432ec2be6e6e215168e46dee5867d5d","hascolor":false,"manufacturername":"netvox","modelid":null,"name":"Smart plug 2","state":{"alert":"none","on":false,"reachable":true},"swversion":null,"type":"Smart plug","uniqueid":"00:13:7a:00:00:04:0a:4b-01"}}
23:01:55:407 Erase task req-id: 85, type: 19 zcl seqno: 4 send time 0, profileId: 0x0104, clusterId: 0x0000
23:01:55:442 read attributes of 0x00137A0000040A4B cluster: 0x0000: [ 23:01:55:442 0x0005 23:01:55:442 ]
23:01:55:442 add task 188 type 19 to 0x00137A0000040A4B cluster 0x0000 req.id 86
23:01:55:442 Poll APS request 86 to 0x00137A0000040A4B cluster: 0x0000
23:01:55:482 Node data 0x00137a0000040a4b profileId: 0x0104, clusterId: 0x0000
23:01:55:482 Working with modelId Z809AE3R
23:01:55:482 Device supported
23:01:55:482 ~Resource() /sensors 0x7eff8428
23:01:55:482 ~Resource() /sensors 0x7eff8428
23:01:55:486 Poll APS confirm 86 status: 0x00
23:01:55:486 Erase task req-id: 86, type: 19 zcl seqno: 5 send time 0, profileId: 0x0104, clusterId: 0x0000
23:01:55:488 read attributes of 0x00137A0000040A4B cluster: 0x0000: [ 23:01:55:488 0x4000 23:01:55:489 ]
23:01:55:489 add task 190 type 19 to 0x00137A0000040A4B cluster 0x0000 req.id 89
23:01:55:489 Poll APS request 89 to 0x00137A0000040A4B cluster: 0x0000
23:01:55:505 ZDP discovery done in 5001 ms23:01:55:512 add task 191 type 30 to 0x00137A0000040A4B cluster 0x0004 req.id 90
23:01:55:534 HTTP client hdr detected:
```

Does it only add new sensors on the first go or does it continually look for them?

Any ideas on how to grab or override the modelId on the first go?

thanks for your help so far.

**Comment by ebaauw** [comment]
> Does it only add new sensors on the first go or does it continually look for them?
> Any ideas on how to grab or override the modelId on the first go?

deCONZ doesn't "look" for new devices in the tradional meaning of looking.  Also, there's no single orchestration logic handling the pairing; it's event-based.

When opening the network, the deCONZ core programme broadcasts a message to all routers to accept new devices.  On reset, a ZigBee devices tries to find a router that will accept a new device, and exchange the network key.  After joining the ZigBee network, the devices announces itselves.  On receiving such an announcement, the deCONZ core programme reads the device's _Node Descriptor_ (for the _Manufacturer Code_ and list of endpoints).  On receiving the _Node Descriptor_, it populates the GUI node with that info.  Next, it will query the _Simple Descriptors_ (for protocol (ZHA/ZLL), _Device Type_, and clusters per endpoint).  On receiving the _Simple Descriptor_, it populates the drop-down list for the right of the two circular buttons on the GUI node.

The REST API plugins listens in on this ZigBee traffic, but only when it is "searching" for new devices (that's why you have to open the network from the REST API/Phoscon app/Old web app, instead of from the GUI).  On seeing the _Simple Descriptor_ it creates `/lights` resources, if the received info matches the whitelisting.  On seeing a _Basic_ cluster in the _Simple Descriptor_, it will query the _Model Identifier_ attribute.  On receiving the _Model Identifier_, it creates the `/sensors` resources, if the info matches the whitelisting.

If deCONZ or the REST API plugin doesn't receive a response, the next step is never triggered.  Especially on sleepy (battery-powered) end devices, not all queries might reach the device.  And depending on network load and physical conditions, not all responses might make it back.  To remedy, you can reset the device and start over (likely running into the same issue), or you can re-issue the last request manually from the GUI, trying to get the right response to continue.  This is where trying to read the descriptors from the left of the two round buttons on the GUI node comes in, and the reading of the _Basic_ cluster attributes in the _Cluster Info_ panel.

**Comment by clockbrain** [comment]
Thanks this is really helpful. I have now managed to get the voltage & consumption sensors to be created (once) by pressing the rightmost button and cluster in deCONZ UI.

I now need to spend a bit more time understanding how exactly that worked and what if anything can be done to make it less manual.

**Comment by Smanar** [comment]
Lol, nice I have missed the bad model id.
BTW the fonction readBindingTable() change something for you ?

**Comment by clockbrain** [comment]
@Smanar you're right. The change to readBindingTable wasn't necessary so I've removed it.

I had originally included it just by searching everywhere for 'whitelist' and trying to emulate what was there without much understanding of what each of them did.

I think it is ok to merge now. Works well enough for me. I've got three of these netvox smart plugs paired and linked through to Home Assistant. Thanks for your help.

P.S. I struggled a bit as there isn't really any visual indication in Phoscon that the associated sensors have been created for the smart plug so I was trying to scan log files after the event. Would be better if there was some feedback when the light/smart plug was created that it had related sensors also. Just my 2c.

**Pull request merged**
