### PR TITLE
Add DDF for Xiaomi presence sensor lumi.sensor_motion.aq2 (RTCGQ11LM)

### PR DESCRIPTION
**Pull request by SwoopX**
Adds respective DDF, no legacy code to remove.

### CODE REVIEW

**Comment by cyablo** [comment]
This change breaks update of light level on this sensor. It's stuck on (probably) the last value before the update.

**Comment by SwoopX** [comment]
Hm, works fine over here

**Comment by cyablo** [comment]
Tried 2.17 again,  even tried repairing a sensor, light level is stuck. Downgraded to 2.16.1 everything fine again. Conbee II with Firmware 26780700

**Comment by Tscheurgen** [comment]
Unfortunately I have the same issue as cyablo. My lux value of ZHALightLevel is stuck at 0. Any hint to fix this?

**Comment by Tscheurgen** [comment]
I have a bit investigated.
Measured Value of Cluster 0400 (Illuminance Measurement) does Change, but REST provides always the same value.

**Comment by cyablo** [comment]
We got into that in the Forum: https://forum.phoscon.de/t/rtcgq11lm-light-level-broken-since-2-17/2104/7

**Comment by Tscheurgen** [comment]
I'm sorry, Thank you for the link!

**Pull request merged**
