### PR TITLE
DDF for Aubess Multi Sensor TS201 with LCD display

### PR DESCRIPTION
**Pull request by Finne75**
Based on #6394. [Link ](https://www.aliexpress.com/item/1005003071537749.html) to product.

### CODE REVIEW

**Comment by manup** [comment]
Hi, is the .json file extension missing?

**Comment by Finne75** [comment]
Indeed :/

**Comment by Finne75** [comment]
But is fixed now :)

**Comment by Finne75** [comment]
I try again in another PR

**Pull request closed without merging**
