### PR TITLE
Eria adurolight remote support

### PR DESCRIPTION
**Pull request by mdolnik**
Refer to issues: #1730 and #3383

Refer to previous Pull Request #4211

These changes allow the Eria Adurosmart remote to send events for each button press.

From what I can tell there is no distinction from the remote for holding the button or double clicking, so this just provides simple button presses.

### CODE REVIEW

**Comment by mdolnik** [comment]
Please note the change in 4da5cc8 which is a little unconventional as the current logic is essentially ignoring the button map as this remote has a situation where it sends the same endpoint/cluster/command ID for every button pressed and only makes the distinction between buttons via payload value.

> This switch has a situation where it sends the same endpoint/cluster/command ID for every button pressed and only makes the distinction between buttons via payload value.
> The current logic in `DeRestPluginPrivate::checkSensorButtonEvent()` currently does not support this type of distinction, and the button map (field #5) only seems to support the first digit of the payload value and not the full payload value.
> Therefore all of the information that distinguishes between the buttons ends up being ignored and the button events are being sent as the first mapped entry (button 1).
> This commit changes the logic within `DeRestPluginPrivate::checkSensorButtonEvent()` to allow the value of the button pressed to be modified once a valid mapped entry has been found, and adds specific logic for the Eria Adurosmart Wireless Dimming Switch to change the button value based off of the payload value.

Ideally this type of situation should have an extra value (or modify the existing 5th value) in the button maps to allow for identification of the FULL payload to distinguish the types of buttons pressed.

I'm open to suggestions and/or I can help test any changes.

**Comment by mdolnik** [comment]
Also none of these changes allow it to be recognized by Phoscon (only deCONZ GUI).

The events can be picked up by Home Assistant in the `/developer-tools/event` page.
2021-02-28_17h06_42

I'm not sure if this is normal, but it is added as a Device in Home Assistant, but not as an Entity.
2021-02-28_17h08_14

**Comment by SwoopX** [comment]
I'm afraid all what's required is the creation of the button map and the addition of the manufacturer specific cluster at the right place, all other amendments are superfluous.

Also, the referred to PRs have the MFC VENDOR_JENNIC, so that would mean people running those would probably end up with non-working devices.

**Comment by SwoopX** [comment]
I stay brief here and apparently, I missed your feedback on the previous PR.

Your code is "just" working as it benefits from a logic flaw allowing incomplete button maps to be stored in memory. Incomplete in this sense because you added a 3 Bytes payload, which is disallowed and also throws errors in the debug log right after starting deconz. Apparently, a for-loop is not exited appropriately.

- As for the manufacturer code: The code a device has gets added, simple as that. However, the really problematic part I had in mind is obviously already gone.
- Regarding `DeRestPluginPrivate::addSensorNode()`: Here you're indeed right a whitelisting is required. Doing whatever purely on the manufacturer code is just aching and an awkward legacy heritage, that hopefully will be eradicated in the mid term.
- Regarding the code at an appropriate place: Well, the place is right and now I understand why adding all that code was required to make it work (as mentioned at the top). In the end, it shouldn't be more than for the Sengled...

To not loop all the back and forth through, how about if I quickly put the required parts together and you check'em?

**Comment by mdolnik** [comment]
> Your code is "just" working as it benefits from a logic flaw allowing incomplete button maps to be stored in memory. Incomplete in this sense because you added a 3 Bytes payload, which is disallowed and also throws errors in the debug log right after starting deconz.

Is this referring to the `000000`, `000100`, `000200`, etc values in the button map? If-so those don't even need to be there as they never get read by any of the current logic as right now [the for loop mentioned in the code reference of my previous comment](https://github.com/dresden-elektronik/deconz-rest-plugin/pull/4495/#issuecomment-788427989) will only grab the first button map entry every time.

I could technically change all of those values to `0` and/or only have one generic button map value that works for all buttons because the only thing in my pull request which is doing any actual button mapping is...
```
// Eria Adurosmart Wireless Dimming Switch.
else if (ind.clusterId() == ADUROLIGHT_CLUSTER_ID && sensor->modelId() == QLatin1String("Adurolight_NCC"))
{
    ok = true;
    // Since the only way to determine which buttons was pressed is by the payload,
    // change the value of buttonPressed based on the payload value.
    quint16 payload;
    QDataStream stream(zclFrame.payload());
    stream.setByteOrder(QDataStream::LittleEndian);
    stream >> payload;
    switch (payload) {
        case 0x000000: buttonPressed = (S_BUTTON_1 + S_BUTTON_ACTION_SHORT_RELEASED); break;
        case 0x000100: buttonPressed = (S_BUTTON_2 + S_BUTTON_ACTION_SHORT_RELEASED); break;
        case 0x000200: buttonPressed = (S_BUTTON_3 + S_BUTTON_ACTION_SHORT_RELEASED); break;
        case 0x000300: buttonPressed = (S_BUTTON_4 + S_BUTTON_ACTION_SHORT_RELEASED); break;
        default: ok = false; break;
    }
}
```

> To not loop all the back and forth through, how about if I quickly put the required parts together and you check'em?

Thanks that would help. Are you implying that you will make your own pull request for this issue and I will review and ensure it works for me?

> Regarding DeRestPluginPrivate::addSensorNode(): Here you're indeed right, a whitelisting is required. Doing whatever purely on the manufacturer code is just aching and an awkward legacy heritage, that hopefully will be eradicated in the mid term.

Fair enough, I will reverse commits 486ce64 and e403df9 (unless you're making your own PR).

**Comment by SwoopX** [comment]
Check out https://github.com/SwoopX/deconz-rest-plugin/commit/6fd2f17570fd2ff53830117200bfc7dfdd0e2946

**Comment by mdolnik** [comment]
> Check out #4580

I just tested the Eria remote with that branch and it works! Thanks for 

I think I understand now how your approach works, essentially it loops through all of the button map entries and you're essentially setting the `ok` variable as to whether the current payload value matches the `zclParam0` of the current button map entry.

I'm closing this PR in favor of your branch.

**Comment by SwoopX** [comment]
I guess the whole function is a bit... clumsy and could use a decent overhaul. I haven't dared that yet since mistakes would have quite some impact. It was already painful enough when I introduced the button maps due to other than obvious hidden dependencies.

**Pull request closed without merging**
