### PR TITLE
Create zigfred_uno_wired_switch.json

### PR DESCRIPTION
**Pull request by WhistleMaster**
Initial support for Siglis zigfred_uno device made with @Smanar.

### CODE REVIEW

**Comment by Atokulus** [comment]
Dear all

I am dearly sorry, that I have not yet been able to respond to your integration request. It is quite nice, you took initiative in integrating the device 😄 Great job and kudos to @WhistleMaster and @Smanar 😁

I have checked your code and it looks quite promising. 

There are two issues that comes to my mind which would benefit from being addressed before merging:

* One seems to be that the zigfred button state encoding is not on pair with the specification by Deconz.
* Another one is that polling is currently used over attribute reporting. This has a huge impact on network traffic and might lead to congestion.

So let me address both of them:

# Button state mapping

zigfred's button state encoding has to be mapped to Deconz's expected button event encoding. See

* https://dresden-elektronik.github.io/deconz-rest-doc/endpoints/sensors/button_events/
* https://github.com/manup/deconz-rest-plugin/blob/device_descriptions/devices/philips/rwl02_dimmer_switch.json#L63
* https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/devices/siglis.js#L17 for reference.

On zigfred, the button's state code is encoded within an attribute (`0x0008` in manufacturer specific zigfred cluster `0xFC42`) **and** as a custom command `0x002` from manufacturer specific zigfred cluster `0xFC42` (to lower latency, as attribute reporting rate is often limited to one update each second). The button state is encoded in the following way:

```c
typedef enum {
  BUTTON_RELEASE = 0x00,
  BUTTON_CLICK = 0x01,
  BUTTON_DOUBLE = 0x02,
  BUTTON_HOLD = 0x03,
} zf_button_state_t;
```

A proper way to do the mapping, would be the following `eval` function:

```js
const eventLookup = [
  0x03, // 0x00 -> Long Release (equivalent to button hold release in zigfred terminology)
  0x00, // 0x01 -> Short Release (equivalent to button click in zigfred terminology)
  0x04, // 0x02 -> Double Press (equivalent to button double click in zigfred terminology)
  0x01, // 0x03 -> Hold (0x01)
];
Item.val = (ZclFrame.at(0)+1) * 1000 + eventLookup[ZclFrame.at(1)];
```

respectively as valid JSON:

```json
"eval": "const eventLookup = [0x03, 0x00, 0x04, 0x01]; Item.val = (ZclFrame.at(0)+1) * 1000 + eventLookup[ZclFrame.at(1)]"
```

# Attribute reporting
Zigbee Attribute Reporting will let zigfred tell Deconz the current light state on its own, without the need for data-intense polling/readout of the attribute values, as soon as it changes. This means, that the overall network traffic can be reduced by a lot!

An example can be seen in https://github.com/manup/deconz-rest-plugin/blob/device_descriptions/devices/ikea/kadrilj_blind.json

With Deconz DDF, one needs to enter all attributes manually. So in the case of zigfred, this would mean something like:
```json
"supportsMgmtBind": true,
"bindings": [
  {
    "bind": "unicast",
    "src.ep": "0x05",
    "cl": "0x0006",
    "report": [
      {
        "at": "0x0000",
        "dt": "0x10",
        "min": 1,
        "max": 1800,
        "change": "0x01"
      }
    ]
  },
  {
    "bind": "unicast",
    "src.ep": "0x05",
    "cl": "0x0008",
    "report": [
      {
        "at": "0x0000",
        "dt": "0x20",
        "min": 1,
        "max": 1800,
        "change": "0x01"
      }
    ]
  },
  {
    "bind": "unicast",
    "src.ep": "0x05",
    "cl": "0x0300",
    "report": [
      {
        "at": "0x0003",
        "dt": "0x21",
        "min": 5,
        "max": 1800,
        "change": "0x0a"
      },
      {
        "at": "0x0004",
        "dt": "0x21",
        "min": 5,
        "max": 1800,
        "change": "0x0a"
      },
    ]
  },
  {
    "bind": "unicast",
    "src.ep": "0x06",
    "cl": "0x0006",
    "report": [
      {
        "at": "0x0000",
        "dt": "0x10",
        "min": 1,
        "max": 1800,
        "change": "0x01"
      }
    ]
  },
  {
    "bind": "unicast",
    "src.ep": "0x07",
    "cl": "0x0006",
    "report": [
      {
        "at": "0x0000",
        "dt": "0x10",
        "min": 1,
        "max": 1800,
        "change": "0x01"
      }
    ]
  },
  {
    "bind": "unicast",
    "src.ep": "0x07",
    "cl": "0x0008",
    "report": [
      {
        "at": "0x0000",
        "dt": "0x20",
        "min": 1,
        "max": 1800,
        "change": "0x01"
      }
    ]
  },
],
```

I will attach the final code here, as soon as I have tested it out myself (this takes me until 3am, Zurich time, probably. I have been reading into Deconz DDFs and integration only one hour ago, so I better check myself, if everything is correct.

And I can also test and add the DDF for zigfred plus.

Many thanks to you both and best regards 😉
Markus


P.S. @WhistleMaster & @Smanar: If you want by chance to meet up for some coding hackathon or wathever, just PM me at mw@siglis.com

**Comment by WhistleMaster** [comment]
Thanks @Atokulus for the detailed comment !

> I will attach the final code here, as soon as I have tested it out myself (this takes me until 3am, Zurich time, probably. I have been reading into Deconz DDFs and integration only one hour ago, so I better check myself, if everything is correct.

I'll be happy to test your new DDF with my device.

> P.S. @WhistleMaster & @Smanar: If you want by chance to meet up for some coding hackathon or wathever, just PM me at [mw@siglis.com](mailto:mw@siglis.com)

Will do :)

**Comment by Atokulus** [comment]
I just opened GH-6282 which adds all together. Best regards and looking forward to meeting you :)

**Comment by WhistleMaster** [comment]
Great, thanks ! Should I close this one then ?

PS: The zigfred uno is a great device but when should we expect the new zigfred plus ;-) ?

**Comment by Atokulus** [comment]
Dear @WhistleMaster 
Yes, you might close this pull request.

We are currently doing last tests and PCB to PCB assembly on zigfred plus as we finally got the first manufactured batch from our electronics supplier for our preorder customers 😉 I believe my team mate mentioned mid to end september as shipping date.

Best regards
Markus

**Comment by WhistleMaster** [comment]
Great news ! Looking forward to it :)

I close this PR then.

Best regards,
WM

**Comment by Smanar** [comment]
>P.S. @WhistleMaster & @Smanar: If you want by chance to meet up for some coding hackathon or wathever, just PM me at [mw@siglis.com](mailto:mw@siglis.com)

Lol, thx for the proposition and for the finals DDFs.

Just a question have you tested the first version ? Because If I m right as we have skipped the binding part, deconz make a generic one, less complete than your, but in my mind enought to prevent the polling no ?

```
    else if (bt.binding.clusterId == BINARY_INPUT_CLUSTER_ID)
    {
        rq.dataType = deCONZ::ZclBoolean;
        rq.attributeId = 0x0055; // present value
        rq.minInterval = 10;
        rq.maxInterval = 300;
        return sendConfigureReportingRequest(bt, {rq});
    }
```

**Comment by Atokulus** [comment]
Dear @Smanar
I did not know about default attribute report registration nor did I test the first version. But I guess it is fine to have some explicit control over the report parameters.

**Pull request closed without merging**
