### PR TITLE
Initial support for Legrand Wireless Smart Dimmer with Netatmo WNRL63

### PR DESCRIPTION
**Pull request by Smanar**
- Product name: Wireless Smart Dimmer with Netatmo
- Manufacturer: Legrand
- Model identifier: Remote Dimmer Switch
See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5343

### CODE REVIEW

**Comment by stevenwfoley** [comment]
Hello, I was just curious when this might get merged into a release?

**Comment by stevenwfoley** [comment]
Can anyone comment on when this might get merged into a release? Is this waiting on something, or further dev?

**Comment by Smanar** [comment]
Hello.
ATM adding new device is only alowed using DDF.
Not sure the core was finished to support it, but I can help you to make a DDF to try ? Will be easier if you don't have HA, but have you at least acess to the GUI ?

**Comment by stevenwfoley** [comment]
Thank you Smanar. Looking at the "Files Changed" section it looks like all that was done was adding modelID strings to a couple files, so hopefully that same result can be achieved through the DDF.
I do have full access to the deconz gui.

**Comment by Smanar** [comment]
You will probably too edit the xml file but will see later.

You have a video here https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/DDF-cheat-sheet

So after making "Edit DDF"
- fill "basic cluster indentification" if values are empty
- drag and drop a ZHASwitch
- save the DDF
- make "hot reload"

If we are lucky first the device will be reconized (but not working), and if you use it you will see error about button map on logs with "info" and "info_l2"

If not error message, go on the editor second tab and make binding for cluster 0x0006 (only this one it s for test)

**Pull request closed without merging**
