### PR TITLE
Hue smart button no longer updated

### PR DESCRIPTION
**Pull request by ebaauw**
See #6347.

### CODE REVIEW

**Comment by farianfossy** [comment]
Hello.

I updated deconz to version 2.19.01 yesterday.
Since I was affected by error #6288 for a long time. Now I noticed that the smartbuttons do not work anymore.
The problem seemed to be known. Unfortunately, I cannot confirm that it has been fixed.

Neither via Phoscon nor via Hue Essentials does the smart button react.
The firmware is still 26780700.

Could you please look at this again or give me a tip on how to solve this?

Thank you very much and best regards.
Marian

**Comment by tbpoetke** [comment]
> Hello.
> 
> I updated deconz to version 2.19.01 yesterday. Since I was affected by error #6288 for a long time. Now I noticed that the smartbuttons do not work anymore. The problem seemed to be known. Unfortunately, I cannot confirm that it has been fixed.
> 
> Neither via Phoscon nor via Hue Essentials does the smart button react. The firmware is still 26780700.
> 
> Could you please look at this again or give me a tip on how to solve this?
> 
> Thank you very much and best regards. Marian

same here :(

**Comment by alefab** [comment]
> Hello.
> 
> I updated deconz to version 2.19.01 yesterday. Since I was affected by error #6288 for a long time. Now I noticed that the smartbuttons do not work anymore. The problem seemed to be known. Unfortunately, I cannot confirm that it has been fixed.
> 
> Neither via Phoscon nor via Hue Essentials does the smart button react. The firmware is still 26780700.
> 
> Could you please look at this again or give me a tip on how to solve this?
> 
> Thank you very much and best regards. Marian

same here, even after a deletion of the switch and re insertion :(
image
Bouton Hue - Abigaelle <= button that I didn't have deleted/linked angain
Bouton Hue - Aurélian <= button that I did have deleted and re linked to deconz

**Comment by ebaauw** [comment]
I cannot help with Phoson, but it's suspicious that it reports the two buttons differently.  Make sure to read the _Basic_ attributes of both buttons in the GUI - they should report _Manufacturer Name_ of "Signify Netherlands B.V.", not "Philips".   If not, double-check the _SW Build ID_, it should be "2.47.8_h2F968624".  If not, you might need to update the button's firmware.

Next, check in the GUI that the FC00 cluster receives the button actions.  If not, the issue is likely with the binding of the button to the coordinator, or with the configuration of the button (attribute 0x0031 in the _Basic_ cluster should be 0x000b).  The API plugin should set this, once it knows the button is awake, but if the binding isn't there, the API plugin never hears from the button.

If you see the button actions in the GUI, but not in the API, please turn on logging INFO, INFO_L2, ERROR, ERROR_L2, APS, and APS_L2, and capture the debug log while pressing the button.

**Comment by alefab** [comment]
I reverted back to previous version of deconz, and it work again.
For info,
1. both buttons are not working with 2.19.1 ( by not working, I mean that the light linked to the switch is not turning on/off )
2. both buttons were linked to the network and responding to deconz gui requests
3. when I checked the GUI for both buttons, the only difference was MAC, NWK and Manufacturer ( one with Philips and the other with "Signify Netherlands B.V." )
4. I recently ( 1 month ago ) updated both buttons to 2.47.8_h2F968624

**Comment by tbpoetke** [comment]
@alefab 
> I reverted back to previous version of deconz, and it work again. For info,
> 
how to downgrade ?

**Comment by tbpoetke** [comment]
> @alefab
> 
> > I reverted back to previous version of deconz, and it work again. For info,
> 
> how to downgrade ?

nvm, I found it under backups

**Comment by tbpoetke** [comment]
working after downgrade

**Comment by alefab** [comment]
> > @alefab
> > > I reverted back to previous version of deconz, and it work again. For info,
> > 
> > 
> > how to downgrade ?
> 
> nvm, I found it under backups

Yes, if using home assistant, there is an automatic backup done that can be restored when a plugin is updated.

**Comment by geir55** [comment]
I have the same problem. Downgraded

**Comment by jnt0r** [comment]
I can confirm this too. Could not connect the button and after downgrading to 2.18.02 I see the button already configured.

**Pull request merged**
