### PR TITLE
Add initial support for edp re:dy smart plug (ZM-SmartPlug-1.0.0)

### PR DESCRIPTION
**Pull request by SwoopX**

### CODE REVIEW

**Comment by vpedromarques** [comment]
Sorry if I don't know how this updates works and if this "initial support" is noticeable or not. Installed master branch (2.9) and still can't see any metering being reported. Deleted node and re-added it but still nothing...

{"etag":"5215b21d444caf6bbcc21e0a0565d7f6","hascolor":false,"lastannounced":null,"lastseen":"2020-12-28T18:16Z","manufacturername":"EDP-WITHUS","modelid":"ZB-SmartPlug-1.0.0","name":"On/Off plug-in unit 74","state":{"alert":"none","on":true,"reachable":true},"swversion":null,"type":"On/Off plug-in unit","uniqueid":"00:12:4b:00:0c:0f:16:4c-55"}

**Comment by Mimiix** [comment]
> Sorry if I don't know how this updates works and if this "initial support" is noticeable or not. Installed master branch (2.9) and still can't see any metering being reported. Deleted node and re-added it but still nothing...
> 
> {"etag":"5215b21d444caf6bbcc21e0a0565d7f6","hascolor":false,"lastannounced":null,"lastseen":"2020-12-28T18:16Z","manufacturername":"EDP-WITHUS","modelid":"ZB-SmartPlug-1.0.0","name":"On/Off plug-in unit 74","state":{"alert":"none","on":true,"reachable":true},"swversion":null,"type":"On/Off plug-in unit","uniqueid":"00:12:4b:00:0c:0f:16:4c-55"}


You should check sensors

**Comment by SwoopX** [comment]
There was a typo in the original request which now requires a fix.

**Comment by vpedromarques** [comment]
> There was a typo in the original request which now requires a fix.

ahh! Sorry! I'll be waiting for the correction. Thanks!

**Pull request merged**
