### PR TITLE
Add `fingerprint` to DDFs for `sensors` resources

### PR DESCRIPTION
**Pull request by ebaauw**
Add `fingerprint` to the DDF sub devices for `sensors` resources of the following devices:
- Develco SMSZB-120 smoke detector;
- IKEA FYRTUR block-out roller blind;
- IKEA VINDSTYRKA Air Quality sensor;
- innr SP 120 smart plug;
- Hue smart button
- Hue dimmer switch (2021)
- Hue motion sensor;
- Hue outdoor motion sensor;
- Hue motion sensor (2022);
- Hue outdoor motion sensor (2022);
- Xiaomi Aqara FP1 presence sensor;
- Xiaomi Aqara Roller Shade Driver E1 

This is especially relevant to ZHAPresence sensors (like the Hue motion sensor family), where the fingerprint is used to find the `Sensor`, see #6845.  Not sure if this changes any functionality for the other resources, but it should get rid of "Missing cluster in sensor fingerprint" warnings in the log.

The devices in this PR are just the ones I have online.  I think this needs to be checked for all DDFs exposing `sensors` resources.

### CODE REVIEW

**Comment by manup** [comment]
Side info: The fingerprint data in DDFs are currently extra baggage, needed for some devices, to keep parts of the old code working. I hope we can get rid of it in future entirely.

**Comment by SwoopX** [comment]
While I really appreciate the effort, also to have the DDFs complete and consistent, the practical benefit of those additions is very limited as I recall. The DDFs their selves do not make the fingerprints (sort of) superfluous, but the parts which can be skipped in `apsdeDataIndication()` due to the result of the check if a device is managed or not.

As we see also with this PR, motion sensors are somewhat a special case in this regard, as the handler predominantly cannot be skipped. Devices exposing `config/delay` are save to skip it (Hue motion sensors, Develco/Frient), but all the others require it due to the `durationDue` related presence state reset.

Hue/Develco/Frient motion sensors "just" throw a, admittedly irritating, message that a respective sensor could not be found (true if no fingerprint is available) and exit the handler function. Same might happen for other clusters as well.

**Comment by manup** [comment]
I think for now it's ok to include the fingerprint extras, once cleanup in C++ parts is more progressed and functionality which uses fingerprint can be handled by new DDF code we can remove these later on. On one side it's a uphill battle with baby steps, but I like the smaller steps so we don't mess up too eagerly :)

**Comment by manup** [comment]
Random thought, we maybe should just remove the debug line in question, if it doesn't help us much other than being spammy?

**Pull request merged**
