### PR TITLE
DDF for Third Reality, Inc smart button 3RSB22BZ

### PR DESCRIPTION
**Pull request by louix**
Issue: #7863

### CODE REVIEW

**Comment by manup** [comment]
```
Item.val={1: 1002, 2: 1004, 0: 1001, 255: 1003}[Number(ZclFrame.at(3))]
```

I don't think that will work in Javascript since object keys must be strings.

Here's an alternative approach (1):

```js
const v = [1, 1002, 2, 1004, 0, 1001, 255, 1003];
const n = v.indexOf(ZclFrame.at(3));
if (n >= 0) Item.val = v[n + 1];
```

Or another one as one liner (2):

```js
const n = ZclFrame.at(3); if (n < 3) { Item.val = [1001, 1002, 1004][n]; } else if (n == 255) { Item.val = 1003; }
```

Not pretty but should do the trick without string conversions :)

**Comment by Smanar** [comment]
Another one that have workied for him

`n=Number(ZclFrame.at(3));t={'1': 1002, '2': 1004, '0': 1001, '255': 1003};if(n in t){Item.val=t[n]}`

**Comment by louix** [comment]
Hey, apologies for the confusion.

JS engines internally coerces keys that are not `string | Symbol` via [ToPropertyKey][0]:

```sh
$ node --eval "console.log({1: true})"
{ '1': true }
$ node --eval "console.log({'1': 'hello'}[1])"
'hello'
```

A `Map` can be used:
```sh
$ node --eval "console.log(new Map([[1, true]]))"
Map(1) { 1 => true }
$ node --eval "console.log(new Map([[1, 'hello'], [2, 'goodbye']]).get(1))"
hello
```

But it's for sure uglier, and probably a bit slower:
```js
Item.val=new Map([[1, 1002], [2, 1004], [0, 1001], [255, 1003]]).get(Number(ZclFrame.at(3)))
```

[0]: https://tc39.es/ecma262/#sec-topropertykey

**Comment by Smanar** [comment]
lol, sometime we are searching a special function, sometime we found too much of them ^^.
On my side for a so simple convertion I prefer a "one liner"

**Comment by manup** [comment]
> It should be fine, JS engines internally coerces keys that are not string | Symbol via [ToPropertyKey](https://tc39.es/ecma262/#sec-topropertykey) as part of the ECMAScript spec:

Thanks I didn't know that. Could you test if this is also supported in DucktapeJS engine?
This is the engine used in deCONZ and supports only ECMAScript E5 and just a subset of newer versions <https://duktape.org>

**Comment by louix** [comment]
Thanks Manuel.

> Could you test if this is also supported in DucktapeJS engine?

Sure. They have a nice web REPL, and I am happy to report [it works][0] (version 20500).

I have tested the device integration with deCONZ, too.

All said and done, this is your codebase and the conventions are up to you, I'm happy to change to to something if it makes it more difficult for maintainers to reason about.

[0]: 
https://duktape.org/dukweb#print(JSON.stringify(%7B1%3A%20true%7D))%0Aprint(%7B'1'%3A%20'hello'%7D%5B1%5D)%0A%0Aprint(%22%3A)%22\)

**Comment by manup** [comment]
Cool nice that it works, then I see no problem for merging.

I like Web REPL, perhaps some time this should also be integrated into the UI for easier testing.

**Pull request merged**
