### PR TITLE
Add further Danfoss specific resource items

### PR DESCRIPTION
**Pull request by SwoopX**
This PR adds a few missing resource item json files:
- `config/lastchange_source`
- `config/lastchange_time`
- `config/lastchange_amount`

and adds a few new resource items for thermostats (primarily Danfoss specific):
- `config/mode` -> Generic item, allowing for values 'off' and 'heat'. Set to 'off' when heating period ends to prevent unnecessary valve adjustments.
- `config/loadbalancing` -> Thermostat runs stand alone (false) or shares load with others in the same room (true).
- `config/radiatorcovered` -> Radiator is standing freely (false) or is covered (true). Set this to true for Danfoss Ally to use external temp sensor.
- `config/windowopendetectionenabled` -> Turns the window open detection feature on or off.

### CODE REVIEW

**Comment by Prior99** [comment]
This would be really useful to have.

**Comment by Didier3L** [comment]
Good evening, there is also `Heat Supply Request` which allows you to know if the radiator needs hot water
image

**Comment by ebaauw** [comment]
Shouldn’t the `lastchange` attributes be in `state` rather than `config`?

**Comment by SwoopX** [comment]
> Shouldn’t the `lastchange` attributes be in `state` rather than `config`?

Yeah, I guess so. Not sure if you had a reason to do it as is back in the days? 🙂 
Can change it once we have had the discussion on the thermostat resource items.

**Comment by Didier3L** [comment]
these changes will be available when in the latest version ?

**Comment by Smanar** [comment]
What is blocking for this PR ?

**Comment by Pe-MaKer** [comment]
I would really appreciate these items to be available soon.
It's a shame that one has to set config/heatavailable in the UI for each thermostat twice a year if the solution just has to be merged.

**Comment by Jonaslinderoth** [comment]
I would really appreciate  it if we could add the items discussed in as well #6872.
Allowing for reading the load estimate and writing to the load radiator load mean, will make it possible to calculate the average load estimate for all the radiators in the room, and forwarding it to each radiator. 

This will help distribute the load between the radiators which is helpfull when you have multiple radiators of different sizes in the same room.

**Comment by manup** [comment]
Almost ready, can you please also change the remaining `{"fn": "zcl"}` cases so the validator won't scream :)

**Comment by SwoopX** [comment]
> Almost ready, can you please also change the remaining `{"fn": "zcl"}` cases so the validator won't scream :)

That now took me a while to understand which ones you meant as I was focussed on Danfoss and totally forgot about the additions 😀 Done

**Comment by Hencor93** [comment]
May a little late, but I just saw that the PR was merged now. 
I miss the Items for Config `Load Radiator Room Mean` and the `Load estimate on this radiator` as a State. Without these items the load balancing mode on the TRVs cannot be used. 
These two are present in the PR #6872 and was missed to merged into this PR I think.

**Comment by Smanar** [comment]
I think the better solution is making a new PR just for them, it's not possible (more complex) to rollback a PR just for that.

**Pull request merged**
