### PR TITLE
Add battery updates for LIDL/Silvercrest motion sensor

### PR DESCRIPTION
**Pull request by SwoopX**

### CODE REVIEW

**Comment by dodo124** [comment]
Hi there :-)

I´m needing a hint ...

Installed Beta firmware26680700 and I´m unable to add the above sensor :-( 

What am I doing wrong?

Any help welcome ;-)

Greetings Dom

**Comment by Mimiix** [comment]
> Hi there :-)
> 
> I´m needing a hint ...
> 
> Installed Beta firmware26680700 and I´m unable to add the above sensor :-( 
> 
> What am I doing wrong?
> 
> Any help welcome ;-)
> 
> Greetings Dom

Did you try to reset it with the small button in the hole?

**Comment by dodo124** [comment]
Hi Miimix,

yes I did.  And after that deCons App says "ready" and when hitting the green "ready button" that nothing is happening.

In deConz the sensor is mapped but the bar is gray.

:-( any idea?

Regards Dominik

**Comment by Smanar** [comment]
The presence detection is working ?
Do you have the device JSON ?

**Comment by dodo124** [comment]
Hi Smanar,

The presence detection seems to be working because it reacts to the sensor signal, though not correct I´m afraid.

Can U tell me how to get the json for U? This one?
`{
  "from": "system.adapter.deconz.0",
  "user": "system.user.admin",
  "ts": 1607201511344,
  "common": {
    "name": "Presence 9 presence",
    "type": "mixed",
    "role": "sensor.motion",
    "read": true,
    "write": false
  },
  "native": {},
  "acl": {
    "object": 1638,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator",
    "state": 1638
  },
  "_id": "deconz.0.Sensors.9.presence",
  "type": "state"
}`

where can i find the previuos one?

Thanks :-)

Dom

btw. all other Lidl components seem to work and don´t have a different controll than the Lidl Hub.

**Comment by Smanar** [comment]
Strange you have it working without the battery.
To find the json you can have in in logs generaly, on deconz or your third app, or direcly in the api if you have an api key.

`http://IP:PORT/api/KEY/sensors`

IP and PORT : same than for deconz
KEY : your api key.

Have you tried to re-include it, without deleting the old entry ?

**Comment by dodo124** [comment]
Ok here is the status screen of the iobroker.
status

**Comment by Smanar** [comment]
I m seing a battery field on it ? with value  = 100

**Comment by dodo124** [comment]
Hi, yes its true the sensor is battery powered.

**Comment by SwoopX** [comment]
This is just the wrong place to discuss whatever the issue is here, and that apparently is not the battery level.

**Comment by Mimiix** [comment]
Closing this issue off. @dodo124  feel free to join our discord or open a user question issue.

**Pull request merged**
