### PR TITLE
Update ZCLDB to add/update some Measurement clusters

### PR DESCRIPTION
**Pull request by BabaIsYou**
Complete general.xml to add Concentration Measurement clusters as Zigbee Cluster Library Specification Revision 8 and other measurement updates.

### CODE REVIEW

**Comment by BabaIsYou** [comment]
BTW need perhaps to be linked with the issue #6904 to be fully operational in GUI

**Comment by ebaauw** [comment]
Damn, this PR breaks support for the Hue motion sensors sensitivity and sensitivity max.

**Comment by BabaIsYou** [comment]
Look like the same trouble I already got because some Elko specific defintions hadn't mfcode specified in general.xml and were positionned before Sinopé specific definition. Then were loaded before specific Sinopé that had mfcode.

Changing the order into general.xml resolved the issue #6827

Then I guees that moving Hue-specific attributes 0x0030 and 0x0031 on Occupancy Sensing before the Zigbee specification will solve it.

**Comment by BabaIsYou** [comment]
I know it works for having tested it before on another previous conflicted definition.

I’m also aware that’s just a workaround, but it works until other way of doing it (custom xml file with specific loading order should have been another solution … if it should have been functional; -/ )

**Pull request merged**
