### PR TITLE
DDF for IKEA VINDSTYRKA

### PR DESCRIPTION
**Pull request by ebaauw**
Note: this PR depends on #7252.

This updated DDF for the IKEA VINDSTYRKA sensor introduces the new `state/measured_value` and corresponding `capabilities` items.  Unfortunately, the sensor reports temperature and humidity at a coarse resolution, so we cannot see the floating point values in action.

### ZHATemperature
- Add `state/measured_value`, as float value in °C.  Unfortunately, the sensor's granularity is limited to integer values;
- Add corresponding `cap/measured_value` items.  `min` and `max` are reported by the sensor; `quantity`, `substance`, and `unit` are defined in the DDF;
- Deprecate `state/temperature` (integer value in 0.01 °C);
- Not sure what to do with `config/offset` (also integer value in 0.01 °C).  I do apply it to `state/measured_value`, but ultimately, we want this as a float values as well.  Maybe introduce `config/measured_value/offset` and deprecate `config/offset`?
```
{
  "capabilities": {
    "measured_value": {
      "max": 50,
      "min": -10,
      "quantity": "temperature",
      "substance": "air",
      "unit": "degC"
    }
  },
  "config": {
    "offset": 0,
    "on": true,
    "reachable": true
  },
  "ep": 1,
  "etag": "89dc3816a6ddd73d103a8e2cc4b61caa",
  "lastannounced": null,
  "lastseen": "2023-09-23T14:05Z",
  "manufacturername": "IKEA of Sweden",
  "modelid": "VINDSTYRKA",
  "name": "Vindstyrka",
  "productid": "E2112",
  "state": {
    "lastupdated": "2023-09-23T14:02:06.470",
    "measured_value": 23,
    "temperature": 2300
  },
  "swversion": "1.0.11",
  "type": "ZHATemperature",
  "uniqueid": "94:34:69:ff:fe:bb:f4:92-01-0402"
}

```

### ZHAHumidity
- Add `state/measured_value`, as float value in %.  Unfortunately, the sensor's granularity is limited to integer values;
- Add corresponding `cap/measured_value` items.  `min` and `max` are reported by the sensor; `quantity`, `substance`, and `unit` are defined in the DDF;
- Deprecate `state/temperature` (integer value in 0.01%);
- Not sure what to do with `config/offset` (also integer value in 0.01%).  I do apply it to `state/measured_value`, but ultimately, we want this as a float values as well.  Maybe introduce `config/measured_value/offset` and deprecate `config/offset`?
```
{
  "capabilities": {
    "measured_value": {
      "max": 100,
      "min": 0,
      "quantity": "level",
      "substance": "relative humidity",
      "unit": "%"
    }
  },
  "config": {
    "offset": 0,
    "on": true,
    "reachable": true
  },
  "ep": 1,
  "etag": "4a8285863f1847c8f96f1a6e6dc98a4a",
  "lastannounced": null,
  "lastseen": "2023-09-23T14:01Z",
  "manufacturername": "IKEA of Sweden",
  "modelid": "VINDSTYRKA",
  "name": "Vindstyrka",
  "productid": "E2112",
  "state": {
    "humidity": 5800,
    "lastupdated": "2023-09-23T14:00:08.432",
    "measured_value": 58
  },
  "swversion": "1.0.11",
  "type": "ZHAHumidity",
  "uniqueid": "94:34:69:ff:fe:bb:f4:92-01-0405"
}
```

### ZHAParticulateMatter
The sensor uses the standard 0x042A to report PM2.5 density.
- Change `type` to ZHAParticulateMatter (was ZHAAirQuality);
- Add `state/measured_value`, as float value in µg/m³.  Unfortunately, the sensor's granularity is limited to integer values;
- Add corresponding `cap/measured_value` items.  `min` and `max` are reported by the sensor; `quantity`, `substance`, and `unit` are defined in the DDF;
- Derive `state/airquality` from `state/measured_value`.  The validator error for this is being fixed by @Zehir;
- Deprecate `state/pm2_5`.
```
{
  "capabilities": {
    "measured_value": {
      "max": 999,
      "min": 0,
      "quantity": "density",
      "substance": "PM2.5",
      "unit": "ug/m^3"
    }
  },
  "config": {
    "on": true,
    "reachable": true
  },
  "ep": 1,
  "etag": "5ab00c1628d670a2eeda5bff81463897",
  "lastannounced": null,
  "lastseen": "2023-09-23T14:02Z",
  "manufacturername": "IKEA of Sweden",
  "modelid": "VINDSTYRKA",
  "name": "Vindstyrka",
  "productid": "E2112",
  "state": {
    "airquality": "excellent",
    "lastupdated": "2023-09-23T14:01:32.533",
    "measured_value": 1,
    "pm2_5": 1
  },
  "swversion": "1.0.11",
  "type": "ZHAParticulateMatter",
  "uniqueid": "94:34:69:ff:fe:bb:f4:92-01-042a"
}
```

### ZHAAirQuality
The sensor uses IKEA-specific cluster to report the tVOC level.
- Add `state/measured_value`, as float value in ppb.  Unfortunately, the sensor's granularity is limited to integer values;
- Add corresponding `cap/measured_value` items.  `min` and `max` are reported by the sensor; `quantity`, `substance`, and `unit` are defined in the DDF;
- Derive `state/airquality` from `state/measured_value`.  The validator error for this is being fixed by @Zehir;
- Deprecate `state/airqualityppb`.
```
{
  "capabilities": {
    "measured_value": {
      "max": 500,
      "min": 0,
      "quantity": "level",
      "substance": "tVOC",
      "unit": "ppb"
    }
  },
  "config": {
    "on": true,
    "reachable": true
  },
  "ep": 1,
  "etag": "036255a18e94d3760a13e8ceb66abb52",
  "lastannounced": null,
  "lastseen": "2023-09-23T14:02Z",
  "manufacturername": "IKEA of Sweden",
  "modelid": "VINDSTYRKA",
  "name": "Vindstyrka",
  "productid": "E2112",
  "state": {
    "airquality": "good",
    "airqualityppb": 75,
    "lastupdated": "2023-09-23T13:59:56.439",
    "measured_value": 75
  },
  "swversion": "1.0.11",
  "type": "ZHAAirQuality",
  "uniqueid": "94:34:69:ff:fe:bb:f4:92-01-fc7e"
}
```

### CODE REVIEW

**Comment by ebaauw** [comment]
Damn.  The C++ code eats up the float values.  Hacked a Hue motion sensor to expose `measured_value` on the ZHATemperature.  The DDF log suggests it returns float values, but `DataTypeRead` doesn't yet work:
```
Sep 17 13:14:26 pi6 deCONZ[596217]: 13:14:26:699 todo handle DataTypeReal in setValue13:14:26:700 DJS result  24.86, memory peak: 211390 bytes
Sep 17 13:14:26 pi6 deCONZ[596217]: 13:14:26:700 00:17:88:01:0b:d1:08:d7-02-0402/state/measured_value expression: Item.val = (Attr.val - R.item('config/offset').val) / 100 --> 24.86
```
Consequentlty, the resource shows integers:
```
{
  "capabilities": {
    "measured_value": {
      "max": 0,
      "min": -273,
      "quantity": "temperature",
      "substance": "air",
      "unit": "°C"
    }
  },
  "config": {
    "alert": "none",
    "battery": 100,
    "offset": 0,
    "on": true,
    "reachable": true
  },
  "ep": 2,
  "etag": "eb831be1be62b172954c2e2f069a093e",
  "lastannounced": null,
  "lastseen": "2023-09-17T11:13Z",
  "manufacturername": "Signify Netherlands B.V.",
  "modelid": "SML004",
  "name": "Hue outdoor motion sensor 2022",
  "productname": "Hue outdoor temp. sensor",
  "state": {
    "lastupdated": "2023-09-17T11:13:42.147",
    "measured_value": 25,
    "temperature": 2460
  },
  "swversion": "2.53.6",
  "type": "ZHATemperature",
  "uniqueid": "00:17:88:01:0b:d1:08:d7-02-0402"
}
```

**Comment by Zehir** [comment]
@ebaauw I have updated the github action to 1.8.1 with lastest changes of the validator, you can re-run the validator from the `Checks` tab.

**Comment by manup** [comment]
I don't have the device for testing, PR looks fine to me except the `state/temperature` deprecation :)

**Comment by ebaauw** [comment]
Updated.

**Comment by LeoeLeoeL** [comment]
I think unit of measure for TVOC should be changed from PPB to a "general" INDEX.
TVOC PPB scale goes from 0 to 5500 but this entity stops to 500.

**Comment by BabaIsYou** [comment]
Already reported https://github.com/dresden-elektronik/deconz-rest-plugin/pull/7121#issuecomment-1668732577 and https://github.com/dresden-elektronik/deconz-rest-plugin/pull/6673#issuecomment-1572665255 but may be lost into larger discussions.

**Comment by LeoeLeoeL** [comment]
I wrote INDEX because also PM 2.5 often uses a scale (called AQI) that goes from 0 to 500.

**Comment by BabaIsYou** [comment]
> We could do linear extrapolation in each range, but I'd rather see a proper formula, @BabaIsYou would you have that?

Unfortunately I don't ! But I think that this kind of transformation won't reflect what this index is in reality. It's not a measure of a concentration but the reflect of an empiric  variation on the last 24 hours. Then I think that I could be better to change unit and quantity in the device specific DDF for devices that are based on SEN54 sensor like the VindStyrka.

**Comment by BabaIsYou** [comment]
> I wrote INDEX because also PM 2.5 often uses a scale (called AQI) that goes from 0 to 500.

AFAIK AQI is not limited to PM 2.5, is a kind of tVOC as it combines several substances to get an index :  https://www.airnow.gov/sites/default/files/2020-05/aqi-technical-assistance-document-sept2018.pdf

**Comment by LeoeLeoeL** [comment]
I have 3 of them (PM 2.5 sensors):
image
They can show PM 2.5 in AQI index or ug/m3.
They are "faster" than Vindstyrka but they arent "smart".

**Comment by BabaIsYou** [comment]
You're right, my misunderstanding of how it is calculated. The AQI is calculated from the upper pollutant (only one in youre case) based on the calculation chart and formula in pages 9-10 of the referenced pdf.

**Comment by ebaauw** [comment]
Fixed in #7297.

**Pull request merged**
