### PR TITLE
Sonoff SNZB-01

### PR DESCRIPTION
**Pull request by Smanar**
Untested,
Change some remote value.

But the code will be editable direclty in next version (json file)

### CODE REVIEW

**Comment by SwoopX** [comment]
Took the liberty to include this already in my larger PR 😉

**Comment by Smanar** [comment]
@SwoopX 
So I can close the PR ?

**Comment by SwoopX** [comment]
Yes, but I'd say leave it open for now. Not sure when my PR will come into play so we have this one as backup.

**Comment by Smanar** [comment]
Ok so, note for Manup ^^

Pls do not merge this PR if you take the new code for Button map.

**Comment by SwoopX** [comment]
@Smanar Ok, now it can be closed ;)

**Comment by SAOPP** [comment]
Guys, at 86th beta button don't send any events. In 85th version I saw single click event, but now any events is away.

**Comment by Mimiix** [comment]
@SAOPP So this broke too?

**Comment by SAOPP** [comment]
@Mimiix I don't know what to say, on the 85th version all events started working for me. Now there are no events from this button at all. @SwoopX told me that is my internal setup issue. But honestly, I'm not sure about that. But on the 86th version, the button is stupidly silent, just like the vibration sensor.

**Comment by SwoopX** [comment]
Please provide us with some logs including button presses to check them, as suggested.

**Comment by SAOPP** [comment]
I haven't seen any mention from other owners of this device, is everything okay or not with it on the 86th version.

**Pull request closed without merging**
