### PR TITLE
[subdevice] items_optional for ZHAOpenClose

### PR DESCRIPTION
**Pull request by Zehir**
Part 15 of https://github.com/dresden-elektronik/deconz-rest-plugin/pull/7155

### CODE REVIEW

**Comment by manup** [comment]
From my understanding the `config/on` is mandatory on all sensor types. It seems to be only used for enabling sensors in rules processing.

**Comment by Zehir** [comment]
> From my understanding the `config/on` is mandatory on all sensor types. It seems to be only used for enabling sensors in rules processing.

Then this one is having an issue, it's the only one that dont have the `config/on`
https://github.com/dresden-elektronik/deconz-rest-plugin/blob/dd4bb528ff1061dd4adbc8bae931a4bdfa6ae8e0/devices/tuya/_TZE200_htnnfasr_water_valve.json#L69-L161

**Comment by manup** [comment]
Indeed imho `config/on` should be added to the device.

**Comment by Zehir** [comment]
> Indeed imho `config/on` should be added to the device.

Then we can just close this PR, I will let somebody else update the DDF

**Review by ebaauw — CHANGES_REQUESTED** [review]
`config/on` is mandatory for all `sensors` resources.  It's not mapped to any Zigbee attribute.  The REST API uses it to enable/disable rules triggered by this sensor.

**Comment by Zehir** [comment]
> 

ok then no need to merge this PR because there is no changes

**Pull request closed without merging**
