### PR TITLE
ZHALightLevel and more...

### PR DESCRIPTION
**Pull request by ebaauw**
- Use sensor `type` ZHALightLevel instead of ZHALight.
- Also issue web socket notification for `config.battery` on read/report, when value hasn’t changed.
- Setup attribute reporting for color temperature 0x0300/0x0007 of lights and binding for Trådfri remote (commit 471679a - sorry wrong comment, but I can't seem to change it).  The color temperature works: I see dbg-info level 2 messages and the expected settings can be read back from the deCONZ GUI.  I'm not too sure about the Trådfri remote bindings - I don't see any info message for binding of cluster 0x0005.
- Bug fixes for mac address mask; Don't re-create IKEA remote rules when rules exist, but disabled.
- Change light `manufacturer` attribute to `manufacturername` (issue #30, item 7).

### CODE REVIEW

**Comment by donnib** [comment]
@ebaauw i can't check it atm but does the events for remotes also give the battery status or are battery events separate only ?

**Comment by ebaauw** [comment]
Separate events.

deCONZ doesn't combine multiple attributes into one event yet (with the exception of a sensor's `state.lastupdated`).  Even if it would, the sensors send a separate attribute reporting message for battery (as it's on a different cluster, so the updates arrive at a different time from the updates for presence, light level, temperature, or button event.

**Comment by donnib** [comment]
@ebaauw thank you

**Comment by donnib** [comment]
I forgot to ask, would it make sense to have battery for a CLIP Sensor ? I would use it for test purpose while i develop.

**Comment by ebaauw** [comment]
Yes it would, not just for testing, but also if you use the CLIP sensor as a proxy for an external battery-powered sensor (that isn't connected to the ZigBee network).  If you include `"config": {"battery":100}` in the POST body while creating the CLIP sensor, the created resource should contain it and allow PUTs to change it.

Same for `reachable`.

**Comment by donnib** [comment]
ahh cool, i didn't know that, will try that, i had only tried to do a `PUT` on `battery` and obviously it failed.

**Comment by snozzlebert** [comment]
> Also issue web socket notification for ```config.battery``` on read/report, when value hasn’t changed.

Why? If the value isn't changed I won't expect ```"e":"changed"```. I think it is confusing.
Now I get this from my dimmer switch:
```
2017-08-16 08:03:45 {"config":{"battery":100},"e":"changed","id":"1","r":"sensors","t":"event"}
2017-08-16 08:08:46 {"config":{"battery":100},"e":"changed","id":"1","r":"sensors","t":"event"}
2017-08-16 08:13:47 {"config":{"battery":100},"e":"changed","id":"1","r":"sensors","t":"event"}
2017-08-16 08:18:48 {"config":{"battery":100},"e":"changed","id":"1","r":"sensors","t":"event"}
2017-08-16 08:23:49 {"config":{"battery":100},"e":"changed","id":"1","r":"sensors","t":"event"}
```

**Comment by ebaauw** [comment]
You might be right...  and it becomes even more confusing when `config.duration` and `config.sensitivity` come into play.

My thought was to receive web socket events when the sensor sends an attribute reporting command to the gateway, so you could use these to build up a history of values.  By changing the attribute reporting setting, you could configure how often you'd get these events.  Also, somehow this seemed more consistent with the behaviour for the Hue motion sensor for the state attributes (of course in that case, `state.lastupdated` has changed even when `state.presence`, `state.lightlevel` or `state.temperature` haven't).

**Pull request merged**
