### PR TITLE
Initial support for Tuya dimmer with double Gang.

### PR DESCRIPTION
**Pull request by Smanar**
- Product name: MoesHouse 2 Gang ZigBee Dimmer Module MS-105BZ
- Manufacturer: _TZE200_e3oitdyu
- Model identifier: TS0601

This device use the tuya hack, so it create 3 "light" sensors, with only 2 are used.

Will try to correct that with DDF files.

See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5320

### CODE REVIEW

**Comment by vishivishy** [comment]
Hi @Smanar @Mimiix @manup , any ETA on when this will be merged? Thanks

**Comment by Mimiix** [comment]
Nope I don't :(

**Comment by vishivishy** [comment]
Its already been 3 months since this change, is there anything I can do to help get this merged?

**Comment by Smanar** [comment]
Nope, inclusion for classic device is only allowed using DDF, tuya is special, but it seem it s locked too for the moment.
And this device can't be added yet using only DDF.

**Comment by boennhoff** [comment]
I have several installed since november and can't get them to work. the DDF rework merge blocker #5733 seems to be the reason for the delay in device acceptance. so i tried today with this PR rebased on master, and was not able to make it work. They are now shown as dimmable lights, but only a single light. In the deCONZ gui i can see 3 different "clusterinfo groups".
What am i missing?

**Comment by boennhoff** [comment]
@Mimiix thanks, that's a good hint with phoscon, matches the picture. I recognized other fallbacks as well. Shouldn't ioBroker use the API as well? it still only creates only one object/entity per device.

I read that for HomeAssistant a complete rewrote of the tuya integration was happening because of a device definition problem, like we have here, if I get it right -- probably I don't 😄 But is this related? Is there a nice writeup of the backgrounds of this DDF case we have here? Maybe only in german?

**Comment by Mimiix** [comment]
Iobroker uses the API but i am not sure how it implements this. So i can't answer that.

On DDF: There's a cheatsheet in the wiki. Not sure on other documentation.

**Pull request closed without merging**
