### PR TITLE
Add DDF for SMaBiT Door sensor AV2010/21C

### PR DESCRIPTION
**Pull request by Smanar**
Nothing special, see https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5992

### CODE REVIEW

**Comment by SwoopX** [comment]
The DDF is still incomplete. It misses the `config/battery` item and the respective binding for the power configuration cluster.

**Comment by Smanar** [comment]
@SwoopX take a look here https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5992#issuecomment-1114295233
This device doesn't seem to have it, so I m using just state/lowbattery

Can correct it when I will have confirmation this cluster is working.

**Comment by SwoopX** [comment]
Ah, point well taken. Pitty that it reports 0. Maybe they thought with the advertised 10 yrs battery life, it wouldn't be too necessary 😄

**Comment by Smanar** [comment]
lol
IDK, can be too an issue when reading attribute (it happen on doorlock). But for the moment can't do better with thoses captures.

**Comment by bubffm** [comment]
I dont seem to be able to connect this sensor via phoscon.  sensor seems to blink twice after a while (indicating connection), but phoscon does not give a confirmation, remaining stuck in the connection modus.  

Any ideas?

**Comment by Mimiix** [comment]
> I dont seem to be able to connect this sensor via phoscon. sensor seems to blink twice after a while (indicating connection), but phoscon does not give a confirmation, remaining stuck in the connection modus.
> 
> Any ideas?

Please open a forum post on this.

**Pull request merged**
