### PR TITLE
Fix Xiaomi WXKG11LM regression bug for ZHASwitch resource creation

### PR DESCRIPTION
**Pull request by SwoopX**
This fix should allow the device to be paired again.

### CODE REVIEW

**Comment by jankryh** [comment]
the problem still remains v2.14.1

**Comment by syre** [comment]
I'm running v2.14.1 and the switch paired successfully for me.

**Comment by rohrsh** [comment]
I upgraded to 2.14.01-raspbian-buster-beta tonight and can now repair my Xiaomi buttons. Thank you.

**Comment by bumpyflea** [comment]
Hi @manup 
Are you guys doing anything specific to be able to pair the Xiaomi buttons?  I'm on 2.14.1 and have been trying for about 2 hrs trying to get 2 of these buttons to pair to the conbee II, but haven't been able to do. 

image

Would really appreciate any tips / suggestions that you can provide.  The model number is WXKG11LM  and it's having the same issue as described on https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5599

**Pull request merged**
