### PR TITLE
Add initial support for Apex smart plug (PoP)

### PR DESCRIPTION
**Pull request by SwoopX**
- Add initial support
- Add Datek specific clusters to general.xml

### CODE REVIEW

**Comment by haarvig** [comment]
What´s the process for this now? Will support be implemented in a new version of HA, or how does this work?

**Comment by SwoopX** [comment]
So the (presumably) working code is currently available within my branch and could be compiled manually for testing and verification purposes. If no further issues are identified, the PR gets merged into the official repository, that usually happens every 1 - 2 weeks. Again, the code can be evaluated and compiled manually, but this time from the official repo. Typically, new beta versions are released on the 15th of a month, but there may be exceptions to do it more frequently. Stable releases are released around the beginning of a month. See also the release schedule in the repo's readme. The above does not take important bug fixes into account.

Now, we don't have any influence on the HA side when they update. However, they chose to follow up on stable releases only, if you're relying on their addon.

There might be another beta before year end so the device addition would be available to HA addon somewhere shortly after Jan 15th.

One additional remark on the integration if you allow: Please take note that we primarily do this remotely and without us having the device in hands, so this is best effort under the given circumstances. If you're up for it (and I understood you'd appreciate to have further devices of yours integrated as well), it would be really beneficial to have sample devices available. There's certain details and quirks you only note when you have direct access. I'd be more than happy to arrange an easy exchange on this with DE.

Cheers.

**Comment by haarvig** [comment]
Thanks for the update. As I use HA myself, I appreciate this work. I can send you a sample device, no problem. Also we have additional sensors coming up during Q1 2021. Please have a look at the datasheets on this page if you want:
https://www.datek.no/en/products-and-solutions/smart-home

Next sensor is the Meter Reader (HAN adapter) for connecting to AMS meter. As of now it will not pair using deCONZ Phoscon. I can provide sample of this too, and Zigbee cluster documentation. Please let me know if this is of interest. ;y contact details are on the bottom of the page I linked to.

Thanks for all help!

**Comment by SwoopX** [comment]
@haarvig Just the time of year ;)

So, we're happy to also add support for the other devices. I talked to DE and they can make sure that sample devices you might want to donate will reach me. Just reach out to mpi@dresden-elektronik.de for my address and we get that accomodated.

**Comment by haarvig** [comment]
Seems this is not in the latest beta @SwoopX ? Is there an issue with support for the Smart Plug?

**Comment by SwoopX** [comment]
@haarvig not too sure why this hasn't been included yet. There's no problem from the code perspective so far. Lemme poke DE on this to make sure it gets merged asap ;)

**Comment by haarvig** [comment]
> @haarvig Just the time of year ;)
> 
> So, we're happy to also add support for the other devices. I talked to DE and they can make sure that sample devices you might want to donate will reach me. Just reach out to [mpi@dresden-elektronik.de](mailto:mpi@dresden-elektronik.de) for my address and we get that accomodated.

Joined discord as DatekHarald. We have new sensors coming in shortly and seek to have them supported in Deconz and also Z2M.

**Comment by SwoopX** [comment]
Feel free to ping us ;)

**Pull request merged**
