### PR TITLE
[subdevice] items_optional for Color dimmable light

### PR DESCRIPTION
**Pull request by Zehir**
Part 7 of #7155

### CODE REVIEW

**Comment by Zehir** [comment]
@ebaauw suggested that this type should be removed

**Comment by ebaauw** [comment]
Because it's used for lights with only colour temperature, only colour, and both colour and colour temperature.  This is the old (pre-Zigbee 3) ZHA type.  Most Zigbee-3 lights use the ZLL types: _Color Temperature Light_, _Color Light_, _Extended Color Light_.  _Color Dimmable Light_ should be mapped to one of these three, depending on the colour capabilities it supports.  Note that the legacy code did the mapping for some whitelisted lights, but not for all.

**Comment by ebaauw** [comment]
Changed the DDFs of the three _Color Dimmable Light_ in https://github.com/dresden-elektronik/deconz-rest-plugin/pull/7221, so we could simply delete this type.

**Comment by Zehir** [comment]
I updated the PR to remove the json references of the `Color Dimmable Light` but there is still some references to it in the C code

**Review by ebaauw — APPROVED** [review]

**Pull request merged**
