### PR TITLE
Hue white and color ambiance lights

### PR DESCRIPTION
**Pull request by ebaauw**
With latest firmware, Hue white and color ambiance lights carry a manufacturer-specific cluster 0xFC03.  On newer Zigbee 3 lights (typically with BLE support), this is used to set Hue-specific effects, gradient points, etc.  It also reports the current light state in a single attribute, combining info from the _On/Off_, _Level Control_, and _Color Control_ cluster.  The older ZLL lights (typically without BLE support) carry this cluster as well, but don't support atrribute reporting.  See #6192 and #5891.

In essence, this PR provides DDFs and the supporting C++ code for Hue (white and) color ambiance lights:
- One for gradient lights, adding support for gradient mode and dynamic effects, and setting up attribute reporting for the 0xFC03 state attribute, with fallback polling;
- One for the Hue Festavia gradient string light (see #6536);
- One for Zigbee 3 white and color ambiance lights, adding support for dynamic effects, and setting up attribute reporting for the 0xFC03 state attribute, with fallback polling; and
- One for ZLL gamut-C white and color lights, with polling of the 0xFC03 state attribute.
- One for ZLL gamut-B white and color lights, with polling of the 0xFC03 state attribute.
- One for ZLL gamut-A color ambiance lights, that don't support colour temperature and don't carry the 0xFC03 cluster.

The FC03 state attribute encodes the values of _On/Off_, _Current Level_, _Current X_, _Current Y_, _Color Temperature_, the Hue effect, and the gradient.  However, it does not include _Enhanced Current Hue_, _Current Saturation_, _Color Loop Active_, and _Enhanced Color Mode_.  Also, these attributes are stlll not reportable.

The Hue API v2 no longer supports setting colours through `hue` and `sat`.  It still supports colour loop from the ZLL extensions, but quite differently from the Hue API v1.  Also, there is an undocumented dynamic effect, that looks like colour loop, but behaves a bit differently.

I wouldn't mind dropping support for `state/hue` and `state/sat` altogether, but I would hate dropping the colour loop effect from `state/effect`.  Also, the colour mode cannot be deduced from the FC03 state in all cases.  Consequently, we still need to poll the _Color Control_ cluster for _Enhanced Color Mode_ and _Color Loop Active_.  Since we can read _Enhanced Current Hue_, _Current Saturation_ in the same command, I'll leave `state/hue` and `state/sat` in for now.

This PR adds `capabilities` and `config` maps to `lights` resources.  Changes of attributes in these maps are reported in separate web socket push notifications for `capabilities` and `config`.  The attributes in `capabilities` are read-only; those in `config` are read/write.  The `capabilities` resource items in C++ are prefixed with `RCap`; the items in the DDFs are prefixed with `cap/`.

The ambition for `capabilities` is to eliminate the need to whitelist lights on manufacturer and model.  All device-dependent behaviour would be modelled using capabilities instead.  Some capabilities are for internal use by the REST API plugin only.  You would add them to the DDF, but they're not exposed through the API.

The following table lists the `capabilities` attributes:

Atttribute | Default | API | DDF | Description
-- | -- | -- | -- | --
`alert/trigger_effect`| `true` |  | Y | Subdevice supports _Trigger Effect_.<br>Exposed through `capabilities/alerts`.
`alerts` | | Y | | List with supported `state.alert` values.<br>Note that `state/alert` is write-only and always reports `"none"`.
`bri` | | | | Map with _Level Control_ capabilities.
`bti/min_dim_level` | | Y | Y | Percentage of lumen the light outputs at minimum value for `state/bri`.
`bri/move_with_onoff` | `true` | |  Y | Subdevice supports _Move to Level (with On/Off)_.<br>Influences the subdevice on/off logic.
`color` | | Y | | Map with _Color Control_ capabilities.<br>Replaces deprecated top-level attribute `hascolor`.
`color/capabilities` | | | Y |  Bitmap with supported colour modes.<br>Replaces deprecated top-level attribute `colorcapabilities`.<br>Exposed through `capabilities/color/mode` and `capabilities/color/effects`.
`color/ct` | | Y | | Map with colour temperature capabilities.
`color/ct/computes_xy` | `true` | Y | Y | Light computes and updates `state/xy`, while in `ct` colour mode.
`color/ct/max`| `500` | Y | Y | Maximum supported `state/ct` value.<br>Replaces deprecated top-level attribute `ctmax`.
`color/ct/min` | `153` | Y | Y | Minimum supported `state/ct` value.<br>Replaces deprecated top-level attribute `ctmin`.
`color/effects`|  | Y | | List of supported `state/effect` values.<br>Lights supporting colour loop and/or dynamic effects.<br>Hue white and color ambiance ZB3 lights support new values, see #6192.
`color/gamut_type` | | Y | Y | Hue gamut type: `"A"`, `"B"`, or `"C"`.<br>Hue (white and) color ambiance lights.
`color/gradient` |  | Y | | Map with gradient capabilities.<br>Hue white and color ambiance gradient lights, see #5891 and #6536.
`color/gradient/max_segments` |  | Y | Y | Maximum supported `state/gradient/segments` value.
`color/gradient/pixel_count` |  | Y | Y | Number of gradient "pixels".
`color/gradient/pixel_length` |  | Y | Y | Physical length (in 0.1 mm) of a gradient "pixel".
`color/gradient/styles` | | Y | Y | List of supported `state/gradient/style` values.<br>Note that I'm using the friendly names from the Hue app, rather than the technical names from the Hue API v2.
`color/modes` | | Y | | List with supported `state/colormode` values:<br>- `ct`: Colour temperature;<br>- `effect`: Dynamic effect;<br>- `gradient`: Gradient;<br>- `hs`: Colour by hue/saturation;<br>- `xy`: Colour by CIE 1931 colour space coordinates.
`color/xy` | | Y |  | Map with supported values for `state/xy`.
`color/xy/red` | `[0.9961, 0]` | Y | | Red-most value for `state/xy`.
`color/xy/red_x` | `0xFEFF` | | Y | Red-most value for _Current X_.
`color/xy/red_y` | `0` | | Y | Red-most value for _Current Y_.
`color/xy/green` | `[0, 0.9961]` | Y | | Green-most value for `state/xy`.
`color/xy/green_x` | `0` | | Y | Green-most value for _Current X_.
`color/xy/green_y` | `0xFEFF` | | Y | Green-most value for _Current Y_.
`color/xy/blue` |  `[0, 0]` | Y | | Blue-most value for `state/xy`.
`color/xy/blue_x` |  `0` | Y | | Blue-most value for _Current X_.
`color/xy/blue_y` |  `0` | Y | | Blue-most value for _Current Y_.
`groups` | | | | Map with _Groups_ capabilities.
`groups/not_supported` | `true` |  | Y | _Groups_ cluster does not work<br>Subdevice cannot be included in a group.<br>Exposed through (absence of) `config/groups`.
`on` | | Y | | Map with _On/Off_ capabilities.
`on/off_with_effect` | `true` | Y | Y | Device supports _Off with Effect_ command.<br>Influences the subdevice off logic, see #6104.
`sleeper` | `true` | Y | Y | Device turns radio off for more than 7.5s.<br>Influence the logic of interacting with the device.
`transition_block` | `true` | Y | Y | Device doesn't accept commands during active transition.<br>Bug in older IKEA firmware.

With these changes, attributes `ctmax`, `ctmin`, `colormode`, and `hascolor` have become obsolete and should be deprecated.  To remove them from the light state, specify `Accept: application/vnd.ddel.v3` in the HTTP header.

The following table lists the `config` attributes:

Atttribute | Default | API | DDF | Description
-- | -- | -- | -- | --
`bri` | | | | Map with _Level Control_ settings.
`bri/execute_if_off` | `true` |  | Y | Change brightness while light is off.<br>Lights supporting _Execute If Off_, see #6454.
`bri/max` | `254` | Y | Y | Maximum `state/bri` value for dimmer ballast.<br>Lights supporting  _Ballast Configuration_.
`bri/min` | `1` | Y | Y | Minimum `state/bri` value for dimmer ballast.<br>Lights supporting _Ballast Configuration_.
`bri/on_level` | `true` | Y | Y | Default `state/bri` value when turning light on.<br>Lights supporting _On Level_, see #149.
`bri/onoff_transitiontime` | `4`| Y | Y | Default transition time (in 0.1 s) when turning light on or off<br>Lights supporting _OnOff Transition Time_, see #149.
`bri/startup` | `254` | Y | Y | Startup value for `state/bri`, from `0` to `254`, or `"previous"`.<br>Lights that support _Startup Current Level_;
`color` | | Y | | Map with _Color Control_ settings.
`color/ct` | | Y | | Map with colour temperature settings.
`color/ct/startup` | `366` | Y | Y | Startup value for `state/ct`: `ct` value or `"previous"`.<br>Lights that support _Startup Color Temperature_;
`color/execute_if_off` | `true` |  | Y | Change colour (temperature) while light is off.<br>Lights supporting _Execute If Off_, see #6454.
`color/gradient` |  | Y | | Map with gradient settings.
`color/gradient/reversed` | `false` | Y | Y | Gradient colours are reversed.
`color/xy` | | Y | | Map with colour settings.
`color/xy/startup` |`"previous"` | Y | | Startup value for `state/xy`: `xy` value or `"previous"`.<br>Hue white and color ambiance lights.
`color/xy/startup_x` |`0xFFFF` | | Y | Startup value for _Current X_.
`color/xy/startup_y` |`0xFFFF` | | Y | Startup value for _Current Y_.
`groups` | | Y | N | List with `groups` resource IDs of groups that the subdevice has joined.
`on` | | Y | | Map with _On/Off_ settings.
`on/startup` | `true`| Y | Y | Startup value for `state/on`: `true`, `false`, or `"previous"`.<br>Lights that support _Startup On/Off_.

Furthermore, this PR creates the following `state` attributes:

Attribute | Default | Description
-- | -- | --
`gradient` |  |  Map with gradient state.<br>Hue white and color ambiance gradient lights;
`gradient/points` |  |  A list with up to nine gradient "points", `xy` values defining a colour.
`gradient/segments` |  # points | The number of gradient "segments".<br>If this is larger than the number of points, the colours are repeated. If it's smaller, any superfluous colours are ignored.
`gradient/color_adjustment` | `0` | Adjustment to the segment colours, from 0 to 7.
`gradient/offset` | `0`  | The offset into points for the colour of the first segment.
`gradient/offset_adjustment` | `0` | Adjustment to the offset, from 0 to 7.
`gradient/style` | `linear` | The style for the gradient.<br>Note that I'm using the friendly names from the Hue app, rather than the technical names from the Hue API v2.

Finally, this PR creates the following top-level attributes:

Attribute | Default | Description
-- | -- | --
`productid` | | The `productid` as exposed by the Hue bridge.
`productname` | | The `productname` as exposed by the Hue bridge.<br>*Not yet exposed (see below).*
`swconfigid` | | The `swconfigid` as expeosed by the Hue bridge.<br>Not sure what it's used for.

Still to do:
- Better way to match lights on manufacturer, profile, device type, and firmware image type, instead of by model identifier.
- Query the light capabilities through the manifacturer-specific 0xc0/0xc1 commands on the _Basic_ cluster, o.a. others to retrieve `productname`.

Note: This is my first attempt at a PR using a different Git branch.

### CODE REVIEW

**Comment by Thomas-Vos** [comment]
The power on behaviour addition is awesome. That will be a great feature, thanks a lot for adding it. I do have a question about it. On a Hue bridge, you can set the power on mode to "return to previous state" or "switch on to previous state". Would something like that be available on deCONZ, too?

**Comment by ebaauw** [comment]
I still cannot set the power-on colour from deCONZ.  Hue lights use the same attribute IDs as _Current X_ and _Curent Y_, but now manufacturer specific, which confuses the hell out of deCONZ.  Other than that, the power-on at previous state is setting the power-on attributes to 255 (0xFF) or 65535 (0xFFFF).

**Comment by ebaauw** [comment]
Doing some more tests, now that setting multiple items from a script will trigger the corresponding event notifications.

Look like the light firmware no longer reports _Color Mode_ nor _Enhanced Color Mode_ correctly.  It seems to be updated only when explicitly setting a colour.

When activating colour loop, they report `hs` alright, but when deactivating colour loop, they continue to report `hs`, even though the light switched back to the previous colour mode, `xy` or `ct`.  Worse, the FC03 attribute reports an `xy` state, even when the mode before the colour loop was `ct` and the light is actually driving the white channels (instead of the RGB channels).  Same happens on a power cycle with power-on settings to previous state.  The light comes back in `ct` mode alright, but reports `xy`.

**Comment by ebaauw** [comment]
Fun fact: there's an undocumented third dynamic scene that suspiciously looks like colour loop.  However, this scene fixes the brightness and doesn't update _Current X_ and _Current Y_ while looping.

**Comment by ebaauw** [comment]
Still to do:
- Make `config/startup` attributes updatable through the API;
- Better way to match lights on manufacturer, profile, device type, and maybe firmware, instead of by model identifier.

**Comment by ebaauw** [comment]
With the latest commit, the `startup` map is now updatable, through PUT `/lights/#/startup`.  Attributes take regular values (boolean for `on`, integer for `bri` and `ct`, list for `xy`) or string value `"previous"`.

E.g. to have the light power on full red:
```
$ ph put /lights/8/startup '{"on": true, "bri": 255, "xy": [1, 0]}'
{
  "on": true,
  "bri": 254,
  "xy": [
    0.9961,
    0
  ]
}
$ ph get /lights/8/startup
{
  "bri": 254,
  "ct": "previous",
  "on": true,
  "xy": [
    0.9961,
    0
  ]
}
```
Or to keep it off, after a power cycle:
```
$ ph put /lights/8/startup '{"on": false, "bri": "previous", "xy": "previous"}'
{
  "on": false,
  "bri": "previous",
  "xy": "previous"
}
$ ph get /lights/8/startup
{
  "bri": "previous",
  "ct": "previous",
  "on": false,
  "xy": "previous"
}
```

**Comment by ebaauw** [comment]
For completeness, here's an overview of the startup settings supported by the Hue bridge:

Hue app | mode | on | bri | ct | x | y
-- | -- | -- | -- | -- | -- | --
Default | `safety` | `true` | `254` | `336` | `"previous"` | `"previous"`
Last on | `lastonstate` | `true` | `"previous"` | `"previous"` | `"previous"` | `"previous"`
Power loss recovery | `powerfail` | `"previous"` | `"previous"` | `"previous"` | `"previous"` | `"previous"`
Custom | `custom` | `true` | _custom_ | _custom_ | _custom_ | _custom_

**Comment by ebaauw** [comment]
Got the gradient working, see #5891.  Should also work for the Signe.  Still testing and experimenting, in search for more undocumented features.  Also, still need a sanity-check on API input when setting the gradient.

**Comment by Thomas-Vos** [comment]
Great work Erik, this is amazing!

By the way, for the Hue Gradient Signe the following model IDs exist:
```
915005987101
915005987201
915005986901
915005987001
```
There are black/white and floor/table versions, that's why there are four IDs.

Also what about the Hue PLAY gradient lightstrip for behind the TV? Were you able to test one of those, too? I don't know how similar they are at Zigbee level. Model IDs are:
LCX001
LCX002
LCX003

There is also a Hue gradient tube light, I can give you those model IDs if you want. I have one too, but it's still in the box.

Related to the startup settings, is there any reason it is at the top level and not under a `config` object? Isn't putting it under a config object more consistent with the rest of the API?

**Comment by ebaauw** [comment]
Yeah, please list the model numbers, so I can add them to the DDF.  And make the case to accept at least wildcards for the model.  I suspect the play gradient lightstrips to be very similar, using the same Zigbee interface.

There is no `config` for `lights` resources, so I put `startup` at top level.

**Comment by Thomas-Vos** [comment]
> Yeah, please list the model numbers, so I can add them to the DDF

Here are the model IDs of the Hue gradient tube I know of, all of the versions:

```
// EU/UK
915005988001
915005987901
915005988101
915005988201
// US
915005988601
915005988401
```
Again, white/black and compact/large variants so multiple zigbee model IDs. I have the 915005988001 for testing, other ones were reported by users. 

There seem to be also different variants for EU/UK and US / rest of the world, and also different model IDs. Am still missing two of the US versions. I suspect they are `915005988501` and `915005988301` (got the 12NC from US hue store, they seem to match the zigbee id), so you could add those too if you want. But as they were not reported personally I cannot be 100% sure they are correct.

**Comment by ebaauw** [comment]
Hm, if we're to expose _Execute If Off_ for _Level Control_ and _Color Control_ (see #6454), it seems to make more sense to do so as `config/bri/execute_if_off` and `config/color/execute_if_off`, instead of `config/execute_if_off/bri` and `config/execute_if_off/color`.

So the API (v2) paths become:
- {`capabilities`,`config`}`/`_cluster_`/`_attribute_, or
- {`capabilities`,`config`}`/color/`_colormode_`/`_attribute_.

So, for consistency, we would get:
Attribute | Instead of
-- | -- 
`capabilities/color/ct/max` | `capabilities/ct/max`
`capabilities/color/ct/min` |  `capabilities/ct/min`
`capabilities/color/effects` |  `capabilities/effects`
`capabilities/color/gamut_type` | Unchanged
`capabilities/color/gradient/max_segments` | `capabilities/gradient/max_segments`
`capabilities/color/gradient/pixel_count` | `capabilities/gradient/pixel_count`
`capabilities/color/gradient/pixel_length` | `capabilities/gradient/pixel_length`
`capabilities/color/modes` | Unchanged
`capabilities/color/xy/blue` | `capabilities/color/gamut/red`
`capabilities/color/xy/green` | `capabilities/color/gamut/green`
`capabilities/color/xy/red` | `capabilities/color/gamut/blue`
`config/bri/execute_if_off` | New for _Execute If Off_ , see #6454
`config/bri/on` | New for _On Level_, see #149
`config/bri/onoff_transitiontime` | New for _OnOff Transition Time_, see #149
`config/bri/startup` | `config/startup/bri`
`config/color/ct/startup` | `config/startup/ct`
`config/color/execute_if_off` | New for _Execute If Off_ , see #6454
`config/color/xy/startup` | `config/startup/xy`
`config/on/startup` | `config/startup/on`

It might looks a bit silly that, at the moment, all capabilities are colour-related, but I suppose we'll see other capabilities is future (like what `alert` values the light supports).  Also, I expect more `config` values, e.g. `config/bri/min` for _Min Level_ of _Ballast Configuration_ for in-wall dimmers, like the ubisys D1.

**Comment by hanskroner** [comment]
If I'm still on time, `LCA001` bulbs are also capable of Attribute Reporting and Dynamic Scenes with the latest v1.93.11 firmware. They could also be included in the _'white_and_color_ambiance_zha.json'_ DDF. Very much looking forward to have this functionality, thank you!

**Comment by ebaauw** [comment]
> I suppose we'll see other capabilities is future

My ambition would be that API clients no longer need to whitelist lights.  Any special behaviour should be based on `capabilities` exposed by the API, instead of whitelisting.

Checking the code of Homerbidge Hue, I whitelist lights for the following features:
- Colour gamut for RGB to `xy` conversions - already exposed by this PR;
- Support for _Trigger Effect_ - not all lights support this; non-lights definitely don't.  Some innr lights hang on _Breathe_ (firmware bug).  This capability should also determine what values for `state/alert` are acceptable.
- Light computes and updates `xy` when setting `ct` - in HomeKit, colour temperature is write-only for lights exposing both colour temperature and colour.  I need to report back the corresponding colour to display the correct temperature.  It helps if the light already makes the conversion for me.
- IKEA bug that light ignores other commands while transition is active.  I'm working around this by adding a `"transitiontime": 0` when setting more than one state attribute through the API.  This could better be handled by deCONZ, I suppose.

Similarly, my (stretch) ambition would be to eliminate whitelisting in the REST API C++ code (starting with `setLightState()`) in favour of (possibly hidden) `RCap...` resource items configured in the DDF.

Currently, `setLightState()` whitelists lights for:
- _Off with Effect_, see also #6241;
- _Move to Level (with On/Off)_, see also #2475;
- Special effects (scenes) for Hue, Mueller, and LIDL Xmas lightstrip.  Each need (different) C++ support (for now) anyway, so maybe leave this for now.

There are still two non-light devices handled by `setLightState()`:
- The DanaLock door lock - no clue why this isn't exposed as ZHADoorLock;
- The Profalux shutter, that is controlled through _Level Control_.

Since both only support one or two attributes, I think we should move these to separate functions (like `setTuyaDeviceState()`.  Unfortunately, I have neither device and cannot test this.

**Comment by Smanar** [comment]
But using a "config" field for light will not cause issue/incompatiblities ?

**Comment by ebaauw** [comment]
> But using a "config" field for light will not cause issues/incompatiblities ?

Why?  Decent API clients should just ignore new attributes they don't support.

**Comment by ebaauw** [comment]
With latest commit, PUT to a `lights` `config` should work.  Changes are written to Zigbee attributes using `StateChange`.

**Comment by Thomas-Vos** [comment]
> But using a "config" field for light will not cause issues/incompatiblities ?

No, as API clients (should) ignore any unknown attributes.

However, the official Hue API also supports capabilities/config under light resources which may cause incompatibilities. But at the time of writing my comment, all of the added attributes by Erik under capabilities/config are different than the Hue API, so they should be ignored by API clients. So this is not an issue at all.

**Comment by Gloomyeye** [comment]
@manup it is possible to review and merge this request in the next beta/release? This would be really great due to the amazing work regarding the Hue Gradient lights?

**Comment by manup** [comment]
It's a large PR but brings heaps of goodies, thanks a lot :+1:  Have this running for a few days now, and so couldn't spot any problems. Will merge for v2.20.0-beta. For some things like gammut we should iterate in future to be not too hue centric as A,B,C are fixed sets (as I understand) here it could be made more generic to expose the primaries as array which works for every light, but that's a feature for another day.

**Comment by manup** [comment]
> I'm exposing these as well (capabilities/color/xy/blue etc).

Ha, nice yes that should do.

Yeah no real way to get around manufacturer specific items. On the other hand with more functionality on DDF space we can increasingly avoid having this as C++ code. In mid future we'll be able to define custom items just in JSON with not even having counterparts defined in `resource.cpp`. My goal is to reduce the basic system so that a setup really just has to load and run code for devices which actually exist in the setup. For example systems without a Lidl xmas strip from 2019 don't even have to bother with the related code.

Bigger next challenge is the extension or definition of the REST-API itself outside of C++, but first things first :)

**Review by manup — APPROVED** [review]

**Pull request merged**
