### PR TITLE
Put R_GetProductId() and isTuyaManufacturerName() in own module

### PR DESCRIPTION
**Pull request by manup**
New files `product_match.[cpp,h]` to provide functions to identify products.

The PR removes `resource.cpp` dependency on the whole plugin which was included via `tuya.h`.

@Smanar I haven't looked through all PRs in detail, but if some of them extend the product map this would conflict.
I can resolve the conflicts when mergin the PRs.

### CODE REVIEW

**Review by ebaauw — CHANGES_REQUESTED** [review]
This is the same logic as I implemented for the LIDL devices in https://github.com/dresden-elektronik/deconz-rest-plugin/pull/3975 back in December:
https://github.com/dresden-elektronik/deconz-rest-plugin/blob/25128677b14da2412357a32d27e85a5bb7109501/de_web_plugin.cpp#L492-L545

I call these methods when handling the _Read Attributes Response_/_Report Attributes_, to patch the `manufacturername` and `modelid` values to the logical names instead of the Tuya names, so the rest of the code can use these.

I think we should at least try and harmonise this and merge the implementations.

**Comment by SwoopX** [comment]
Guys, please keep #4710 in mind here.

**Comment by Smanar** [comment]
>I haven't looked through all PRs in detail, but if some of them extend the product map this would conflict.
I can resolve the conflicts when mergin the PRs.

Ok, else I can do it (there will be probably other conflict) but let me somes days betwen this PR validation and other.

**Comment by manup** [comment]
> I think we should at least try and harmonise this and merge the implementations.

Good point, as a start I'd like to move the lidl functions unchanged into `product_map.cpp` to get them out of the `de_web_plugin.cpp`.

The `QString R_GetProductId(Resource*)` doesn't change the manufacturer name / modelid, it only returns the mapped value and attaches the non public `attr/productid` item which could also be interpreted as prettier `attr/modelid`. The same can be done for the manufacturer name. Not changing the original value is handy at some places like `isTuyaManufacturerName()`.

I think the map should be extended to also specify which values should be returned by the API so we have precise control and don't mess up with breaking changes. The values shown in REST GET responses would then just be retrieved via helper functions, for example:

```
QString GetApiManufacturerName(const Resource*);
QString GetApiModelId(const Resource*);
```

For most Tuya devices the cryptic values will be returned to not break clients. Perhaps we should expose the mapped values separately to API like *attr/prettymanufacturer* and *attr/productid* (or whatever they should be called) so everything is available but nothing breaks.

Sometimes like during pairing we don't have a `Resource*` (Sensor or LightNode) available, here we could use further functions:

```
QString GetPrettyManufacturerName(const QString &manufacturerName, const QString &modelId);
QString GetPrettyModelId(const QString &manufacturerName, const QString &modelId);
```

Note: If the map doesn't have an entry the input parameter is returned.

**Comment by manup** [comment]
> Ok, else I can do it (there will be probably other conflict) but let me somes days betwen this PR validation and other.

@Smanar I have added the entries from the PRs in commit https://github.com/dresden-elektronik/deconz-rest-plugin/pull/4717/commits/d19005fa2af4767bf8db107552f777dae5699792

So in theory in your related PRs you just need to leave them out, hope this helps a bit.

**Comment by manup** [comment]
I moved the LIDL device code from `de_web_plugin.cpp` to `product_match.cpp`. I think this can be merged for now and refactoring the two maps into into one interface can be done in a separate PR with some tests to verify nothing breaks.

**Review by ebaauw — APPROVED** [review]

**Pull request merged**
