### PR TITLE
Added support for (Revolt NX-4911-675) _TZE200_kfvq6avy

### PR DESCRIPTION
**Pull request by kgorszczyk**
It seems that Revolt released a new revision (or something) of their Zigbee TRV (old: _TYST11_kfvq6avy).
This just adds the necessary strings to make it detectable in deconz. The old TRV is already supported with #3381

### CODE REVIEW

**Comment by manup** [comment]
The _TZE200_kfvq6avy manufacturer name relates to  Revolt NX-4911-675. 
But what device is the TS0601?

**Comment by kgorszczyk** [comment]
So, let's call it the first revision Revolt released had a reported manufacturer name: _TYST11_kfvq6avy and model identifier: fvq6avy. 
The second revision has a reported manufacturer name: _TZE200_kfvq6avy and a model identifier: TS0601.
In the end, it's the exact same device, I just bought it at a later date.

**Comment by Smanar** [comment]
But better to use "_TYST11_kfvq6avy" and " _TZE200_kfvq6avy", the manufacture name is unique not the model id, you can have more than one device called "TS0601" (and not obligatory a TRV)

**Comment by Smanar** [comment]
For tuya is you can use the manufacture name istead of the model id it s better, the manufacture name is unique, not the model id.

**Comment by kgorszczyk** [comment]
Hey sorry I hadn't had time to check it until today. I didn't even notice, that I forgot to add the changes in rest_sensors.cpp. 
I saw that @Smanar already fixed it with #3989
Let's use his version as he has some additional fixed.

**Pull request closed without merging**
