### PR TITLE
Add tuya switch _TZ3000_peszejy7/_TZ3000_qzjcsmar/TZ3000_owgcnkrh/_TZ3000_adkvzooy/_TZ3000_arfwfgoa

### PR DESCRIPTION
**Pull request by Smanar**
See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3042#issuecomment-757118520

### CODE REVIEW

**Comment by Smanar** [comment]
Add model _TZ3000_qzjcsmar

**Comment by Smanar** [comment]
Add model TZ3000_owgcnkrh 2 gang > https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4309

**Comment by Smanar** [comment]
Add another one _TZ3000_adkvzooy

**Comment by Smanar** [comment]
Adding _TZ3000_arfwfgoa https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4409

**Comment by erikje14** [comment]
it actually is _TZ3000_arfwfgoa

**Comment by Smanar** [comment]
ha yep, lol, corrected.

**Comment by manup** [comment]
As usual ;) can you please list the modelid's / product names  of the switches in the PR description.
For a reader the PR description *must* list which devices are added, so there is no need to read through long issues.

**Pull request merged**
