### PR TITLE
DDF for generic Tuya TRV

### PR DESCRIPTION
**Pull request by KodeCR**
Mine has manufacturername ~~_TZE200_6rdj9dzm~~_TZE200_6rdj8dzm, might also work for others.
Mode, on, heatsetpoint, temperature, locked, offset are all tested, the remaining items aren't seen yet and/or are not supported by deCONZ.

### CODE REVIEW

**Comment by manup** [comment]
Interesting case, for now I'd propose to only include items in the DDF for which there are entries in the `generic/items` folder and respective code in `resources.cpp`. @Zehir is currently working on a validator which checks for such things.

For new items in the past unfortunately often we didn't have much discussion to figure out the best way before introducing them, which bites back later on. I hope we can get to a more streamlines process with many eyes figuring out what's the most appropriate way :)

**Comment by marten19** [comment]
My TRV has the manufacturing name _TZE200_6rdj8dzm which is almost the same. I was planning to upload it as a device request since I am not super familiar with deconz and coding yet. I wanted to upload it as a device request but first have to figure out the correct way to do so.

**Comment by Mimiix** [comment]
@marten19  Best way to find out is reading filling the template here :) 
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/new?assignees=&labels=Device+Request&template=device-request.md&title=Device+name

**Comment by KodeCR** [comment]
@manup, sorry I missed this, I've updated the DDF with only supported items.

**Comment by manup** [comment]
Thanks, it's hard to keep track with all the Tuya devices. I think we have a duplicate here and this TRV is already supported by https://github.com/dresden-elektronik/deconz-rest-plugin/pull/6896

@Smanar can you please check?

**Comment by Smanar** [comment]
Ha yes, Have found it https://github.com/dresden-elektronik/deconz-rest-plugin/blob/master/devices/tuya/_TZE200_TS0601_trv.json

```
  "manufacturername": ["_TZE200_bvu2wnxz", "_TZE200_6rdj8dzm", "_TZE200_gd4rvykv"],
  "modelid": ["TS0601", "TS0601", "TS0601"],
```

@KodeCR I m sorry, your DDF is fine, have compared with the other one, there are same, but another one was merged before yours.

**Comment by manup** [comment]
Closing for now since the device is already handled by `tuya/_TZE200_TS0601_trv.json`, sorry that it was detected so late.

**Pull request closed without merging**
