### PR TITLE
Fix LIDL smart plug consumption reporting 0

### PR DESCRIPTION
**Pull request by Pirionfr**
fix consumption reporting 0 because of missing semicolon

### CODE REVIEW

**Comment by manup** [comment]
Hmm sure about this? It the semicolon shouldn't make any difference here.

**Comment by Pirionfr** [comment]
I added it in my ddf and data was available in the api

**Comment by Pirionfr** [comment]
after deconz plugins  restart is home assistant it's doesn't increase over the api. so you are right

**Comment by Pirionfr** [comment]
image
but in the API
image

**Comment by mattreim** [comment]
Please try this: "Item.val = Attr.val * 10;"

I think it's because of the small "i".

**Comment by Pirionfr** [comment]
it's as been fixes in last beta version.

**Pull request closed without merging**
