### PR TITLE
DDF update the Tuya air quality sensor _TZE200_dwcarsat with "state/measured_value"

### PR DESCRIPTION
**Pull request by Smanar**
See https://github.com/dresden-elektronik/deconz-rest-plugin/pull/6673

Create 6 sensors :
- ZHAHumidity
- ZHAtemperature
- ZHAAirquality
- ZHAFormaldehyde
- ZHACarbonDioxide
- ZHAParticulateMatter

### CODE REVIEW

**Comment by manup** [comment]
Getting closer, we have the `state/measured_value` for the sensors, now respective `/devices/generic/subdevices` need to be defined.

In addition to `cap/measured_value/unit` it makes sense to add `cap/measured_value/dimension` for the benefit of generic clients (I stole "dimensions" from [[2]](https://www.openhab.org/docs/concepts/units-of-measurement.html) not sure if that's a good name).

| Sensor type | cap/measured_value/dimension                                 | cap/measured_value/unit |
| ------------------------- | ------------------------------------------------------------ | ----------------------- |
| ZHAFormaldehyde | "Formaldehyde" [[3]](https://en.wikipedia.org/wiki/Formaldehyde) | PPM                     |
| ZHACarbonDixide | "CO2" [[4]](https://en.wikipedia.org/wiki/Carbon_monoxide) | PPM                     |
| ZHAParticulateMatter | "PM25"  <br />For particulate matter of 2.5 micrometers and smaller [[6]](https://www.epa.gov/pm-pollution/particulate-matter-pm-basics) | ug/m\^3                   |
| ZHAAirQuality             | "TVOC" (total volatile organic compounds) [[5]](https://learn.kaiterra.com/en/resources/understanding-tvoc-volatile-organic-compounds) | PPB                     |

The `ZHAParticulateMatter` is weird one to me, because are PM25 and PM10 sufficient to be useful? From what I read it should be interesting to know what exactly is measured (smoke particles?) if that is even possible and described for the products giving such values. Looking at Home Assistant [[1]](https://developers.home-assistant.io/docs/core/entity/sensor/#available-device-classessuch) such details aren't exposed?

For now it's ok to keep the `state/airqualityppb` item in `ZHAAirQuality` sensor, but I propose to deprecate it and add `state/measured_value`  to the sensor as shown in the table above (TVOC) for streamlining.

References: 

[1] https://developers.home-assistant.io/docs/core/entity/sensor/#available-device-classes
[2] https://www.openhab.org/docs/concepts/units-of-measurement.html
[3] https://en.wikipedia.org/wiki/Formaldehyde
[4] https://en.wikipedia.org/wiki/Carbon_monoxide
[5] https://learn.kaiterra.com/en/resources/understanding-tvoc-volatile-organic-compounds
[6] https://www.epa.gov/pm-pollution/particulate-matter-pm-basics

**Comment by Smanar** [comment]
Code updated with last comment, the device now create 6 entries.

**Comment by SwoopX** [comment]
@manup I wouldn't describe the "what is actually measured" as dimension. Why don't we stick to the standard here also and name it "substance_measured" or just "substance". Not a perfect fit, admittedly, but I guess universal enough to catch the idea (now saving my popcorn for Erik's 20 Cents 🙂 )

Happy to put `state/airqualityppb` aside when the time's ready to be somehow consistent. Still, however, dislike the idea to introduce 32 new sensor types, as they all look alike and this is not exactly generic. But as the dice is already cast, I'll probably have to find a way to life with it 🙂

**Comment by manup** [comment]
> @manup I wouldn't describe the "what is actually measured" as dimension. Why don't we stick to the standard here also and name it "substance_measured" or just "substance". Not a perfect fit, admittedly, but I guess universal enough to catch the idea (now saving my popcorn for Erik's 20 Cents 🙂 )

That's my lack of imagination :D I just stole "dimension" from OpenHab `cap/measured_value/substance` sounds indeed better, but is pm2.5 a substance? Perhaps "subject" or even "what" will do, but I can also live with "substance".


> Happy to put `state/airqualityppb` aside when the time's ready to be somehow consistent. As for `ZHAParticulateMatter`, standard defines, we do I'd say. Still, however, dislike the idea to introduce 32 new sensor types, as they all look alike and this is not exactly generic. But as the dice is already cast, I'll probably have to find a way to life with it 🙂

Yeah for now it's fine to keep `state/airqualityppb` (also in for this PR in addition to `state/measured_value`), deprecate at some point and remove in a year or so.

Ha yes, count me in the team for less sensor types, I think it's a tradeoff since different clients have different approaches how to deal with the API. The way I'll treat this in a generic manner is to mostly ignore the type in the (new) UI and check for `state/measured_value`, e.g. like following pseudo code:

```
for s in sensors:
    if s.state.measured_value     // as good as ZHAMeasurement
        print  s.cap.measured_value.substance
        print  s.state.measured_value
        print  s.cap.measured_value.unit
```

**Comment by manup** [comment]
@Smanar  thanks for the updated DDF from what I see the following should be done before merging:

* Add new sensor types like `$TYPE_CARBONDIOXIDE_SENSOR` to  `devices/generic/constants.json`.
* Use the `$....` constant values in the DDF for `"type"` field (it works without doing that, but I'd like to use constants for consistency for now).
* Add `cap/measured_value/min` and `cap/measured_value/max` items with respective values.
* The ZHAFormaldehyde has PPM not PPB (if I understand it right)

For the "dimension" item we should first decide on a good name, "substance", "subject" or "what" are on the table currently. Ideas here are welcome.

**Comment by Smanar** [comment]
PR updated.
Except for `cap/measured_value/min` and `cap/measured_value/max` because It is useless for this device. Third app will just display the value gived by the device they don't care of min or max

**Comment by Zehir** [comment]
@Smanar you added a `cap/measured_value/dimension` in the subdevices (subdevice1.schema.json) files but there is no item file for it (resourceitem1.schema.json). Could you please add it ?

**Comment by Smanar** [comment]
Added here https://github.com/dresden-elektronik/deconz-rest-plugin/pull/7146

**Comment by BabaIsYou** [comment]
> Except for `cap/measured_value/min` and `cap/measured_value/max` because It is useless for this device

This could be a derivated way to detect if the device is faulty if the measured value is out of range for instance ;-)

**Comment by BabaIsYou** [comment]
> For the "dimension" item we should first decide on a good name, "substance", "subject" or "what" are on the table currently. Ideas here are welcome.

From Zigbee specification it's called "substance" : https://github.com/dresden-elektronik/deconz-rest-plugin/pull/6673#issuecomment-1510537352

**Comment by Smanar** [comment]
Ok I will update dimension for substance on the PR

**Comment by BabaIsYou** [comment]
> For now it's ok to keep the `state/airqualityppb` item in `ZHAAirQuality` sensor, but I propose to deprecate it and add `state/measured_value` to the sensor as shown in the table above (TVOC) for streamlining.

TVOC is a specific case as it's not so "standadized" as other "real" substances, for mention, all devices based on Sensirion SEN54 sensor like IKEA VINDSTRYKA don't report a measure of a substance but a kind of specific index : https://github.com/dresden-elektronik/deconz-rest-plugin/pull/6673#issuecomment-1572665255 , with a min and a max clearly identified into specifications.

**Pull request merged**
