### PR TITLE
DDF for Moes ZM-105-M 1 gang dimmer (_TZE204_dcnsggvz)

### PR DESCRIPTION
**Pull request by dmichalski**
adds DDF for Moes ZM-105-M 1 gang dimmer (_TZE204_dcnsggvz).

### CODE REVIEW

**Comment by dmichalski** [comment]
resolves #7703

**Comment by Smanar** [comment]
> Error: The device is missing the device definition (subdevice1.schema.json) for the type "$TYPE_DIMMER_SWITCH"

OK, I will ask what is missing here.

**Comment by Smanar** [comment]
Ok I think it's because there is no `devices\generic\subdevices\dimmer_switch.json`
So 2 solution , use in the DDF `"type": "$TYPE_DIMMABLE_LIGHT",` or create a devices\generic\subdevices\dimmer_switch.json with mimic the `devices\generic\subdevices\dimmable_light.json`  for exemple

**Comment by Smanar** [comment]
>  Error: 1 validation error in file devices/moes/Moes_ZM-105-M_1_gang_dimmer.json at subdevices/0/items
> Error: The device should have the item "state/alert" because it is mandatory for devices of type "$TYPE_DIMMER_SWITCH"

Sorry my bad, can you remove this line on the new "dimmer_switch.json" file ?

`"state/alert",`

**Pull request merged**
