### PR TITLE
Enable binding and reporting for Vimar mains powered devices

### PR DESCRIPTION
**Pull request by SwoopX**

### CODE REVIEW

**Comment by Mimiix** [comment]
@SwoopX Does this PR Enable Power Measuring?  Or does this need some work after initial support?

**Comment by SwoopX** [comment]
@Mimiix no, it doesn't, since there's nothing to measure. It enables binding and reporting for `/lights` resources.

**Comment by Mimiix** [comment]
@SwoopX The website suggests that it does. But you have no reason to believe the actuator does report power measurement?

**Comment by SwoopX** [comment]
@Mimiix simple as that: no simple metering or electrical measurement, no manufacturer specific clusters.

**Comment by LeoeLeoeL** [comment]
I have a Vimar "On_Off_Switch_v1.0" (19592).
In the "On/Off"cluster, the 2 commands ON, OFF work as the TOGGLE command.
If the lamp is off and I press OFF the lamp switches on.

**Comment by rafuz** [comment]
I have asked for device integration of VIMAR 19592 #3639  . I am experiencing the same beahaviour. Both Turn ON and Turn OFF commands acts as TOGGLE

**Pull request merged**
