### PR TITLE
Add order to moisture_sensor.json

### PR DESCRIPTION
**Pull request by Zehir**

### CODE REVIEW

**Comment by BabaIsYou** [comment]
Just for interest, what does "order" is for ?

**Comment by Zehir** [comment]
> Just for interest, what does "order" is for ?

Don't really know but in the validator I mark it as required. I think it's for the GUI in the DDF editor list

**Comment by manup** [comment]
Ahh sorry didn't see the PR in time, already fixed by #7038

**Comment by Zehir** [comment]
no problem, I will close this one @manup

**Pull request closed without merging**
