### PR TITLE
DDF for various Tuya TRVs

### PR DESCRIPTION
**Pull request by Smanar**
See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6856

- Product name: Hama Smart Radiator Thermostat
- Manufacturer: _TZE200_h4cgnbzg
- Model identifier: TS0601

and clones

> "manufacturername": ["_TZE200_h4cgnbzg", "_TZE200_exfrnlow", "_TZE200_9m4kmbfu", "_TZE200_3yp57tby", "_TZE200_9gvruqf5", "_TZE200_zr9c0day", "_TZE200_0dvm9mva"],

### CODE REVIEW

**Comment by DerOetzi** [comment]
Can you recheck my already merged PR, which I did some weeks ago to get the TRV work: https://github.com/dresden-elektronik/deconz-rest-plugin/pull/6690 is this still neccassary with your change or should it be reverted?

**Comment by Smanar** [comment]
Can keep both.
With your code change, some device will be able to work with legacy code.
Other will work with DDF, the previous user have issue with the legacy code because a new manufacture number if I m right.
There is so much clones all can't work with legacy code.

**Comment by cagnulein** [comment]
is this somehow releated to https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6269 ?

**Comment by Smanar** [comment]
About "_TZE200_2ekuz3dz" ?

This DDF is for ["_TZE200_h4cgnbzg", "_TZE200_exfrnlow", "_TZE200_9m4kmbfu", "_TZE200_3yp57tby", "_TZE200_9gvruqf5", "_TZE200_zr9c0day", "_TZE200_0dvm9mva"],

Haven't checked others.

**Comment by manup** [comment]
The "manufacturername" and "modelid" arrays seem to be of different lengths? Otherwise the PR looks fine.

**Comment by Smanar** [comment]
Right, have corrected.

**Pull request merged**
