### PR TITLE
Add sensitivity and selftest for Xiaomi smoke and gas sensor

### PR DESCRIPTION
**Pull request by SwoopX**
See #5210.

This PR adds `RConfigSensitivity` and `RConfigSelfTest` to the Honeywell smoke and gas sensors.

The selftest will be a hit and miss for the smoke sensor, as it doesn't give any kind of response or updates any attribute value (battery powered). As it also mac polls just every 15 secs (instead of the usual 7.5, a quite remarkable deviation), delivery of the command cannot be ensured. The gas sensor reacts instantly (mains powered). For the value to return to `false` after issuing a selftest, a 3 seconds timer is used.

Sensitivity can be handled better. For the smoke sensor, the command is retried every 10 secs until the corresponding attribute holding the sensitivity value is successfully read. The same scale for the allowed values and the meaning is applied as for the Hue motion sensor (0 - low, 1 - medium, 2 - high).

Additionally, the tamper state is removed, as both devices do not support it anyway. They have also been excluded from the IAS enrollment process, as they do not comply with the zigbee specs in this regard, so the devices do not get hammered with unnecessary requests (will be marked as enrolled).

### CODE REVIEW

**Comment by Prior99** [comment]
Awesome. Will this also enable the siren?

**Comment by SwoopX** [comment]
Afaik, there isn't any capability to do this, so no.

**Comment by 7leman7** [comment]
Sorry for the noob question, but is there any way to get this working prior to merge into official deconz release (e.g. by manually copying certain files)?

**Comment by SwoopX** [comment]
Sure, you can compile the corresponding branch anytime and exchange the original plugin with the compiled version.

**Comment by jip67** [comment]
I’m not shure, but I think it will be available in the next beta release. Probably in September. I’m also a noob so maybe someone can confirm this?
Regards, 

Remi

**Comment by 7leman7** [comment]
> Sure, you can compile the corresponding branch anytime and exchange the original plugin with the compiled version.

Thanks for the quick response, compiling etc. is way beyond my understanding level currently, but I guess I'll have to educate myself.

As I'm running deConz as HA OS add-on I guess I won't be able to put my hands on beta releases unfortunately...

**Comment by RealKanashii** [comment]
> Just wanted to bump this - I guess this functionality should be already merged in deCONZ 2.12.6, but how exactly do I access sensitivity configuration and trigger self test?

Doesn't seem merged in the master ...

**Comment by SwoopX** [comment]
Replaced by #6245

**Pull request closed without merging**
