### PR TITLE
DDF add item file for cap/measured_value/substance

### PR DESCRIPTION
**Pull request by Smanar**
See https://github.com/dresden-elektronik/deconz-rest-plugin/pull/7121

### CODE REVIEW

**Comment by SwoopX** [comment]
Wasn't that item supposed to be called `cap/measured_value/substance`?

https://github.com/dresden-elektronik/deconz-rest-plugin/pull/7121#issuecomment-1650537418

**Comment by Smanar** [comment]
IDK, it make no difference for me.
I have started the previous PR with "dimension", but I can change it if you prefer ?

**Comment by Smanar** [comment]
Updated for substance

**Comment by manup** [comment]
That was my question in another PRs comment. I agree that "dimension" is a bit meh, but keep in mind that measured value is not all about substances, e.g. **°C** for temperature isn't a substance.

I'd prefer a generic word here, otherwise it feels again like the *Window Covering* devices under a `/lights` thing to me.

Ideas?

**Comment by ebaauw** [comment]
The physics term for what you're measuring: quantity (_grootheid_ in Dutch; _Größe_ in German, _quantité_ in French).

As opposed to how you express a measured value: unit (_eenheid_ in Dutch, _Einheit_ in German, _unité_ in French).

**Comment by manup** [comment]
`quantity` is perfect from what I read on Wikipedia, Dutch version is pretty cool too :)

https://en.wikipedia.org/wiki/List_of_physical_quantities

Everybody ok with `cap/measured_value/quantity` ?

**Comment by SwoopX** [comment]
No? You might have totally lost me on this one, but were discussing the "what", not the "how much"?

**Comment by ebaauw** [comment]
In physics, the “what” is called “quantity”, see the Wiki that Manu linked.

**Comment by SwoopX** [comment]
Sodium is the **name** a chemical element, it is **what** will serve as an example here. Sodium has defined SI defined base quantities, e.g. a _mass_ or an _amount of substance_.
I assume we do all agree that we already use the base quantity amount of substance aka measured value, but we want to communicate measured value of what or which chemical element or which substance.

Haven't seen any chemical element been defined as quantity, but maybe I've overlooked it.

**Comment by ebaauw** [comment]
> Haven't seen any chemical element been defined as quantity 

Neither have I.  Nor have I seen any sensors that measure a chemical elements.  Sensors measure quantities like the density or level of that element.  CO2 is a chemical element; CO2 level is a quantity, typically expressed in ppb; CO2 density would be another quantity, typically expressed in um/m3.

> I assume we do all agree that we already use the base quantity amount of substance

The amount of CO2 would be yet another quantity, typically expressed in mol.  I haven’t seen any sensors for that.

I suppose we could split quantity (what) vs substance (of what) into separate attributes.  That would also help with air temperature vs water temperature vs device temperature (although it might be a stretch to see a device as “substance”), or mains voltage vs battery voltage.

**Comment by SwoopX** [comment]
I guess we're pretty close to each other

> I suppose we could split quantity (what) vs substance (of what) into separate attributes

This is what I'm arguing, and only the **of what** part. We're here with the Concentration Measurement cluster only, which lists something like 32 chemical elements or organic/chemical compounds (primarily). Zigbee standard calls the **of what** "substance measured", the suggestion in PR https://github.com/dresden-elektronik/deconz-rest-plugin/pull/7121 was to call it "dimension", which I dislike and do not feel appropriate. Even the SI base quantity "amount of substance" references substance, so I'd suggest we just call it like that

grafik

For anything else related to quantities (**what**), be it to call it generically "quantity" or name whatever as a base quantity or anything even more specific, you most likely get an instant full ACK from me 🙂

**Comment by manup** [comment]
I'm still a bit lost here. So from my understanding if we go with `cap/measured_value/substance` it must be restricted to actual substances. For non substances like "temperature" this item must not be added, we can later on think of adding additional `cap/measured_value/quantity` if needed if the sensor "type" isn't enough (not a high priority currently but I'd like to have something like that later on for the UI part).

Would that be ok?

**Comment by BabaIsYou** [comment]
Sorry if my previous post may have added to the confusion. I reviewed it in order to remove all that was humorous or not factual which may not go well all the time... ;-)

**Pull request merged**
