### PR TITLE
Fix loading of DDFs due constants.json race

### PR DESCRIPTION
**Pull request by manup**
Stupid beginner mistake. The JSON files are read in arbitrary file system order. Which is ok except for the `constants.json` which need to be read first in order to determine if a DDF should be loaded.

### CODE REVIEW

**Comment by ebaauw** [comment]
Shouldn’t the relevant constants be included in the bundle?

**Comment by Zehir** [comment]
> Shouldn’t the relevant constants be included in the bundle?

They are, the issue is for the not bundled DDF

**Comment by ebaauw** [comment]
> The JSON files are read in arbitrary file system order

Makes you miss the MS-DOS days where you could sort the directory entries on disk.

**Comment by gibsganich** [comment]
Hi all,
I would guess I am not the only one still facing the issue from subject. My hue wall switches (RDM001) do not work proper since upgrade to 2.27. same issue is still present in 2.28.1.
Therefore I am still running 2.26.3.
Refer with your comment, please.
Thanks

**Pull request merged**
