### PR TITLE
RE: DDF for Tuya trv: Essentials, Revolt, Siterwell, Nedis...

### PR DESCRIPTION
**Pull request by mattreim**
Reopened #7640

My test device: 
Essentials 12011
Essentials 12011

The information is from the following page [zha-device-handlers](https://github.com/zigpy/zha-device-handlers/discussions/1084).

Tuya-thermostat

Phoscon:
Thermostat

### CODE REVIEW

**Comment by mattreim** [comment]
Hey @Smanar, the first error has been fixed and the next one is coming.

**Comment by Smanar** [comment]
Me too, I have checked your json, no typo on my side, it work

@Zehir what is the json problem ?

**Comment by Zehir** [comment]
Hello @Smanar , it's not the json format the issue, I need to update the error message.

The correct error is : `There is no generic file for config/setvalve`

**Comment by mattreim** [comment]
I had already done a PR there. Should I open it again?

**Comment by Zehir** [comment]
@manup @SwoopX Any idea about that ?

**Comment by mattreim** [comment]
But with "public: true" it works and I can also control it externally.

**Comment by Smanar** [comment]
>There is no generic file for config/setvalve

@mattreim you mean a json file in devices\generic\items called config_setvalve_item.json with this contain
```
{
  "schema": "resourceitem1.schema.json",
  "id": "config/setvalve",
  "datatype": "Bool",
  "access": "RW",
  "public": true,
  "description": "XXXXXXXXXXXXXXXXXXXxx.",
  "default": false
}

```

**Comment by mattreim** [comment]
@Smanar Please take a look at [#7614](https://github.com/dresden-elektronik/deconz-rest-plugin/pull/7614). I reopened it.

**Comment by Smanar** [comment]
Ha yes ...
So wich one name you want instead of `config/setvalve` @SwoopX and @manup 

Or he can give up and just remove this field from his DDF ?

**Comment by SwoopX** [comment]
> @manup @SwoopX Any idea about that ?

@Zehir Well, the json file for that item is indeed missing and was apparently forgotten during its introduction

**Comment by mattreim** [comment]
`config_setvalve_item.json` is now merged.

**Comment by Zehir** [comment]
> @Zehir `config_setvalve_item.json` is now merged.

Then you need to rebase this PR on the latest commit from the main branch

**Comment by mattreim** [comment]
@Zehir Now comes the next error

**Comment by Zehir** [comment]
> @Zehir Now comes the next error

It's not related to this PR but there is issue on the main branch, checking with other devs. Maybe related to #7961

**Comment by Zehir** [comment]
Fix was added in https://github.com/dresden-elektronik/deconz-rest-plugin/pull/7979

**Comment by mattreim** [comment]
Funny, now there are three #7979 #8025 #8026

**Comment by mattreim** [comment]
Now it works, thank you all.

**Comment by mattreim** [comment]
@Smanar Unbelievable now it's broken again and now what?

**Comment by Smanar** [comment]
Arf, sorry , it's because this PR https://github.com/dresden-elektronik/deconz-rest-plugin/pull/8021
He have modified all files, and yours too.
But the change is minimal, I think it will be easy to correct it, the PR just changes synthax.

Clic on the "Resolve Conflits" button, it will open a text editor on the browser with both version (the master and yours), just correct the problematic lines.

**Comment by mattreim** [comment]
Unfortunately the "Resolve Conflits" button is grayed out. Now there are only two options: I open a new PR again or someone (e.g. @manup) with write rights deletes this file.

`devices/tuya/_TZE200_hhrtiq0x_nedis_trv.json`

**Comment by Smanar** [comment]
And if you try to update your branch ? From your fork, the green button with "<> code".
But the procedure is not easy, it will make a new branch, a PR to your own fork, ect ....

Deleting the file will not work, because if the file is deleted, your PR will be not able to delete it too (Your PR delete this json and create a new one)

**Pull request closed without merging**
