### PR TITLE
Improve ZHADoorlock device

### PR DESCRIPTION
**Pull request by Smanar**
This code:
- move the doorlock stuff in doorlock.cpp file
- add the field "state/doorstate" with value open/closed/error jammed/error forced open/error unspecified
- add the field "state/notification" with some information like "source:keypad, code:Unlock, pin:0"
- add a field "state/pin" for pin management

### CODE REVIEW

**Comment by Smanar** [comment]
For Pin management I m using state/pin and not config/pin, because the work need to be done by the third app, there is no "get all pin" command, and thoses kind of device realy don't like request spamming.

Can use GET and DELETE with
`/api/{apikey}/sensors/{sensorid}/state/pin/{userid}`

Can use PUT with
`/api/{apikey}/sensors/{sensorid}/state/pin`
and the body
`{"id":4,"type": X, "status":Y, "code":"YYYYYY"}`

**Comment by manup** [comment]
Cool, I like that the door lock code moved into a separate file. I'm going to get a Yalelock for testing myself. For the PIN security we still need to find a way which works for all clients, I guess it would be good to create a dedicated issue for that and get discussion and ideas how to approach this.

**Comment by zeiphon** [comment]
@manup did you end up getting a yale lock for testing?

**Comment by bjornomy** [comment]
@Smanar this looks very promising. Is there anything I could help with? I have an ID Lock 150 where I would like to use the set/get pin functionality and maybe 'Door opened by user x' or whatever it may be.
I've seen people implementing this (lock) in Zigbee2Mqtt, and I might be able to get some details from them, if needed.

**Comment by Smanar** [comment]
If I m right the "ID Lock 150" is alreadu in the code ?
This Pr and the key pad one https://github.com/dresden-elektronik/deconz-rest-plugin/pull/4758#issuecomment-876679000 are in the todo list, it s for that they was recently updated, with some luck we will have them in the future PR validation session.

**Comment by bjornomy** [comment]
Ahh, sorry, I might have been somewhat unclear.

As far as I understand, this PR improves the generic ZHADoorlock basis that all Zigbee locks could use as a representation of the component. ZHADoorlock is then the object which is serialized into JSON when you GET /api/<key>/[sensor|light]/<id>, correct?

It seems to me that this PR adds at least the ability to read out both 'locked/unlocked' and 'open, closed, jammed', which the last of I can't get through the REST API.

Since my lock has the correct cluster and state fields (0x0101 -> 0x000 - 0x0003), I was simply thinking I could test, or otherwise look through the locks implementation in Zigbee2Mqtt to maybe get some implementation hints towards other useful and generic functionality.

**Comment by Smanar** [comment]
ZHAdoorlock is already in the code, but yes, the actual version miss some feature like the state/doorstate or the state/notification.
Thoses one are on this PR, and if you have a linux machine with full OS you can test this PR, it was updated recently so it don't miss lot of chnages.

**Comment by manup** [comment]
Small update: I got a Danalock V3 now for testing and will review and test the code after the next stable release.

**Comment by wvuyk** [comment]
@manup 

Are there any plans to implement pin code management possibilities on the Yale lock keypads (and others too I imagine)? I have a customer who would like to implement the zigbee version of Yale lock as the responbse seems to be a lot better then zwave versions. But he needs user (pin) management to have its tracks correct?

Wim

**Comment by amaino** [comment]
Really would like to have PIN management through the REST api. I have a cleaner coming by every second week and want to create a one time pin automatically for him in the morning of the day.

Is there anything I can do to help this PR to go through?

**Comment by dtd** [comment]
Any updates on progress on this PR? Would really love to have the pin management.

**Pull request closed without merging**
