### PR TITLE
Enhancements and add various devices

### PR DESCRIPTION
**Pull request by Smanar**
- Correction Legrand power consumption module https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2456
- Add Legrand motion sensor https://github.com/dresden-elektronik/deconz-rest-plugin/issues/883#issuecomment-612509192
- Add Legrand double switch https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2674
- Add Legrand switch module https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2720
- Improving Profalux support https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2739

Livolo was removed, not finished.

### CODE REVIEW

**Comment by manup** [comment]
Hey @Smanar thanks a lot for the PR. I've merged the other PR's but now this one needs to be updated, can you please rebase the PR on the recent master branch?

**Comment by Smanar** [comment]
I m on it, pls don't merge for the moment, correcting bugs.

**Comment by Smanar** [comment]
Ok, done, it compile.

**Comment by manup** [comment]
Thanks :) so its ready for merge now?

**Comment by Smanar** [comment]
Yep

**Pull request merged**
