### PR TITLE
LIDL remote, Trådfri shortcut button

### PR DESCRIPTION
**Pull request by ebaauw**
See #3829 and #3495.

### CODE REVIEW

**Comment by ebaauw** [comment]
With the latest commit, the following LIDL devices should have regular `manufacturername` and `modelid` values, as mentioned in the manuals.  I you previously paired any of these devices, it should be enough to re-read the _Basic_ cluster attributes, to get the proper values.

device | _Manufacturer Name_ | _Model Identifier_ | `manufacturername` | `modelid`
-- | -- | -- | -- | --
LED bulb (GU.10) | `_TZ3000_el5kt5im` | `TS0502A`  | `LIDL Livarno Lux` | `HG06492A`
Remote Control | `_TYZB01_bngwdjsr` | `TS1001`  | `LIDL Livarno Lux` | `HG06323`
RGB lamp (E27) | `_TZ3000_dbou1ap4` | `TS0505A`  | `LIDL Livarno Lux` | `HG06106C`
Smart USB Extension Lead (EU) | `_TZ3000_1obwwnmq` | `TS011F`  | `LIDL Silvercrest` | `HG06338`
Xmas light strip | `_TZE200_s8gkrkxk` | `TS0601`  | `_TZE200_s8gkrkxk` | `TS0601`

At the request of @Thomas-Vos, I didn't change the Xmas light strip, not to break Hue Essentials.  Also, the manual doesn't mention a model ID for the light strip (only for the power adapter).

**Comment by ebaauw** [comment]
Refactored the translation of Tuya-like _Manufacturer Name_ to `manufacturername` and `modelid`.  It's now based on a translation table, `lidlDevices[]`.  Not sure if the scheme is applicable to Tuya devices as well, but this is definitely more maintainable then whitelisting the values "everywhere".  Table is checked through `getLidlDevice()` and `isLidlDevice()` in `addLightNode()` and `addSensorNode()`, and in `updateLightNode()` and `updateSensorNode()`, when receiving _ManifacturerName_ or _ModelIdentifier_.

**Comment by enjikaka** [comment]
This doens't seem to be working? I see it in the deconz VNC app, but in Phoscon it doens't find it under "Add new switch" with either IKEA or Other as vendor... deCONZ version 2.9.3 on Home Assistant

**Comment by Mimiix** [comment]
@enjikaka It does work for other users so i suspect something else.  Please open a new user question with logs and atleast a screen of the deCONZ vnc map.

**Comment by lukecarbis** [comment]
I have this same problem. Phoscon doesn't find it under "Add new switch" (tried adding as "other" since there was no option for the Shortcut button, only Dimmer and Remote Control). I'm also using Home Assistant, version 2.9.3.

The Shortcut button DOES show in VNC, and also in Home Assistant. After double checking, it does not show on Phoscon under Switches (or anywhere else).

Screen Shot 2021-03-04 at 15 45 31

Screen Shot 2021-03-04 at 15 51 12

**Comment by SwoopX** [comment]
This is all good. Please note that deconz != Phoscon. The corresponding issue for the Phoscon repo is linked above.

**Comment by enjikaka** [comment]
I've got the exactly same situation as @lukecarbis! I do get the buttons battery status as an entity in Home Assistant through, but nothing more. Empty in Phoscon and deCONZ VNC looks the same way, except from showing the battery too: 
Skärmavbild 2021-03-04 kl  11 04 08

**Comment by Mimiix** [comment]
@enjikaka  @lukecarbis  You should be checking deconz.event in HA. 

If it's in deconz it is supported / added. 


**I'm locking this PR as it's finished and it's not the place to ask for support. If you have questions, feel free to open a user question issue.**

**Pull request merged**
