### PR TITLE
DDF for Tuya trv: Essentials, Revolt, Siterwell, Nedis...

### PR DESCRIPTION
**Pull request by mattreim**
My test device: 
Essentials 12011
Essentials 12011

The information is from the following page [zha-device-handlers](https://github.com/zigpy/zha-device-handlers/discussions/1084).

Tuya-thermostat

### CODE REVIEW

**Comment by mattreim** [comment]
windowopen and setvalve don't work yet.

**Comment by mattreim** [comment]
With these settings setvalve seems to be working again.

setvalve

**Comment by mattreim** [comment]
I can also share the DDF and assign it to the manufacturer.

**Comment by Smanar** [comment]
If I m right their table mean some device use a quirk "site 1" and other a quirk "site 2" nope ?
So it mean there is at least 2 versions for this hardware with different dpid.

**Comment by Smanar** [comment]
BTW , why this PR is still in waiting list ?

**Comment by Smanar** [comment]
Hello, IDK why this PR is still in waiting list, but it's probably because of the conflicting files.
I can't solve the conflict on my side.

**Comment by mattreim** [comment]
Actually the old file should be replaced.

**Comment by Smanar** [comment]
I think it's because the conflicting files.
You have a button called "Resolve conflict", with some luck you have just a line te remove.

Else don't loose your time, close this PR and re open it but AFTER having updated your fork (and same if you don't know how to do, just delete it and restart from scratch)

**Comment by mattreim** [comment]
I don't have write permissions and resolve conflict cannot be selected. Now I'll probably open a new PR.

**Pull request closed without merging**
