### PR TITLE
Vendor codes

### PR DESCRIPTION
**Pull request by ebaauw**
I found a [new source](https://github.com/wireshark/wireshark/blob/master/epan/dissectors/packet-zbee.h) for ZigBee manufacturer codes, which contains the missing codes that we couldn't find earlier.  There are some mismatches between this list from WireShark and our current list, which I've highlighted in this PR.  I haven't marked any literal differences, like names with or without "Technology" in them, or "DDEL" vs "Dresden".  I think the mismatches I marked are mostly OEM vs commercial names, like "Shenzhen" vs "Sunricher", or "Jiuzhou" vs "Paulman".

I also sorted the list, once again, on manufacturer code.

Main reason I've created this PR is to start/continue the discussion how we want to deal with these definitions.  Should we continue to maintain them ourselves, or should we include/re-use the WireShark list?  Should we continue to use our own names, or do we want to use exactly the same names as the WireShark list?  Of course, I have no idea what the official status of the WireShark list is.

Pending this discussion, I haven't yet (?) removed any of the numeric or (possibly) wrong names, and I haven't yet (?) updated the rest of the code to use the new names.

### CODE REVIEW

**Comment by SwoopX** [comment]
Well, I'd say it would generally make more sense to use OEM names to keep it neutral. We just had a comparable discussion on the macprefic in PR #2239.

**Comment by ebaauw** [comment]
Thanks.  Yeah, I saw the discussion, but couldn't find it anymore.  I guess I didn't look hard enough ;-)

**Comment by Smanar** [comment]
For 0x1021 it's Legrand, vantage is a part of legrand, but their last device have nothing to see with vantage.

**Comment by SwoopX** [comment]
> Thanks. Yeah, I saw the discussion, but couldn't find it anymore. I guess I didn't look hard enough ;-)

Lazyness all over the place :P

> Just for information , for 0x1021 it's Legrand, vantage is a part of legrand, but their last devices (netatmo gamme) have nothing to see with vantage.

What is that saying about rules and exceptions in english?

**Comment by ebaauw** [comment]
I'm no native speaker, but in Dutch we have a saying which translates to: "the exception confirms the rule".

**Comment by SwoopX** [comment]
Right, Didn't want to literally translate from German, but that's it.

**Comment by ebaauw** [comment]
Thanks for merging, @manup.

Just to make sure: did you review the changes to the rules evaluation (#2148)?  I've been running that for nearly a week in my production network, and I don't think I've missed any rule triggering during that time.  The DBG_INFO_L2 message when invoking `handleRuleEvent()` for `/config/localtime` every second might be a bit exaggerated, though.

**Comment by manup** [comment]
Yes I've checked the code looks sane to me. I'm running it with some rules for motion sensors and various switches without problems. The debug print can be removed later on or guarded with `DBG_IsEnabled()` to not effect performance.

**Pull request merged**
