### PR TITLE
Fix battery drain and add switch variants to _TZ3000_TS044_4gang_remote.json

### PR DESCRIPTION
**Pull request by sinus61**
Added devices and fix battery drain, follow this closed PR https://github.com/dresden-elektronik/deconz-rest-plugin/pull/6744

### CODE REVIEW

**Comment by sinus61** [comment]
@manup @pavime
Removed  _TZ3000_wkai4ga5  from this PR in button_maps.json

**Comment by sinus61** [comment]
@Smanar
Yes, but don't know what to do now. 
_TZ3000_i3rjdrwu was added from the 2gang PR, _TZ3000_abci1hiu should be added here now.

**Comment by Smanar** [comment]
@sinus61 the conflict is here

```
<<<<<<< _TZ3000_TS0044_4gang_remote.json
            "modelids": ["_TZ3000_ee8nrt2l", "_TZ3000_ygvf9xzp", "_TZ3000_t8hzpgnd", "_TZ3000_wkai4ga5", "_TZ3000_bi6lpsew", "_TZ3400_keyjhapk", "_TYZB02_key8kk7r", "_TZ3400_keyjqthh", "_TZ3400_key8kk7r", "_TZ3000_vp6clf9d", "_TYZB02_keyjqthh", "_TZ3000_peszejy7", "_TZ3000_qzjcsmar", "_TZ3000_owgcnkrh", "_TZ3000_adkvzooy", "_TZ3000_arfwfgoa", "_TZ3000_a7ouggvs", "_TZ3000_rrjr1q0u", "_TZ3000_abci1hiu", "_TZ3000_dfgbtub0", "_TZ3000_rco1yzb1", "_TZ3000_gbm10jnj", "_TZ3000_5e235jpa", "_TZ3000_sj7jbgks", "_TZ3000_w8jwkczz", "_TZ3000_dziaict4", "_TZ3000_famkxci2", "_TZ3000_itb0omhv", "_TZ3000_tzvbimpq", "_TZ3000_mh9px7cq", "_TZ3000_b7bxojrg", "_TZ3000_ufhtxr59", "_TZ3000_4upl1fcj", "_TZ3000_abci1hiu"],
=======
            "modelids": ["_TZ3000_ee8nrt2l", "_TZ3000_ygvf9xzp", "_TZ3000_t8hzpgnd", "_TZ3000_wkai4ga5", "_TZ3000_bi6lpsew", "_TZ3400_keyjhapk", "_TYZB02_key8kk7r", "_TZ3400_keyjqthh", "_TZ3400_key8kk7r", "_TZ3000_vp6clf9d", "_TYZB02_keyjqthh", "_TZ3000_peszejy7", "_TZ3000_qzjcsmar", "_TZ3000_owgcnkrh", "_TZ3000_adkvzooy", "_TZ3000_arfwfgoa", "_TZ3000_a7ouggvs", "_TZ3000_rrjr1q0u", "_TZ3000_abci1hiu", "_TZ3000_dfgbtub0", "_TZ3000_rco1yzb1", "_TZ3000_gbm10jnj", "_TZ3000_5e235jpa", "_TZ3000_sj7jbgks", "_TZ3000_w8jwkczz", "_TZ3000_dziaict4", "_TZ3000_famkxci2", "_TZ3000_itb0omhv", "_TZ3000_tzvbimpq", "_TZ3000_mh9px7cq", "_TZ3000_b7bxojrg", "_TZ3000_ufhtxr59", "_TZ3000_4upl1fcj", "_TZ3000_i3rjdrwu"],
>>>>>>> master
```

You just need to add the _TZ3000_i3rjdrwu and the _TZ3000_abci1hiu, one is on your PT but the second is on the official code and not your PR.

It take 5mn if you press the "Resolve conflict" button.
I can do it, but the last time I have tried to solve conflict on your PR I have done mistake ^^.

**Comment by Smanar** [comment]
Yep, now let's hope for manup validate this PR first to don't have new conflict again ^^

**Comment by Smanar** [comment]
>Ha ok :D so this one needs to be merged first?

Yeah, lol, it's the third time he redid the PR because of me or conflict.

**Comment by manup** [comment]
Oha hope all is good now :)

**Pull request merged**
