### PR TITLE
DDF for Tuya ZP01 motion sensor (_TZ3000_lf56vpxj)

### PR DESCRIPTION
**Pull request by ulikoenig**
Add Support for Tuya _TZ3000_lf56vpxj from here https://de.aliexpress.com/item/1005006010327384.html

### CODE REVIEW

**Comment by pepz-de** [comment]
Got the sensor today. Would be great If it will be added

**Comment by manup** [comment]
Hi, the `modelid` array need to be extended as well since this is treated as a pair to identify the device by (manufacturer name, modelid).

**Review by manup — CHANGES_REQUESTED** [review]
See validator message, the `modelid` array needs to be extended as well.

**Comment by Zehir** [comment]
@manup While resolving the validation issue I came to this and look like the new tuya name is already added from an other PR. I think we can close this one

**Comment by manup** [comment]
Good catch, yes indeed it already exists.
Closing as completed.

**Pull request closed without merging**
