### PR TITLE
Tuya Update.

### PR DESCRIPTION
**Pull request by Smanar**
Ok so with lot of help from @vegetate7 some improvements, but not all are used yet.

- Add a TRV devices https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3110
- Adding some option for TRV device, for exemple 
`curl -H 'Content-Type: application/json' -X PUT -d '{"windowopen_set":[true,20,20]}' http://IP:PORT/api/KEY/sensors/21/config`
To set windows open mode (Valve/temperature/timer).
Or low battery, but I don't find how to have 'false" as defaut value, I always have "null"
- Switch are finally working, but deconz will create always 3 entries even it s a double gang https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2879 
- Starting to add covering, need to test set level, but a remote is needed so for the moment this part is disabled.

### CODE REVIEW

**Comment by Smanar** [comment]
Tuya device need manufacture name to be reconized, and it s not possible with API actual code so I m using 2 tips
- Try to retreive information from deconz (if the user have used the read attribute.
- Try to find information on the database, so the inclusion can faild the first time (I m not freezing the code), but succed on the second one.

Tuya covering are now working open/close/stop/lift and reverse as setting.

**Comment by Smanar** [comment]
And all is working, adding 2 tuya covering, a router and an end device.

**Comment by Abbadon89** [comment]
Any reason why is not included? Atm only way to use it is moving to z2mqtt ;/

**Comment by artkrz** [comment]
Am I correct PRs created after this one got merged? WTF? This is not cool at all :(

**Comment by Smanar** [comment]
Yep, sorry.
The version 81 is a stable version with lot of improvements, the tuya code is not a "light code" so it was too dangerous to put it in a stable version.
So you will have it at the latest, at the next public version (the 15 th october) or earlier in a beta version, but I don't think thoses ones can be used on HA (only Pure Unix machine)

**Comment by artkrz** [comment]
I'm using official Docker image with Conbee2, on HA side I'm using https://www.home-assistant.io/integrations/deconz. BTW, I think this info should be here as soon as it was clear that this PR will not be merged into next beta.

**Comment by andysaab** [comment]
Sad news :( 
We`ve been waiting so long!

**Comment by Smanar** [comment]
Because the 82 was out almost in same time than the 81 (less than 2 days)
I m a little lost in all those versions.
The 81 is the last  stable, idk yet for the 82, probably a beta, but still without tuya code.

I think the PR will be validated in same time, an alpha will be available to test it (or a beta), but I m sure the HA plugin dev will not use it and will wait for the october version.

**Comment by andysaab** [comment]
We have no way, will wait.

**Comment by Abbadon89** [comment]
Funny, i can add valve to Deconz, it works with HA and more or less they working fine. 2 of them have connection (some kind of deep sleep) problem

**Comment by Smanar** [comment]
With the PR or the version 82 ?

**Comment by Abbadon89** [comment]
image
image

**Comment by gmitch64** [comment]
Does this mean that it will be added to v83? I have one of these motors and I'd like to start working with it.

G

**Comment by andysaab** [comment]
> Does this mean that it will be added to v83? I have one of these motors and I'd like to start working with it.
I`ve has update to v83 today - I can say Zigbee 3 Gang Remote TS0043 not worked :(

**Comment by Smanar** [comment]
No this code is not in the version 83 (the version that is out 13 days ago).

**Comment by gmitch64** [comment]
I'm a little confused - the latest prerelease is showing as 2_05_82_01. 

2_05_83 is showing as being tagged, and the tuya commit looks like it's been merged...

image

**Comment by Smanar** [comment]
I use the same name "tuya" for all versions ^^.

The last one was validated 2 days ago, and was called too "tuya"

**Comment by andysaab** [comment]
Today deconz updated to v2.05.84
image
Tuya devices non work yet :(

**Comment by Smanar** [comment]
I don't see tuya code in the version 84.
Have you tru to compile the code ?

84 is a stable
You will probably have the tuya code on the 85 beta (the 15th)

**Comment by andysaab** [comment]
> I don't see tuya code in the version 84.
> Have you try to compile the code ?
> 
> 84 is a stable
> You will probably have the tuya code on the 85 beta (the 15th)

Smanar, no. I wait official release.

**Comment by manup** [comment]
> I don't see tuya code in the version 84.
> Have you try to compile the code ?
> 
> 84 is a stable
> You will probably have the tuya code on the 85 beta (the 15th)

That's correct, the beta 2.05.85 will contain the code.

**Comment by gmitch64** [comment]
I've just upgraded to 2.05.85, and the Zemismart motor doesn't look right in the API when I pull the info back from with postman. I've just deleted and readded it, and this is what it comes back with. Should I open a new issues with for this, or is there an existing issue that I can update?




 "17": {
        "etag": "7ddcb3bc2148cf16578904fe6b7fcee2",
        "hascolor": false,
        "lastannounced": "2020-10-17T17:18:02Z",
        "lastseen": "2020-10-17T18:24Z",
        "manufacturername": "_TYST11_wmcdj3aq",
        "modelid": "mcdj3aq",
        "name": "Green Screen",
        "state": {
            "alert": "none",
            "on": false,
            "reachable": true
        },
        "swversion": null,
        "type": "On/Off light",
        "uniqueid": "bc:33:ac:ff:fe:68:0e:8d-01"

**Comment by gmitch64** [comment]
And it does seem to be there. The GUI is showing it as a light

image

So I can't see the window covering cluster, like I can with my curtains, but the json looks to be sensible for a covering, so I'm not sure what's up. Should I open a new issue, or is this expected behaviour?

"17": {
        "etag": "355a562a95c92252f703c6be137c10eb",
        "hascolor": false,
        "lastannounced": null,
        "lastseen": "2020-10-17T18:43Z",
        "manufacturername": "_TYST11_wmcdj3aq",
        "modelid": "mcdj3aq",
        "name": "On/Off light 17",
        "state": {
            "alert": "none",
            "bri": 0,
            "lift": 0,
            "on": false,
            "open": false,
            "reachable": true
        },
        "swversion": null,
        "type": "Window covering device",
        "uniqueid": "bc:33:ac:ff:fe:68:0e:8d-01"

@andysaab @Smanar 


G

**Comment by Smanar** [comment]
@gmitch64 no for me all is normal.
This device don't use covering cluster (welcome in tuya world ^^), but all tuya device (most of them) are using the same cluster, and still better, this cluster is invisible.

So for the moment your device can't be used with deconz, but make a try with a third app or directly the api, I think it will be fine.

**Comment by gmitch64** [comment]
I've just tried to add a new motor using 2.05.86, and it's not getting past the initial connection stages.

image

It's also not showing in Phoscon, or from a query in postman.

I've also tried to control my existing motor, and even though it seems to be there according to postman, I can't control it, other than with the RF remote control I purchased it with. I was also having issues controlling this original one with 2.05.85, but since it's actually installed and I need a ladder to get up an push the pairing button, I thought I'd get the new one set up to install and test with.

Do you want me to open a new issue, or continue here?


G

**Comment by Smanar** [comment]
Your device was missing.
I have added it on the code, if you can test it to be sure ?

If you need more explanation on how to compile the code, or if it don't work, yes, better making an issue, no one come on old pr already validated.

**Comment by gmitch64** [comment]
If you want to post the git command so I pull the correct branch (I'm not a git expert, and just want to make sure I have the correct code), I can do the test.

G

**Comment by Smanar** [comment]
To test it, you need an Unix OS, and take a look here https://github.com/dresden-elektronik/deconz-rest-plugin#install-deconz-development-package-optional-linux-only with a modification for step 1

```
git clone --branch tuya https://github.com/Smanar/deconz-rest-plugin.git
cd deconz-rest-plugin
qmake && make -j2
sudo cp ../libde_rest_plugin.so /usr/share/deCONZ/plugins

```

**Comment by gmitch64** [comment]
Thanks.
I wasn't sure of which branch to putt down. Getting a compilation error tho...

de_web_plugin.cpp:102:15: error: redefinition of ‘const quint64 silabs6MacPrefix’
 const quint64 silabs6MacPrefix    = 0x588e810000000000ULL;
               ^~~~~~~~~~~~~~~~
de_web_plugin.cpp:101:15: note: ‘const quint64 silabs6MacPrefix’ previously defined here
 const quint64 silabs6MacPrefix    = 0x588e810000000000ULL;
               ^~~~~~~~~~~~~~~~

**Comment by gmitch64** [comment]
Looking at the code, the definitions seem to be the same, so I commented out the 2nd line (102) in the code, and it's passed there. I'll let you know how it goes.

G

**Comment by Smanar** [comment]
Arf, I have removed the silabs4MacPrefix and make 2 time the silabs6MacPrefix.
Was corrected on the fork, but it seem it s not usefull for test (if you have no error about a missing silabs4MacPrefix )

**Comment by gmitch64** [comment]
That was interestingly unsuccessful.

Replaced the lib, rebooted,  and was unable to log into Phoscon - an invalid password error.
Logged in to the Pi using VNC, and saw my network like this..

image

I put the original 05.86 lib.so back in place, rebooted, and was able to log into Phoscon, and my network was back showing the way I expected in VNC.

**Comment by Smanar** [comment]
The problem was with tuya device ? I can't read the model id on your capture ?

**Comment by gmitch64** [comment]
I pulled down your updated tuya branch, recompiled, and moved over the new lib.
This time I was able to log into Phoscon.

I deleted the old device, ran a rescan, and I'm seeing the motor come in on the VNC client, but nothing is showing in Postman.

image

image

G

**Comment by Smanar** [comment]
Ok so I have checked the code again, I have missed something, but you need to have a bulb device for it ATM.

It s a long story, but to make short tuya device need 2 inclusions, 1 to write on database usefull information, but the device can be bad reconized, and a second one where deconz read the previous data to make the correct inclusion.

If it still don't work with the actual code, can you make this test :
- set phosocn in permit join
- read again the device basic attribute, cluster 0x0000, button "read"

**Comment by gmitch64** [comment]
I've just updated my local code from your branch, and I'm compiling it again. Here's the info from the info panel, just in case.

image


G

**Comment by gmitch64** [comment]
Also noticed this error in the compilation - not sure if it's relevant/important, but just in case.

specs/linux-g++ -o release/green_power.o green_power.cpp
green_power.cpp: In function ‘GpKey_t GP_DecryptSecurityKey(quint32, const GpKey_t&)’:
green_power.cpp:20:39: warning: unused parameter ‘sourceID’ [-Wunused-parameter]
 GpKey_t GP_DecryptSecurityKey(quint32 sourceID, const GpKey_t &securityKey)
                                       ^~~~~~~~
green_power.cpp:20:64: warning: unused parameter ‘securityKey’ [-Wunused-parameter]
 GpKey_t GP_DecryptSecurityKey(quint32 sourceID, const GpKey_t &securityKey)
                                                                ^~~~~~~~~~~

**Comment by gmitch64** [comment]
Also noticed this one..

tuya.cpp: In member function ‘bool DeRestPluginPrivate::SendTuyaRequestThermostatSetWeeklySchedule(TaskItem&, quint8, QString)’:
tuya.cpp:702:96: warning: unused parameter ‘weekdays’ [-Wunused-parameter]
 eRestPluginPrivate::SendTuyaRequestThermostatSetWeeklySchedule(TaskItem &taskRef, quint8 weekdays , QString transitions )


G

**Comment by gmitch64** [comment]
OK, tried several times, and it's still not including properly.

Looking at #3161 @andysaab has the same motor as me, but it looks like his is/was being included as a light, where my one seems to be including as a smart plug.

He also seems to have a different manufacturer name and  model Identifier

image

from my one

image

And mine is a ZM25TQ, as is his.
Is there any other info/testing I can do?


G

**Comment by Smanar** [comment]
There is a difference beetween your both device, his have the cluster 0x0006 and the tuya cluster is hidden, yours haven't the cluster 0x0006 but have the cluster tuya.

To create the "device" the code search for cluster 0x0006 (this is the native working mode) or tuya cluster (I think the problem is from here ^^).

The warning are not dangerous.

I have modified the code to force the device creation, even if the code don't see the tuya cluster (I think it s the problem).

Don't delete the node beetwen 2 inclusions.

If it s still not working I need the debug log during the inclusion ( 30s before up to 2 mn after)

`deCONZ --dbg-error=2 --dbg-info=2`

**Comment by gmitch64** [comment]
OK. It's still showing as a Smart Plug rather than a light. I'll do the inclusion again after breakfast with the debugging and update here. Just as a sanity check, here's the motor I'm using. So it looks the same as the one @andysaab has - at least from the outside.

image

**Comment by Smanar** [comment]
Yeah ! Exactly the same model ...

BTW, if the "plug" device is visible, do you have the device json ?

**Comment by gmitch64** [comment]
The plug is visible in the GUI via VNC, but Postman doesn't show anything sadly.


G

**Comment by gmitch64** [comment]
Now, I do have 3 of these motors (the other 2 are mounted and a pain to get to the pairing button). I paired the first one I got with either .84 or .85, and it DID pair - doesn't work via deConz though.

This is the JSON for the one that paired previously.

 "17": {
        "etag": "72a695e26aa120e91db786fe58f58d08",
        "hascolor": false,
        "lastannounced": null,
        "lastseen": "2020-10-23T17:25Z",
        "manufacturername": "_TYST11_wmcdj3aq",
        "modelid": "mcdj3aq",
        "name": "Green Screen",
        "state": {
            "alert": "none",
            "bri": 0,
            "lift": 0,
            "on": false,
            "open": false,
            "reachable": false
        },
        "swversion": "20180727",
        "type": "Window covering device",
        "uniqueid": "bc:33:ac:ff:fe:68:0e:8d-01"
    },

G

**Comment by gmitch64** [comment]
OK. Just did a git pull, and I see the code has been updated.

```
From https://github.com/Smanar/deconz-rest-plugin
   7db39a2..d90041f  tuya       -> origin/tuya
Updating 7db39a2..d90041f
Fast-forward
 database.cpp      |  8 +++++---
 de_web_plugin.cpp |  8 +++++---
 rest_sensors.cpp  | 23 ++++++++++++++++-------
 tuya.cpp          | 40 +++++++++++++++++++++++++++++++++++++++-
 4 files changed, 65 insertions(+), 14 deletions(-)

```

Copied the updated the lib file and rebooted.
Set the motor into inclusion mode (pressed the button 3 times)
Set Phoscon into inclusion mode for lights
It shows in the GUI as a Smart Plug, but nothing in Phoscon, and nothing from Postman either.
Put Phoscon back into inclusion mode for lights.
Sat at did a read on the Basic Cluster every few seconds for the 3 minute inclusion.

Still nothing showing in Phoscon or Postman.

Going to try and run the debug version now.


G

**Comment by gmitch64** [comment]
OK, I'm missing something....

/usr/bin/deCONZ --dbg-error=2 --dbg-info=2 --http-port=80

QCoreApplication::arguments: Please instantiate the QApplication object first
QXcbConnection: Could not connect to display
Aborted

**Comment by Smanar** [comment]
Try with
`deCONZ -platform minimal --dbg-error=2 --dbg-info=2 --http-port=80`

but it have worked with version 84 and 85, but not the last one ?

**Comment by gmitch64** [comment]
I've just done that, and also added 

StandardOutput=file:/home/pi/logs/deCONZ-output.log
StandardError=file:/home/pi/logs/deCONZ-error.log

into the service startup, but it didn't generate the log files. There's a whole load of data in syslog if that's of any use?
If so, is there a place I should upload it to? Or just zip it up and attach here?


G

**Comment by Smanar** [comment]
Both are working, It will depend of size I think

BTW, I have just edited my previous post 

The working is "_TYST11_wmcdj3aq"
The not working is "_TZE200_wmcdj3aq"

**Comment by gmitch64** [comment]
That's correct on the working vs non working. However, both are ZM25TQ motors. I'm guessing there was some change in the logic of the inclusion, and it's not being detected incorrectly?

G

**Comment by Smanar** [comment]
Ok find the problem, give me  10 mn

**Comment by Smanar** [comment]
Ok no bad idea, I will check your log, because I realu don't see what is missing.

**Comment by gmitch64** [comment]
Here's the syslog. 

[syslog.gz](https://github.com/dresden-elektronik/deconz-rest-plugin/files/5469391/syslog.gz)

I'll have another run one this posts.


G

**Comment by Smanar** [comment]
Ok, this time I have found.

It s an old code that I have removed, and was back because of a mistake in PR, to resume it blacklist the mac adress of this device

https://github.com/Smanar/deconz-rest-plugin/commit/7684d819ce797eefbd440a6e1ff144c580623984

**Comment by gmitch64** [comment]
OK. Did the pull

From https://github.com/Smanar/deconz-rest-plugin
   d90041f..116a6fb  tuya       -> origin/tuya
Updating d90041f..116a6fb
Fast-forward
 database.cpp      |   8 +++++-
 de_web_plugin.cpp |  17 ++++++------
 light_node.cpp    |   2 ++
 rest_sensors.cpp  |  41 +++++++++++++++++++++++++--
 tuya.cpp          | 114 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++-------------------
 5 files changed, 140 insertions(+), 42 deletions(-)

And we get a compilation error.

rest_sensors.cpp: In member function ‘int DeRestPluginPrivate::changeSensorConfig(const ApiRequest&, ApiResponse&)’:
rest_sensors.cpp:1205:33: error: expected initializer before ‘modeSet’
                         QString modeSet = map[pi.key()].toString();
                                 ^~~~~~~
rest_sensors.cpp:1206:29: error: ‘modeSet’ was not declared in this scope
                         if (modeSet == "heat") { data = QByteArray("\x00", 1); }
                             ^~~~~~~
Makefile.Release:1066: recipe for target 'release/rest_sensors.o' failed
make[1]: *** [release/rest_sensors.o] Error 1

**Comment by gmitch64** [comment]
OK. Removed rest_sensors.cpp from my local copy and did a git pull again. Clean compilation this time, not sure why I was getting an error last time.

The GUI still shows it as a Smart_Plug

image

Phoscon seems to think it's a thermostat

image

But the JSON looks respectable

  "21": {
        "etag": "3fa9464299e663f05e6eba5abc9b38e3",
        "hascolor": false,
        "lastannounced": null,
        "lastseen": "2020-10-31T19:03Z",
        "manufacturername": "_TZE200_wmcdj3aq",
        "modelid": "TS0601",
        "name": "Smart plug 21",
        "state": {
            "alert": "none",
            "bri": 0,
            "lift": 0,
            "on": false,
            "open": true,
            "reachable": true
        },
        "swversion": null,
        "type": "Window covering device",
        "uniqueid": "bc:33:ac:ff:fe:45:7a:36-01"
    },

**Comment by gmitch64** [comment]
I'm guessing the errors are because it still thinks it's a plug, rather than a light, even though the JSON looks correct?


curl -H 'Content-Type: application/json' -X PUT -d '{"lift": 50}' http://192.168.42.130:80/api/XXXXXXXXXX/lights/2/state
[{"error":{"address":"/lights/2/state","description":"parameter, lift, not available","type":6}},{"error":{"address":"/lights/2/state","description":"missing parameter to set light state","type":5}}]

curl -H 'Content-Type: application/json' -X PUT -d '{"bri": 50}' http://192.168.42.130:80/api/XXXXXXXXXX/lights/2/state
[{"error":{"address":"/lights/2/state","description":"parameter, bri, not available","type":6}},{"error":{"address":"/lights/2/state","description":"missing parameter to set light state","type":5}}]p

Now, the "on" command is accepted, but doesn't do anything on the motor.

curl -H 'Content-Type: application/json' -X PUT -d '{"on": true}' http://192.168.42.130:80/api/XXXXXXXXXX/lights/2/state
[{"success":{"/lights/2/state/on":true}}]


G

**Comment by Smanar** [comment]
>Clean compilation this time, not sure why I was getting an error last time.

It s because I m on several device in same time, and use the github to transfert the code from a machine to another, the code have moved 10/15 time just today ^^, you have made a "git pull" just beetween a corrective.

For the plug type, it s something normal, look at the node title in deconz "Smart Plug" it s the real value, send by the device itself, I m using a hack for the type was "Window covering device" but for zigbee standard, this device is a plug.

But why a thermostat in phoscon ? Here, I realy don't have idea ...

And you have made a mistake with your command, you are using the id = 2, and on the json the id  = 21.

**Comment by gmitch64** [comment]
Dang, yup... 2 does not equal 21. SO, changing that to 21...

Open turns the motor one way
Close turns the motor the other way.
I can't find a way to stop the motor from turning - I presume once I set the limits it will stop, but there should be a command to stop it?

Lift and Bri generate a success error message, but don't do anything with the motor. Is that expected?


G

**Comment by gmitch64** [comment]
As for Phoscon, I just use that for doing the inclusion, and making sure that the lights work.

In the DeConz GUI, it's still showing as a Smart Plug - is that how it should be? And not a light?


G

**Comment by Smanar** [comment]
>In the DeConz GUI, it's still showing as a Smart Plug - is that how it should be? And not a light?

Yep, hack are forbidden in deconz ^^, deconz is a "zigbee management software" not a domotic app, so the zigbee rules need to be respected at maximum for me, that you see in deconz need to be the reality.

To stop the covering
`curl -H 'Content-Type: application/json' -X PUT -d '{"stop": true}' http://IP:PORT/api/KEY/lights/ID/state`

And yes, it depend of device, but generally they need a calibration step, to stop itself and to use the "bri"/"lift command.

But if you still have problem for calibration pls use a similar issue or create  a new one, we have realy abuse with PR usage ^^.

**Comment by gmitch64** [comment]
Yes, "stop": true does stop the motor. I should have tired that - I was expecting to see something in the state area for that; my bad.

Once I get my screen hung, I'll get the limits set, and see if the bri/lift start working at that point. If not, then I'll open a new issue, as you are correct, we (I), have probably abused this PR.

One last question, will these updates hit 5.87 at the start of November, or will they need to wait till the beta of 5.88 in the middle of the month?


G

**Comment by Smanar** [comment]
Lol, not possible to be sure
```
Next Beta: 2.05.88 expected at the 15th of November.
Next Stable: 2.05.87 expected at 8th November.
```

if the code is to much sensible for a stable, they can decide to validate then only for the beta.

**Pull request merged**
