### PR TITLE
Adds Sengled E11 bulbs as RGBWW

### PR DESCRIPTION
**Pull request by magikid**
This should allow the bulb to be set to either color or white.
I followed #5284 for inspiration on how to fix this bulb.  It is related to issue #4833 except it's a slightly different model.

### CODE REVIEW

**Comment by Mimiix** [comment]
This could be done with a DDF afaik

**Comment by magikid** [comment]
@Mimiix What's a DDF?

**Comment by Mimiix** [comment]
Device Descriptor Files. New way of adding devices to deCONZ.

https://dresden-elektronik.github.io/deconz-dev-doc/

**Comment by magikid** [comment]
I'll take a look and see if I can figure it out with a DDF.

**Pull request closed without merging**
