### PR TITLE
New supported devices and updates

### PR DESCRIPTION
**Pull request by SwoopX**
- Added initial support for Legrand DIN power consumption module (#2456)
- Added initial support for Tuya/Blitzwolf TS0201 temp./hum. sensor (#2442)
- Added initial support for GS SKHMP30-I1 smart plug (#2453)
- Added initial support for Develco SMRZB-332 Smart Relay DIN (#2464)
- Added initial support for iris motion sensor v3 (#2460)
- Allow bindings for Xiaomi devices
- Fixed battery reporting for Xiaomi ZB3.0 light sensor
- Added initial support for iHorn temperature and humidity sensor (#2406)

### CODE REVIEW

**Comment by Smanar** [comment]
@SwoopX I have added a type to Legrand DIN device https://github.com/Smanar/deconz-rest-plugin/commit/0dfab3ae5bea74bd0487d201eeca6f22aaee1d3e

But impossible to find the device ID 0x000d I can't say if it's for DIN device, measurement device, or other ....

**Comment by SwoopX** [comment]
Ah, sorry. Did the commit to my repo already on Sat or Sun. Happy to include what's required from your end.

**Comment by Smanar** [comment]
NP.
And I m not sure Xiaomi device need binding, I m not sure if they can support them.
They don't use attribute reporting.

**Comment by SwoopX** [comment]
> And I m not sure Xiaomi device need binding,

The newer ZB3.0 obviously do. We can sharpen it if required and any interference with the older ones is observed.

Btw, 0x000d is "Consumption Awareness Device". I added that just recently to general.xml. Not sure if that is picked up though...

**Comment by Smanar** [comment]
Woaaa, where have you find it ? lol, I have spent more than 2h searching on google.

Interferences, no I don't think, but useless command on batterie device. I don't remember this whiteliast is only for binding or reporting too ?

**Comment by SwoopX** [comment]
😄 Found it here http://read.pudn.com/downloads703/ebook/2827955/docs-05-3520-29-00ha-home-automation-profile-specification.pdf

If I'm not mistakeb, the Xiaomi amendment is for binding only. However, if I recall correctly, in the web plugin code this is shortly followed always by a configure reporting function. I'd prefer reporting over polling, as it is potentially more battery saving than polling as to my understanding. So far, never experienced that reporting is not (generally) supported. E.g. polling of my smart plugs just creates noise in the air and tons of useless events in my middleware logs. Pure reporting would be more efficient and I consider polling more as a fallback scenario these days.

Like I said, my understanding might be wrong.

**Comment by Smanar** [comment]
Thx for the doc.

But take care, if the device don't support report (and if you ask for it), deconz make pooling itself.
I had the problem for some device, for maesurement there is power/current/voltage, but only power is working, deconz have tried to enable reporting on the three, but as it never receive report for 2 of them, it have enabled pooling on them, and pooling generates a lot of traffic.

**Comment by manup** [comment]
Hi thanks a lot for the PR, can you please merge the latest changes from master as well?

**Comment by SwoopX** [comment]
There u go :)

**Comment by Slothinger** [comment]
Hi, 
I compiled the libde_rest_plugin.so with the changes and replaced it with the old one under /usr/share/deCONZ/plugins. 
Should i see the sensor now in phoscon as a sensor?  (Want to use it with Home Assistant)

**Comment by Smanar** [comment]
Generaly, you need to re-include the device (API creation are done during inclusion), it can work without removing it, but better having a clean base for test.

**Comment by Slothinger** [comment]
So i deleted the device in deconz gui and after reconnecting and checking the correct temp and humidity values its still not possible to add the sensor in phoscon.  (Sensors -> Add new sensor -> Other)

**Comment by SwoopX** [comment]
Folks, let's move back to the original request to stay clean here and allow everybody to participate in the discusstion. I'll reply there...

**Pull request merged**
