### PR TITLE
Initial support for zigfred uno and zigfred plus smart in-wall switches by Siglis

### PR DESCRIPTION
**Pull request by Atokulus**
Initial support for zigfred uno and zigfred plus smart in-wall switches by Siglis.

This pull request builds upon and supersedes pull request GH-6280 and #6258

Many thanks go to @WhistleMaster and @Smanar for the initial code.

Best regards
Markus, Team zigfred

### CODE REVIEW

**Comment by manup** [comment]
I did a little test with my zigfred uno, it joined right away and the DDF was picked up. Cool that the color LED can be controlled with its own endpoint :) The button event cluster 0xFC42 was available after updating the switch from version 26 to version 29 via the app.

The events x000, x001 and x003 are emitted for buttons 100x – 400x once they are all configured in the app.
Instead of x000 (initial press) you may consider using x002 for short press?

**Comment by WhistleMaster** [comment]
The x002 is already used for the double press event if I'm not wrong :)

**Comment by manup** [comment]
Not quite, the x002 is short released and x0004 is double press, the values were originally derived from the first Hue dimmer switch and have been extended over time. For a quick ref the sensor.h header has the defines for the last digit / action:

https://github.com/dresden-elektronik/deconz-rest-plugin/blob/449ab29e1548af8e95631ae2d0c4ef14fe9d14f8/sensor.h#L19-L32

**Comment by WhistleMaster** [comment]
In Deconz indeed but I meant for the device itself. According to @Atokulus, the button state is encoded in the following way:

```
typedef enum {
  BUTTON_RELEASE = 0x00,
  BUTTON_CLICK = 0x01,
  BUTTON_DOUBLE = 0x02,
  BUTTON_HOLD = 0x03,
} zf_button_state_t;
```

**Comment by Smanar** [comment]
Ha yes, lol, haven't see that, but the "deconz rule"  are here too https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Supported-Devices#events-legend

for me the correct is

```
typedef enum {
  BUTTON_RELEASE = 0x02, //Release after short press
  BUTTON_CLICK = 0x00,  //Not used
  BUTTON_DOUBLE = 0x04, // Release after double clic
  BUTTON_HOLD = 0x03,
} zf_button_state_t;
```

**Comment by WhistleMaster** [comment]
That means that a mapping should be done in the DDF. 

Is that something that could be done easily in the `eval:` part of the DDF ?

**Comment by manup** [comment]
> Yes ofc, it the place to do that, for this device all the "magic" is done in the DDF for the mapping.
> 
> `"eval": "const eventLookup = [0x03, 0x02, 0x04, 0x01]; Item.val = (ZclFrame.at(0)+1) * 1000 + eventLookup[ZclFrame.at(1)]"`

I can confirm with this the expected x002 events are emitted.

**Comment by manup** [comment]
I've merged the PR and adapted the x002 events in https://github.com/dresden-elektronik/deconz-rest-plugin/commit/4464fe8e9fc9897720cf481a2d5330cd895484b2

**Pull request merged**
