### PR TITLE
Update FW version string for Mijia Light Sensor GZCGQ01LM

### PR DESCRIPTION
**Pull request by SwoopX**
- Updates the FW version string
- Removes legacy device code

### CODE REVIEW

**Comment by manup** [comment]
Can you please rebase on latest master, GIT complains about conflicts due the other merged PRs.

**Comment by SwoopX** [comment]
@manup done

**Comment by manup** [comment]
Looks like there is a missing comma?

image

```
cat xiaomi/xiaomi_gzcgq01lm_light_sensor.json | jq
parse error: Expected separator between values at line 70, column 17
```

Note to myself, we need a GitHub action to validate JSON files :)

**Comment by SwoopX** [comment]
Yeah, should indeed be validated 🙂

**Pull request merged**
