### PR TITLE
Initial support for Tuya Single Phase 65A Din Rail Smart Energy Meter

### PR DESCRIPTION
**Pull request by Smanar**
- Manufacturer: _TZE200_byzdayie
- Model identifier: TS0601

Nothing special, just use some more tuya command
see https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4957

### CODE REVIEW

**Comment by leonardpitzu** [comment]
For some reason the energy value seems to be negative right now.

**Comment by leonardpitzu** [comment]
Well, something is really weird - since you made the PR i had it build locally and the meter was counting as expected (positive, incerasing values). Now the value is negative and is trending towards zero.
I hope the logs is ok - i made it from my phone (i'm not home, next to a computer)
[debug.txt](https://github.com/dresden-elektronik/deconz-rest-plugin/files/7498993/debug.txt)

**Comment by Smanar** [comment]
```
19:35:38:095 Tuya debug 4 : Address 0xB4E3F9FFFEC9FC7A Payload 0076110200040000ac1a
19:35:38:095 Tuya debug 5 : Status: 0 Transid: 118 Dp: 529 (0x02,0x11) Fn: 0 Data 44058
19:35:38:102 Websocket 192.168.0.10:47906 send message: {"e":"changed","id":"60","r":"sensors","state":{"consumption":-21478,"lastupdated":"2021-11-08T17:35:38.100"},"t":"event","uniqueid":"b4:e3:f9:ff:fe:c9:fc:7a-01-0702"}
```

44058  = 0xAC1A

I m using the type

`qint16 energy = static_cast<qint16>(data & 0xFFFF);`

so value > 32 767 are negative
44058 = 65 535 - 44058  = 214 78.

I have updated the code with quint32

**Comment by leonardpitzu** [comment]
i updated as well the code on my side and it's ok, thanks.

**Comment by leonardpitzu** [comment]
I finally managed to integrate the meter in HA Energy. Only now i have noticed that the energy values are off by a factor of 10. How i figured it out? I have a smart plug measuring the usage of the house router, NAS, UPS, etc. The power, thus energy are mostly constant. It uses about 1.6kWh per day. Now this is part of the consumption of the whole house which, while i was  away on a small Christmas vacation, was less than what the "data center" used. This can't be true. I double checked with the outdoors energy meter (the one from the electricity provider) and yes, the measurement of this meter is smaller by a factor of 10. I fixed it locally by multiplying the energy by 10 and recompiling. It all sums up correctly now.

**Comment by Smanar** [comment]
Have updated the branch, and with your change, if I m good ?
https://github.com/Smanar/deconz-rest-plugin/commit/e9a5ffe0fef06d53340c8ab9702462b335cc577f#diff-e26cc016feb71ae607b1eecfd627df205b6faa96793f0c7cf676dd55f5ec4b51

**Comment by leonardpitzu** [comment]
great, thanks!

**Comment by Smanar** [comment]
PR canceled, support added with DDF https://github.com/dresden-elektronik/deconz-rest-plugin/pull/6465

**Pull request closed without merging**
