### PR TITLE
Update and rename _TZ3000_d16y6col_water_sensor.json to _TZ3000_water…

### PR DESCRIPTION
**Pull request by flopp999**
…_sensor.json

added two manufactures

### CODE REVIEW

**Review by SwoopX — APPROVED** [review]

**Comment by SwoopX** [comment]
@flopp999 @manup Just wondering if it wouldn't make more sense to name the DDF file like `ts0207_water_sensor.json`, was the manufacturer is more likely to change...

**Comment by flopp999** [comment]
> @flopp999 @manup Just wondering if it wouldn't make more sense to name the DDF file like `ts0207_water_sensor.json`, was the manufacturer is more likely to change...

**Comment by flopp999** [comment]
@SwoopX yes, TS0207 which is the model I'd is much better to use.

**Comment by manup** [comment]
Good question while the modelid often if the same for the Tuya variants of the same device, there are also some where even the modelid changes. But it seems that modelid is a lesser moving target than the manufacturer name.

**Pull request merged**
