### PR TITLE
DDF for Tuya 3-gang switch (_TZ3000_w3c7ouru)

### PR DESCRIPTION
**Pull request by Smanar**
- Product name: MOES Wireless Remote Switch
- Manufacturer: _TZ3000_w3c7ouru
- Model identifier: TS0043
- Device type : 3 gang switch

Untested, but I just think it one more clone, see https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6724

### CODE REVIEW

**Comment by Sjonnie2018** [comment]
I must admit I am not familiar with the concept of PR's and how they are supposed to get admitted/approved. Is there anything I can do to "help" the process? I would like to get the switches working as I need to automate the last room in my house.

If I inadvertently abused the guidelines or overstepped then I am sorry.

Thank you!

**Comment by Smanar** [comment]
No don't worry, manup is away for somes days, so i take more time, but there is no problem.
There is another PR on the same file, so we will probably have a conflicy, but nothing complex.

**Comment by Sjonnie2018** [comment]
Thank you for your reply, Smanar! I will wait for Manup to return and approve the PR. I saw another PR on the DDF from BabaIsYou which is probably the one you're referring to. Can't be too difficult indeed ;)

**Comment by Smanar** [comment]
@manup There is a problem on this PR ?

**Comment by manup** [comment]
@Smanar sorry GitHub now complains a merge conflict, can you please have a look?

**Comment by Smanar** [comment]
Corrected.

**Pull request merged**
