### PR TITLE
Support iCasa in-wall switch, Hampton Bay fan controller

### PR DESCRIPTION
**Pull request by ebaauw**
See #1124, #932.

### CODE REVIEW

**Comment by ebaauw** [comment]
@manup can you still include this in 2.05.65?

**Comment by manup** [comment]
Unfortunately 2.05.65 was already build yesterday, however 2.05.66 will follow quickly within the next two days.

**Comment by ebaauw** [comment]
Thanks.  I want this one out of the way before messing with `setLightState()`.

**Comment by ebaauw** [comment]
Remove `state.x` and `state.y` from websocket notification. These have been deprecated in v2.05.61 in favour of `state.xy`, see #1357.

**Comment by ebaauw** [comment]
Support Heiman CO sensor (newer model), see #1563.

**Comment by deven2020** [comment]
Hi. What model of Hampton Bay fan controller works with deconz. Does this controller works with any ceiling fan or just Hamton Bay?

**Pull request merged**
