### PR TITLE
eCozy Thermostat and more

### PR DESCRIPTION
**Pull request by ebaauw**
- Additional support for the eCozy Thermostat, see #2393.  Still work in progress:
  - Full GUI support for _Thermostat_ cluster, including schedules and tracking setpoint changes;
  - Support _Time_ cluster as `ZHATime` `/sensors` resource;
  - Sync on-device hardware clock with system clock;
  - Fix hang in API plugin when receiving a schedule with more than one transition;
  - Expose _PI Heating Demand_ as `state.valve`;
  - Base `config.scheduleron` on _Temperature Setpoint Hold_.
- Report `lastseen` with a resolution of minutes, and issue at most one web socket notification per minute per device for `lastseen`;
- Bug fix: the colour attributes for _Color Light_ lights weren't updated, see #3079.

### CODE REVIEW

**Comment by ebaauw** [comment]
Hm, I was still working on this one.  The changes are not complete, see #2393.

**Comment by ebaauw** [comment]
Getting a segmentation fault in v2.05.80 when reading an old-version schedule from the database.
```
$ gdb /usr/bin/deCONZ core-deCONZ-sig11-user1000-group1000-pid2656-time1597505417
(...)
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
Core was generated by `/usr/bin/deCONZ --http-port=80 --dbg-info=2 --dbg-aps=2 --dbg-error=1'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x75fe247c in QString::split(QString const&, QString::SplitBehavior, Qt::CaseSensitivity) const ()
   from /usr/lib/arm-linux-gnueabihf/libQt5Core.so.5
[Current thread is 1 (Thread 0x76fbea00 (LWP 2656))]
(gdb) bt
#0  0x75fe247c in QString::split(QString const&, QString::SplitBehavior, Qt::CaseSensitivity) const ()
   from /usr/lib/arm-linux-gnueabihf/libQt5Core.so.5
#1  0x6bd9d2e8 in DeRestPluginPrivate::deserialiseThermostatTransitions(QString const&, QList<QVariant>*) ()
   from /usr/share/deCONZ/plugins/libde_rest_plugin.so
#2  0x6bd9eb3c in DeRestPluginPrivate::deserialiseThermostatSchedule(QString const&, QMap<QString, QVariant>*) ()
   from /usr/share/deCONZ/plugins/libde_rest_plugin.so
#3  0x6bd5bf40 in DeRestPluginPrivate::sensorToMap(Sensor const*, QMap<QString, QVariant>&, ApiRequest const&) ()
   from /usr/share/deCONZ/plugins/libde_rest_plugin.so
#4  0x6bd5cda4 in DeRestPluginPrivate::getAllSensors(ApiRequest const&, ApiResponse&) ()
   from /usr/share/deCONZ/plugins/libde_rest_plugin.so
#5  0x6bd6d3a4 in DeRestPluginPrivate::handleSensorsApi(ApiRequest const&, ApiResponse&) ()
   from /usr/share/deCONZ/plugins/libde_rest_plugin.so
#6  0x6bcc9dc0 in DeRestPlugin::handleHttpRequest(QHttpRequestHeader const&, QTcpSocket*) ()
   from /usr/share/deCONZ/plugins/libde_rest_plugin.so
#7  0x000bd06c in zmHttpClient::handleHttpRequest() ()
#8  0x7615fbfc in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/arm-linux-gnueabihf/libQt5Core.so.5
#9  0x76402964 in ?? () from /usr/lib/arm-linux-gnueabihf/libQt5Network.so.5
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```

**Comment by ma-ca** [comment]
> Rename `config.scheduleron` to `config.schedule_on` and expose _Temperature Setpoint Hold_ (0x0023) as `config.schedule_on`

@ebaauw The Bitron Thermostat 902010/32 does not have attribute 0x0023 and the `config.scheduleron` was originally mapped to attribute _Thermostat Programming Operation Mode_ 0x0025. This is a breaking change.

I am using HomeKit to turn off and on the Bitron Thermostat scheduler. In HomeKit the thermostat status on or off was mapped to the scheduler being enabled or disabled. That is a very useful feature for me, for example when leaving for holidays in the winter time. 

Is it possible to revert the that change and bring back the mapping in HomeKit between scheduler and thermostat status? Or at least to make it configurable how the thermostat scheduler is mapped into HomeKit?

**Comment by ebaauw** [comment]
Does the Bitron support on-device schedules?  Using the Zigbee standard or some proprietary method?

I only mapped `config.schedule_on` to 0x0023 for the eCozy; for others it’s still mapped to 0x0025.

I think there’s something wrong in the way Homebridge Hue currently uses the _Thermostat_ mode.  In HomeKit, you can set the target mode to _Off_, _Heat_, _Cool_, or _Auto_, indicating whether the thermostat should automatically heat, cool, or both.  The current mode is _Off_, _Heat_, or _Cool_, indicating whether the thermostat is currently heating or cooling.  This has nothing to do with whether the schedule is enabled.  It also has nothing to do whether the Spirit is in automatic mode (where it sets the valve position based on the heatsetpoint) or in manual mode (where you set the value position manually).

Eve shows a separate on/off switch for the schedule, I want to see if I can map that to `config.schedule_on`.  I also want to support setting the on-device from Eve.  Showing the on-device schedule in Eve won’t always be possible, since the on-device schedule is way richer than the Eve schedule.  See https://github.com/ebaauw/homebridge-hue/issues/728.

**Comment by ma-ca** [comment]
> Does the Bitron support on-device schedules? Using the Zigbee standard

Yes, using Zigbee standerd. I did add support in PR #1003 for Thermostat cluster (including get/set schedule) and Bitron Thermostat 902010/32.

> I only mapped `config.schedule_on` to 0x0023 for the eCozy; for others it’s still mapped to 0x0025.

Makes me happy again.

> I think there’s something wrong in the way Homebridge Hue currently uses the _Thermostat_ mode.

That is true. I don't use Eve very often and was not aware about the option _Enabled_  in the thermostat. Anyway, I am also happy to use Eve to enable and disable the scheduler.

**Comment by ebaauw** [comment]
> I did add support in PR #1003 for Thermostat cluster (including get/set schedule) and Bitron Thermostat 902010/32.

Ah, cool.  Did you see in #2393 that `config.schedule` now returns proper JSON and that I changed the way the schedule is set?  Also, I setup periodically reading the schedule for the eCozy, we might want to do the same for the Bitron.  Does the Bitron support attribute reporting for all (relevant) attributes, or do we need to poll it for some of the attributes?

**Comment by ebaauw** [comment]
Another question, @ma-ca: how does the Bitron handle the timing of the schedule?  Does it have an on-device clock?  How do you keep that sync'ed?

**Comment by ma-ca** [comment]
> how does the Bitron handle the timing of the schedule?

The Bitron has a Time cluster that syncs the attributes for UTC time, time zone, dst start, dst end and dst shift.

**Comment by ma-ca** [comment]
> Does the Bitron support attribute reporting for all (relevant) attributes, or do we need to poll it for some of the attributes?

Reporting is enabled and configured every 5 minutes for attribute 0x0000. Polling is already configured every 15 minutes for attributes 0x0012, 0x0025 and 0x0029.

**Comment by ebaauw** [comment]
> The Bitron has a Time cluster that syncs the attributes for UTC time, time zone, dst start, dst end and dst shift.

Is that a client (grey) _Time_ cluster, or a server (blue) one?  Does it find the _Time_ cluster on the coordinator and sync itself automatically?  Or did you set something up?

**Comment by ma-ca** [comment]
A Time server cluster that syncs automatically to the coordinator. I did implement #774 especially for the Bitron.

**Comment by ebaauw** [comment]
The Bitron also supports 0x0030, 0x0031, and 0x0032, so it could also expose `config.lastchange`.

**Comment by ma-ca** [comment]
> There's a bug in the eCozy that it reports _Setpoint Change Time Stamp_ in local time instead of UTC. Does the Bitron do the same?

The Bitron attribute 0x0032 value is the correct UTC time (right after changing heat setpoint the 0x0032 attribute value is close to _Time_ cluster 0x000A attribute 0x0000 value with UTC time)

**Pull request merged**
