### PR TITLE
DDF for iluminize motion sensor (5128.10)

### PR DESCRIPTION
**Pull request by AndreKoepke**
See #7045

### CODE REVIEW

**Comment by AndreKoepke** [comment]
I tried it with in my local home. This ddf seems to be working (setting lift/tilt works without any problems).

It was the first time, that I wrote a ddf. I just copied it and changed the adresses.

**Comment by BabaIsYou** [comment]
Did not really understand binding on cluster "0x0102" "`cl": "0x0102"` on endpoint 6  `"src.ep": 6`, because device descibes on referenced issue doesn't have endpoint 6

**Comment by AndreKoepke** [comment]
@BabaIsYou  
I am very new to DDF and I guessed the values. But from your comment I learned that `"cl"` stands for `cluster`. :D  
Feel free to edit. I can test it with my devices.

**Comment by BabaIsYou** [comment]
Think you should have a look to https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/DDF-cheat-sheet then would understand what I meant ;-)

**Comment by AndreKoepke** [comment]
I will read it and fix the JSON. ^^  
It turns out that after a while, that the value-report don't works as expected. :/

**Comment by BabaIsYou** [comment]
As the device is quite simple, perhaps it would be better to start from scratch using DDF editor and compare the final DDF with the one you did ;-)

**Comment by AndreKoepke** [comment]
:D  
I tried to write the plain JSON while there is a DDF editor. omg. 

I fix the JSON and I will change it here, when the tests are successful and my slow train-vpn-forwarded-x11-ssh-connection allows my to save.

**Comment by BabaIsYou** [comment]
I did the changes from EP 6 to EP 1 into the DDF but you have to test before merging and close #7045

**Comment by AndreKoepke** [comment]
Ok. I dropped the settings via DDF-editor and it from the default-values. Maybe the endpoint came from there.

On the first view, it seems to be working. I will report again, when I'm back home.  
Thanks for the change. :)

**Comment by AndreKoepke** [comment]
Seems good. ready4merge from my site.

**Comment by manup** [comment]
@BabaIsYou all good to merge?

**Pull request merged**
