### PR TITLE
Update hs1sa_smoke_sensor.json

### PR DESCRIPTION
**Pull request by MSL-DA**

### CODE REVIEW

**Comment by Smanar** [comment]
To make a DDF compatible with 2 devices need to use

```
  "manufacturername": ["HEIMAN", "Heiman"],
  "modelid": ["SmokeSensor-EF-3.0","Model id2"],
  "vendor": "HEIMAN",
```

manufacturername and modelid need to be exactly the same than you can see in the GUI

**Comment by Smanar** [comment]
Same problem ^^

```
  "manufacturername": "HEIMAN, Heiman",
  "modelid": "SmokeSensor-EF-3.0, SmokeSensor-EF-3.0",
```

There is 2 devices ? One with "HEIMAN" and another with "Heiman" ?

**Comment by MSL-DA** [comment]
> Same problem ^^, this can't work
> 
> ```
>   "manufacturername": "HEIMAN, Heiman",
>   "modelid": "SmokeSensor-EF-3.0, SmokeSensor-EF-3.0",
> ```
> 
> There is 2 devices ? One with "HEIMAN" and another with "Heiman" ?

Yes ... if I specify Heiman in my DDF, it is not selected. I have to write HEIMAN

**Comment by MSL-DA** [comment]
Is this correct?

```
  "manufacturername": "HEIMAN, Heiman",
  "modelid": "SmokeSensor-EF-3.0",
  "vendor": "HEIMAN",
  "product": "HS1SA"
```

**Comment by Smanar** [comment]
So it mean, if you look on deconz the device Manufacture name is `HEIMAN, Heiman` ?

**Comment by Smanar** [comment]
```
    "manufacturername": [
  "modelid": "SmokeSensor-EF-3.0, SmokeSensor-EF-3.0",
    "HEIMAN",
  "vendor": "HEIMAN",
    "Heiman"
  ],
  "modelid": [
    "SmokeSensor-EF-3.0",
    "SmokeSensor-EF-3.0"
  ],
```

This is fine, it mean you can have a device with Heiman/SmokeSensor-EF-3.0 and another with HEIMAN/SmokeSensor-EF-3.0

**Comment by Smanar** [comment]
@MSL-DA why have you cancelled your PR ?

**Pull request closed without merging**
