### PR TITLE
Improve : Add "duration" for the tuya siren

### PR DESCRIPTION
**Pull request by Smanar**
Model :
- _TYST11_d0yu2xgi
- _TZE200_d0yu2xgi

Add the config/duration field, to set siren duration.

### CODE REVIEW

**Comment by ebaauw** [comment]
Why cannot you use `ontime`, which is already used for other sirens?

**Comment by Smanar** [comment]
Because of tuya ^^.

On other siren, they use a request on IAS_WD_CLUSTER_ID with all params
On this one you have just a command to enable disable the siren. If you want to change the duration in same time, you need to make 2 requests, and this device is realy slow, not powerfull hardware.

**Comment by ebaauw** [comment]
So as an API client, I would need to know and understand the difference beween a regular (_IAS WD_) siren and a Tuya siren?  That doesn't seem right.

**Comment by SwoopX** [comment]
We have no resource item for `ontime` yet. It would probably make sense to create it non-public for config...

**Comment by ebaauw** [comment]
It's a write-only `state` attribute, like `transitiontime`.

**Comment by SwoopX** [comment]
Oki, but regardless if `state` or `config` (I know we have that generally available), we don't have any resource item for this as `rest_lights.cpp` does a direct string comparison on the parameters actually provided via API in contrast to `rest_sensors`, which does it indirectly by iterating over the available resource items.

No clue which approach would be faster/more beneficial though and which should be "standard" in the end though. Fun fact: `ontime` is not even mentioned in the API documentation (presumably because there's no resource item) 😂

**Pull request closed without merging**
