### PR TITLE
Fix for Xiaomi Aqara Single Switch Module T1 (With Neutral)

### PR DESCRIPTION
**Pull request by SwoopX**
- Whitelist for binding
- Calculate the correct power values
- Do not expose current and voltage

### CODE REVIEW

**Review by andudi — CHANGES_REQUESTED** [review]
compilation error in de_web_plugin.cpp:9417
-> only two closing brackets instead of three
-> and after the brackets the or operator (||) is missing

**Comment by andudi** [comment]
with this commit, binding of switch and sensors are working like a charm, thank you!

**Comment by dpozimski** [comment]
on my side it's working too

**Review by manup — APPROVED** [review]

**Comment by cobch** [comment]
Does sensors appear in deconz? I only get switch entity but no luck with sensors such as power or energy. Please update whether it is working or not since I will return my aqara module otherwise )-';

**Comment by andudi** [comment]
yes is working for me. i will send you some config details soon...

On 27. Dezember 2021 19:37:30 MEZ, cobch ***@***.***> wrote:
>Does sensors appear in deconz? I only get switch entity but no luck
>with sensors such as power or energy. Please update whether it is
>working or not since I will return my aqara module otherwise )-';
>
>--
>Reply to this email directly or view it on GitHub:
>https://github.com/dresden-elektronik/deconz-rest-plugin/pull/4768#issuecomment-1001694437
>You are receiving this because you commented.
>
>Message ID:
***@***.***>

--
Diese Nachricht wurde von meinem Mobiltelefon mit Kaiten Mail gesendet.

**Pull request merged**
