### PR TITLE
DDF: Add support for another variation of a Tuya door sensor TS0203 (_TZ3000_oxslv1c9)

### PR DESCRIPTION
**Pull request by aronsky**
Based on work by @Smanar (only the suffix had to be changed)

### CODE REVIEW

**Comment by Smanar** [comment]
Just for information, if the device is a clone, a same DDF can be used for 2 devices

```
  "manufacturername": ["_TZ3000_oxslv1c9", "second(manufacture_name"],
  "modelid": ["TS0203", "TS0203"],
```

**Comment by aronsky** [comment]
Huh, I had no idea. I assume that, in this case, the `modelid` field should actually remain a single string, since it's the same? Or does the length of "manufacturername" and "modelid" lists has to match?

**Comment by Smanar** [comment]
Yep, they need to match (need to use all field even they are same)

```
  "manufacturername": ["manu_device1", "manu_device2"],
  "modelid": ["modelid_device1", "modelid_device2"],
```

**Comment by aronsky** [comment]
Done.

**Comment by Smanar** [comment]
Nice, thx, for me its beter because there is a new tuya clone every day, if we make a new file every time ....

**Comment by Smanar** [comment]
Hello, I have something to ask you ^^.

There is an user with another tuya clone, that work with this DDF too, if you can add it to the list too ?
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6265

Manufacture name : _TZ3000_7tbsruql
Model id  : TS0203

**Comment by aronsky** [comment]
No problem, done.

**Comment by Smanar** [comment]
Thx ^^

**Pull request merged**
