### PR TITLE
Add ddfvalidate validation option

### PR DESCRIPTION
**Pull request by Zehir**
Like we discuss on discord this PR add support for ddfvalidate option and set that flag on some exotic DDF

### CODE REVIEW

**Comment by Zehir** [comment]
With this PR we have only one error left about : 
https://github.com/dresden-elektronik/deconz-rest-plugin/blob/086ee3d32cc6488be92c33fc1740fd50ca24707d/devices/xiaomi/xiaomi_mccgq14lm_e1_openclose_sensor.json#L50-L61

CL is not allowed here, should we update the DDF or the bundle ?

**Comment by Zehir** [comment]
From : https://github.com/dresden-elektronik/deconz-rest-plugin/commit/086ee3d32cc6488be92c33fc1740fd50ca24707d

**Comment by ebaauw** [comment]
Some remarks, not necessary blocking atm, but food for thought for further development:
- @manup suggested a (top-level) item for this, which would be exposed by the API, so API clients could ignore devices exposed in a non-standard way;
- Ideally, this item would be set by the DDF bundler, based on the validator output;
- For me, this seems related to the (Gold, Silver, Brons) `status`, which we might also want to expose over the API.  E.g. as API client, I might want to support only Gold devices.  I don't think any DDF failing validation should be allowed to get Gold `status`;
- We might also expose the DDF file and version over the API, for easier trouble shooting.

**Comment by Zehir** [comment]
> * @manup suggested a (top-level) item for this, which would be exposed by the API, so API clients could ignore devices exposed in a non-standard way;

What you mean by top level item ?
You can query the DDF from the rest api so you can access to the definition like gold, or the ddfvalidate option

> * Ideally, this item would be set by the DDF bundler, based on the validator output;

You mean when you bundle the DDF he generate a new `ZHABundle` that contain `uuid`, `version`, `status`, `product`, ... ?

> * For me, this seems related to the (Gold, Silver, Brons) `status`, which we might also want to expose over the API.  E.g. as API client, I might want to support only Gold devices.  I don't think any DDF failing validation should be allowed to get Gold `status`;

I can easly do a validation rule to disallow status=gold with ddfvalidation=false. Should I add it now ?

> * We might also expose the DDF file and version over the API, for easier trouble shooting.

The DDF is already exposed;
https://github.com/dresden-elektronik/deconz-rest-plugin/blob/086ee3d32cc6488be92c33fc1740fd50ca24707d/rest_devices.cpp#L78-L87

> 
> > CL is not allowed here, should we update the DDF or the bundle ?
> 
> DDF, imho. Strictly speaking the C++ "allows" `cl`, but simply ignores it. Best for the validator to disallow it, I would think.

If it's does nothing he should not be here because we could expect the option to do something

**Comment by Smanar** [comment]
> I don't think any DDF failing validation should be allowed to get Gold status

Why ? A silver status mean the device will be not supported, A DDF can be working but not using "DDF rule".

**Comment by Zehir** [comment]
Nevermind I can't add this check easly because if `ddfvalidate` is false he won't validate at all but at least just the json format

**Comment by ebaauw** [comment]
> What you mean by top level item ?

An `attr/ddfvalidate` resource item, exposed as top-level attribute on the REST API resource.

> The DDF is already exposed;

Cool.  I didn't know that.  It only shows the contents though, not the filename and no version.  But at least clients can already get `ddfvalidate` through the `/devices/`_mac_`/ddf` endpoint.

> I can easly do a validation rule to disallow status=gold with ddfvalidation=false. Should I add it now ?

No, not now.

> And an user can choose to edit the "status" itself.

Indeed, that's why, I think, it should be set by the bundler (as part of "signing" the DDF).

I believe that every-one's entitled to their own misery, and I'm happy for deCONZ to expose cursed devices in a non-standard way.  However, I don't have the bandwidth to support devices exposed in a non-standard way in my Homebridge plugin.  I'm looking for a clear message to my users, so they know upfront which devices exposed by deCONZ will be supported by my plugin.  I'm guessing other API clients (including Phoson) will look for something similar.

**Comment by Zehir** [comment]
Intresting idea to add top level attributes for that but when you have devices with multiple subdevices how you decide who get the attributes ?

Maybe when you add attr/ items they are on each subdevices ?

Or maybe generate a ZHABundle for each loaded bundle but I think @manup has plans to create endpoints to list, add and delete bundle (ddf).

There is discussion of "depreciating" the status option to a signature process on the bundle. Still WIP

For the exotic devices I think you could redirect the users to my node red plugin. He just do an interface between node red and deconz, anything in is copied inside a node red message so an user could create his conversion flow using the homekit node red plugin. It's what I do when I have a too complex switch to only use the HA plugin and the deconz rules.

**Comment by manup** [comment]
Hi, good work, 

FYI there is a DDF bundle REST-API documentation (RFC only, not implemented yet).
... we need more documentation on what DDF bundles are and how they are supposed to work.

https://dresden-elektronik.github.io/deconz-rest-doc/endpoints/ddf

A few things to note for bundles:

In my opinion Gold, Silver, Bronze status is almost meaningless today since most DDFs are merged as Gold which weren't tested by many users. And worse Gold DDFs are changed and may (and do) break. So Gold status today means "trust me bro"  ;)

DDF bundles take a different approach:
* Each DDF has a unique ID like "550e8400-e29b-11d4-a716-446655440000" and a version "1.2.3" for tracking bundles.
* DDF bundles are immutable (100% no exceptions)
* Initially they are untested (like Bronze status)
* Later on once a DDF bundle is tested and feels alright we can sign it with the **Beta (like Silver) signature**, the bundle itself isn't changed (!) only the signature added.
* Later on once DDF bundle is tested even more and we feel it's worthy we add an additional **Stable (like Gold) signature**, again the bundle data isn't changed only the signature added.
* It's not possible to change a bundle without breaking the signatures, so no more breaking "Gold" changes
* **Any** change to a DDF or it's referenced files results in a new bundle which needs to go through the whole untested/beta/stable cycle again.

Note we can derive Gold/Silver/Bronze status values automatically from the signatures a bundle has and give them actual verified meaning.

A DDF bundle embeds *everything*, items, sub devices and Javascript files, in one `<bundle-filename>.ddf` file — like a GIT snapshot.

Switching between bundle versions will be easy™. On a per device/uniqueid (mac) basis. So when a new version is published you don't have to move 100 lights at once to the new DDF bundle, but can test on one and move back if it didn't worked.

* In the database a device will just be pinned to a specific bundle hash.
* In the Web UI you'll see there are different or newer versions for a device, .... update/downgrade should be 2 mouse clicks.
* The UI also shows the stable/beta/untested stuff perhaps as icon (don't wanna unstable stuff? just use stable bundles)


But back to the validation...

The validator is not allowed to change the actual DDF JSON (immutable!) but it can embed the validate result (true/false) in the bundle, and the deCONZ bundle loader can expose this as `attr/ddfvalidate_result` item.

Note: The top level item in this PR only says "do not validate", it's not the actual *result* of the validator. Not sure if we should expose these two things as separate items?

**Comment by ebaauw** [comment]
I would be interested to see that a DDF passed validation, not so much the difference between validation skipped vs validation failed.

**Comment by Zehir** [comment]
> I would be interested to see that a DDF passed validation, not so much the difference between validation skipped vs validation failed.

Where ? On the DDF Bundle page or from the rest api ?

I suppose for the homekit app you can filter out exotic devices that did not respect the validation ?

If the `attr/ddfvalidate_result` is added in the bundle that mean the bundler modify the DDF to add the item.

But I am not sure how deconz handle `attr/*` when there is multiple subdevices, for that case, should he we be added to the first subdevice or all subdevices ?

**Comment by ebaauw** [comment]
From the API.  But we'll probably have to wait for API v2, or at least for the RFC to materialise.

**Comment by manup** [comment]
> If the attr/ddfvalidate_result is added in the bundle that mean the bundler modify the DDF to add the item.

No it isn't allowed to change the DDF JSON, but the bundler can add this in another section perhaps even the DESCR would be a suitable place?

To expose this then via deCONZ REST-API the bundle loader in deCONZ would just attach the item at runtime.

>I would be interested to see that a DDF passed validation, not so much the difference between validation skipped vs validation failed.

Indeed for clients this is likely the only relevant information.

**Comment by Zehir** [comment]
So we add the validation result like the success boolean, errors list and the version of the validator. But either on the desc chunk or on a file with the name validation.json ?
What fo you prefer ?
Then in the rest api you expose it like you want. But note that will probably be optional

**Comment by Zehir** [comment]
@manup when we update the validator should we revalidate all uploaded bundle on the store ?

**Comment by Zehir** [comment]
I would like to see the `DESC` validation result like this ;
https://github.com/deconz-community/ddf-tools/blob/main/packages/bundler/README.md#validation-optional

The complete DESC content;

```json
{
  "version": "1.0.1",
  "source": "https://deconz-community.github.io/ddf-store/XXXX/XXXX",
  "last_modified": "2023-01-08T17:24:24z",
  "version_deconz": ">2.19.3",
  "product": "acme 2000",
  "links": [
    "url-to-forum-entry",
    "url-to-github-entry"
  ],
  "device_identifiers": [
    ["Philips", "acme 2000"],
    ["Signify", "acme 200"]
  ],
  "validation": {
    "result": "error",
    "version": "2.20.0",
    "errors": [
      {
        "message": "Unrecognized key(s) in object: 'cl'",
        "path": ["subdevices", 0, "items", 6, "parse"]
      },
      {
        "message": "Unrecognized key(s) in object: 'cl'",
        "path": ["subdevices", 0, "items", 9, "parse"]
      }
    ]
  }
}
```

#### validation (optional)

The result of the validation using the ddf-validator. It's a JSON object.
If there is no errors the `errors` property is omitted.

`result` can be `success`, `error` or `skipped`.

##### Example success

```json
{
  "result": "success",
  "version": "2.20.0"
}
```

##### Example error

```json
{
  "result": "error",
  "version": "2.20.0",
  "errors": [
    {
      "message": "Unrecognized key(s) in object: 'cl'",
      "path": ["subdevices", 0, "items", 6, "parse"]
    },
    {
      "message": "Unrecognized key(s) in object: 'cl'",
      "path": ["subdevices", 0, "items", 9, "parse"]
    }
  ]
}
```

##### Example skipped

```json
{
  "result": "skipped",
  "version": "2.20.0"
}
```

**Pull request merged**
