### PR TITLE
Fix TS0043_3gang_remote

### PR DESCRIPTION
**Pull request by Zehir**
Add missing modelid

### CODE REVIEW

**Comment by Zehir** [comment]
Duplicate of #6728

**Comment by Zehir** [comment]
@manup can you take a look at this PR until the PR #6728 get merged ? Thanks

**Comment by Zehir** [comment]
> Hi Zehir,
> 
> What do you think about suppressing `"refresh.interval": 84000, ` from `swversion` (the default value is already 86400 in generic json) and passing it to 86400 for` config/battery` ?

No idea I did not make this DDF, @Smanar could probably respond ?

**Comment by Smanar** [comment]
>passing it to 86400 for config/battery

Why not, will not have a big impact.

>about suppressing "refresh.interval": 84000, from swversion

It's probably possible, but as we are making a "custom swversion", It's personnal but I prefer make a complete attribute, if one day the generic json is edited for exemple.
And we have see an issue with drained battery on some device without a defaut refresh.interval in the DDF, was probably config/battery (there is no defaut value in the generic json so deconz probably spam the device) but I prefer avoid this issue.

**Comment by Zehir** [comment]
Maybe you could make this change in #6728 this PR is just to fix the model ID

**Comment by Smanar** [comment]
yep, right now.

**Pull request merged**
