### PR TITLE
DDF for Ikea Fyrtur roller blind

### PR DESCRIPTION
**Pull request by SwoopX**
As I don't own the device, it should ideally be tested before getting merged.

### CODE REVIEW

**Comment by manup** [comment]
@Mimiix do you have the Fyrtur?

**Comment by Mimiix** [comment]
> @Mimiix do you have the Fyrtur?

Yes.
But in my new home I don't have a place for it. I can do some tests but they wouldn't be extensive.

**Comment by alexander-rieder** [comment]
I have a Fyrtur. How can I test this? I have deconz as HA Add On installed.

**Comment by Smanar** [comment]
You have some return here https://forum.phoscon.de/t/ikea-fyrtur-is-not-showing-in-phoscon-and-therefore-not-in-ha/2689/11

The device is working (and need this PR to b included)

**Comment by ulbrich-media** [comment]
Just wanted to give feedback, since I'm running two of these roller blinds with the DDF of this PR for a couple of weeks now and they work perfectly.

**Comment by aradmidias** [comment]
Hello @SwoopX,

I came here from a different Issue with FYRTUR blinds, whose "brightness" can not be set using PWA: https://forum.phoscon.de/t/controlling-ikea-fyrtur-via-pwa-results-in-a-400-response-code/3060

But since I tested this DDF to some degree, I wanted to report my findings back here.

**Without this DDF (current behavior):**
* The brightness slider correctly displays the current "brightness" of this blind.
* The brightness slider can not be used to change the level or the brightness of the blind.
* Clicking of the Light-Bulb ICON of the blind will cause it to coil, but it will not unroll.
* The battery level in the deCONZ Desktop App seems to reflect the actually reported value.
* These Buttons in the `Window Covering Cluster` work: `Up`, `Down`, `Stop`, `Go To Lift Percentage`
* These Buttons in the `Window Covering Cluster` do **not** work: `Go To Lift Value`, `Go To Tilt Value`, `Go To Lift Percentage` (all three report `UNSUP_CLUSTER_COMMAND`)

**With this DDF:**
* The brightness slider does not display the current "brightness" of this blind:
   1. If the blind is fully closed (unrolled), PWA shows the ICON for a light being turned on; the brightness slider is at its top-most position. (basically expected behavior)
   2. If the blind is fully opened (coiled), PWA shows the ICON for a light being turned off; the brightness slider is at its bottom-most position. (basically expected behavior)
   3. If the blind is in any other state, PWA shows the ICON for a light, being turned off; the brightness slider remains at its bottom-most position. This seems undesired to me, as the slider does not indicate the blind's position any more. (**change in behavior**)
* The brightness slider can not be used to change the level or the brightness of the blind. (no change)
* Clicking of the Light-Bulb ICON of the blind has no effect. It triggers the same `transitiontime` error, as mentioned in the link to my forum post. (**Change in behavior**)
* The battery level in the deCONZ Desktop App seems to reflect the actually reported value. (no change)
* These Buttons in the `Window Covering Cluster` work: `Up`, `Down`, `Stop`, `Go To Lift Percentage` (no change)
* These Buttons in the `Window Covering Cluster` do **not** work: `Go To Lift Value`, `Go To Tilt Value`, `Go To Lift Percentage` (all three report `UNSUP_CLUSTER_COMMAND`) (no change)

I am not sure, if this change in behavior is intended.

**Comment by yan14** [comment]
Is there a plan when it will be added to a new version? I have a new blind an it has the same issue as https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6263
My old blind is visible in Phoscon and is available in Home Assistant as well. 
The new blind is missing in both.

**Comment by Smanar** [comment]
@manup and @SwoopX 
What do you want to do with this PR ?
Lot of user on the phoscon forum have issue on Fyrtur and kadrilj Covering. Previsouly included device are working, but not possible to re-include them, or add new one.
They need this PR or turn the status to "Gold" for the kadrilj one.

**Comment by SwoopX** [comment]
I consider this one ready to go and it also has been tested by at least one user.

**Comment by Smanar** [comment]
Same for me, and about the "Bronze" Status for kadrilj  ? We will see on next version ?

**Pull request merged**
