### PR TITLE
Add initial support for ZC-W1 (_tz3000_i8jfiezr)

### PR DESCRIPTION
**Pull request by Smanar**
- Product name: ZC-W1
- Manufacturer: _tz3000_i8jfiezr
- Model identifier: TS0201
Nothing special, see https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5292

### CODE REVIEW

**Comment by simontegelid** [comment]
I have a bunch of these sensors. What is needed to get this PR merged?

**Comment by Smanar** [comment]
I think it will be never merged, better to make a DDF file like for this one https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5483#issuecomment-981131783

**Comment by simontegelid** [comment]
Ah, I see. I did and it works like a charm! Thanks!

**Comment by Smanar** [comment]
Already ?
Lol, DDF seem so easy for some uers, BTW if you can share your ddf on the issue, can help other users.

**Comment by simontegelid** [comment]
Hehe, I just used [this DDF](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5483#issuecomment-986296532). Pasted it into a `ts0201.json` and put it into the mounted `/opt/deCONZ/devices/` directory to my deconz docker container. 

It took two minutes to realize that it worked, but I never understood why /opt/deCONZ/devices/ is the place for deconz to look for DDF files. According to [the DDF cheat sheet](https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/DDF-cheat-sheet) the location should be `/usr/share/deCONZ/devices/generic/` and [this](https://dresden-elektronik.github.io/deconz-dev-doc/modules/ddf/#directory-structure) indicates that the folder should be named `devices`, so when I found a directory named `devices`, I tried it and it worked.

**Comment by Smanar** [comment]
It's perhaps because of docker stuff ?
On my side, real installation, I don't have /opt/deCONZ folder.

**Comment by BabaIsYou** [comment]
As this device is covered by this DDF https://github.com/dresden-elektronik/deconz-rest-plugin/blob/f837452b4eec614746e3ba56f214b1096342a797/devices/tuya/_TZ3000_i8jfiezr_temp_hum_sensor.json#L4 , could we consider to close this PR ?

**Pull request closed without merging**
